### PR TITLE
fix: resolve moderation pubkey via NIP-05 instead of hardcoded value

### LINKED ISSUE #2317: fix: resolve moderation pubkey via NIP-05 instead of hardcoded value
## Parent Epic

Part of divinevideo/support-trust-safety#65 (User-facing moderation communication)

---

## Problem

`moderation_label_service.dart` has a hardcoded moderation pubkey (`121b915b...`) that is the old key. The current moderation identity pubkey is `8fd5eb6d8f362163bc00a5ab6b4a3167dbf32d00ec4efdbcf43b3c9514433b7e`, NIP-05 `moderation@divine.video`.

This means the mobile app is filtering on labels from a key that no longer signs anything. Moderation labels from the actual moderation service are invisible to the app.

## What should happen

1. Resolve `moderation@divine.video` via NIP-05 (`divine.video/.well-known/nostr.json?name=moderation`) to get the current pubkey at runtime
2. Fall back to the hardcoded pubkey `8fd5eb6d8f362163bc00a5ab6b4a3167dbf32d00ec4efdbcf43b3c9514433b7e` if NIP-05 resolution fails
3. Cache the resolved pubkey (NIP-05 doesn't change often)

This ensures the app always uses the right key, even if the moderation identity rotates again.

## What to change

- `mobile/lib/services/moderation_label_service.dart` line 92-93: update hardcoded fallback pubkey to `8fd5eb6d8f362163bc00a5ab6b4a3167dbf32d00ec4efdbcf43b3c9514433b7e`
- Add NIP-05 resolution for `moderation@divine.video` as the primary lookup, hardcoded as fallback

## Context

divine-web already has the correct pubkey hardcoded (`src/lib/videoVerification.ts`). The moderation-service unified signing to `NOSTR_PRIVATE_KEY` in PR #31 (Mar 13), removing the old `MODERATOR_NSEC`. The iac-coreconfig pubkey rotation PR #280 has merged.

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary
- Resolves `moderation@divine.video` via NIP-05 at runtime instead of relying on a stale hardcoded pubkey
- Falls back to the correct pubkey (`8fd5eb6d...`) when NIP-05 resolution fails
- Migrates legacy pubkey (`121b915b...`) out of existing users' stored subscriptions on first run

Closes #2317

### Core (`moderation_label_service.dart`)
- `divineModerationPubkeyHex` changed from `static const` to an instance getter backed by the NIP-05 resolved value
- New `_resolveModerationPubkey()`: checks SharedPreferences cache (24h TTL) → NIP-05 via existing `Nip05Validor.getPubkey()` → stale cache → hardcoded fallback
- New `_migrateLegacyPubkey()`: swaps old pubkey out of persisted labeler subscriptions (idempotent, runs every init)
- `removeLabeler()` uses the resolved instance field for the Divine labeler guard

### Consumers
- `safety_settings_screen.dart`: 4 refs updated from static to instance access; unused import removed
- `report_content_dialog.dart`: reads pubkey from `moderationLabelServiceProvider`; unused import removed

### Tests (9 files, 133 tests passing)
- All static `ModerationLabelService.divineModerationPubkeyHex` refs updated to instance access
- `report_content_dialog_test.dart`: added mock + provider override for `moderationLabelServiceProvider`
- `safety_settings_screen_test.dart`: added stub for the new getter

## Test plan
- [x] `flutter analyze` — 0 issues
- [x] `moderation_label_service_test.dart` — 20 tests pass
- [x] `nsfw_content_filter_test.dart` — 15 tests pass
- [x] `video_event_service_content_filter_test.dart` — 3 tests pass
- [x] `safety_settings_screen_test.dart` — 9 tests pass
- [x] `report_content_dialog_test.dart` — 29 tests pass
- [x] `dm_repository_test.dart` — 66 tests pass
- [ ] Manual: verify moderation labels appear for videos on staging
- [ ] Manual: verify report DM reaches moderation account

### CODE REVIEW

File: mobile/lib/screens/safety_settings_screen.dart [hunk 1]
```diff
@@ -190,11 +189,11 @@ class _SafetySettingsScreenState extends ConsumerState<SafetySettingsScreen> {
         final labelService = ref.read(moderationLabelServiceProvider);
         if (value) {
           await labelService.addLabeler(
-            ModerationLabelService.divineModerationPubkeyHex,
+            labelService.divineModerationPubkeyHex,
```
Comment (omartinma) [inline mobile/lib/screens/safety_settings_screen.dart]: I believe we can simplify this as divineModerationPubkeyHex is already inside the class

Comment (omartinma) [reply mobile/lib/screens/safety_settings_screen.dart]: This is applicable to other usages on labelService inside this screen

File: mobile/lib/services/moderation_label_service.dart
Comment (omartinma) [inline mobile/lib/services/moderation_label_service.dart:1]: Wondering if this class might benefit from a refactor using a more robust cache system

File: mobile/test/repositories/dm_repository_test.dart [hunk 2]
```diff
@@ -2174,7 +2174,8 @@ void main() {
 
     group('moderation DM scenarios', () {
       /// The moderation pubkey from [ModerationLabelService].
```
Comment (hm21) [inline mobile/test/repositories/dm_repository_test.dart]: Nit
```suggestion
      /// The fallback moderation pubkey from [ModerationLabelService].
```

File: mobile/lib/services/moderation_label_service.dart
Comment (realmeylisdev) [reply mobile/lib/services/moderation_label_service.dart:1]: @omartinma Good call. The main improvement here is injecting `SharedPreferences` via constructor instead of calling `.getInstance()` directly in 5 places — aligns with the project's constructor injection standard and the centralized `sharedPreferencesProvider`.

For the in-memory label maps: persisting them would risk showing stale labels (e.g. a removed NSFW flag still cached), since relay Kind 1985 queries are the source of truth and are fast. So those stay session-scoped.

Created #2348 to track the constructor injection refactor as a follow-up.

Comment (omartinma) [reply mobile/lib/services/moderation_label_service.dart:1]: That was not exactly my idea. We have some repositories that implement more robust cache system with Drift, so my concern was whether was worth to switch to that approach on this service

Comment (realmeylisdev) [reply mobile/lib/services/moderation_label_service.dart:1]: Good question. I looked into this and I think SharedPreferences is the right fit here — the service only persists 4 flat key-value pairs (labeler pubkey list, a bool, the resolved pubkey, and a timestamp), all read once on init and written infrequently. No querying, relationships, reactive streams, or batch operations.

The Drift-backed DAOs in this repo earn their weight because they manage many records with complex access patterns (`Nip05VerificationsDao` has status-based adaptive TTL across many identities, `NostrEventsDao` filters thousands of events by kind, etc.). Here we're caching one pubkey with a fixed 24h TTL — the check is 4 lines.

The in-memory label maps are intentionally session-scoped since relay Kind 1985 queries are the source of truth; persisting them would risk showing stale labels (e.g. a removed NSFW flag still cached).

I'll still tackle the constructor injection for SharedPreferences in #2348 — that's a real improvement for testability — but migrating the storage layer to Drift would be over-engineering for this data shape.
