### PR TITLE
fix(auth): clear per-user data on signOut to prevent cross-account data leaks (#2999)

### LINKED ISSUE #2999: fix: Per-user data leaks across account switches on shared devices
## Summary

Several per-user DAOs are never cleared on signOut, so when user B signs in on the same device after user A signed out, B can see A's drafts, clips, pending uploads, personal reactions, personal reposts, and pending actions.

## Environment

- Mobile: divine-mobile, all platforms
- Affects: any device shared between accounts (signOut → signIn as different user)

## Steps to Reproduce

1. Sign in as user A
2. Create a draft, clip, or like a video (generates personal_reactions row)
3. Sign out
4. Sign in as user B
5. Check drafts/clips/library — user A's data is visible from user B's session

## Actual Result

User A's per-user data (drafts, clips, pending uploads, personal reactions, personal reposts, pending actions) is accessible from user B's session.

## Expected Result

On signOut, all per-user data should be cleared regardless of which user signs in next. Daniel's rule: "you could be using another person's phone" — treat signOut as a hard logout for all per-user data.

## Regression?

Unknown — these DAOs may never have been cleared on signOut.

## Evidence

Identified during device debugging of auth-flow bugs (PR #2997 investigation). Cache audit performed by auth-bugs-confirm ouija session.

### Per-user DAOs that need clearing on signOut (currently leaked)

| DAO | Has clearAllForUser helper? | Status |
|-----|---------------------------|--------|
| DraftsDao | No (needs adding) | Leaked |
| ClipsDao | No (needs adding) | Leaked |
| PendingUploadsDao | No (needs adding) | Leaked |
| PersonalReactionsDao | Yes (deleteAllForUser) | Leaked |
| PersonalRepostsDao | Yes (deleteAllForUser) | Leaked |
| PendingActionsDao | Yes (clearAll(userPubkey)) | Leaked |

### Per-user DAOs already cleared on signOut (correct)

| DAO | Status |
|-----|--------|
| DirectMessagesDao | Cleared |
| ConversationsDao | Cleared |
| NotificationsDao | Cleared |

### Shared-across-users DAOs (MUST NOT clear)

UserProfilesDao, NostrEventsDao, ProfileStatsDao, VideoMetricsDao, Nip05VerificationsDao, HashtagStatsDao — these store data for all users, not scoped to the current user. Clearing them would wipe cached profiles, video feeds, and stats for everyone.

## Implementation notes

- Add `clearAllForUser` helpers to DraftsDao, ClipsDao, PendingUploadsDao where they don't exist
- Wire all per-user DAO clears into `UserDataCleanupService.onDatabaseCleanup`
- Clear on ANY signOut regardless of next user (not just identity-change signOut)
- Write per-DAO unit tests for each clear path

### PR DESCRIPTION
**Pull request by dcadenas**
Closes #2999

## Summary
- Clear account-local DAO rows only for destructive sign-out / identity removal paths
- Preserve per-user drafts, clips, pending uploads, reactions, reposts, and pending actions during non-destructive account switches
- Claim legacy NULL-owner draft and clip rows for the active user during session setup so they stop leaking across accounts
- Restore DM sync cursor cleanup alongside DM table cleanup
- Add DAO and auth-service coverage for scoped deletion, legacy claiming, and cleanup flag behavior

### Non-destructive sign-out / account switch

When `signOut(deleteKeys: false)` runs, cleanup is called with `deleteUserData: false`. Shared identity/session cleanup still happens, but account-local DAO rows are preserved so switching away from account A does not delete A's drafts/uploads before a later switch back.

### Destructive sign-out / key deletion

When `signOut(deleteKeys: true)` or destructive identity deletion runs, cleanup is called with `deleteUserData: true` and the outgoing user pubkey. Per-user DAO rows are deleted only for that pubkey. Other users' rows and shared data are preserved.

### Legacy NULL-owner rows

Older rows created before multi-account ownership are claimed during session setup via `claimLegacyRows(pubkey)` for drafts and clips. This prevents NULL-owner rows from continuing to appear for every account through the `_ownedOrLegacy` read filters.

### DM sync state

`DmSyncState.clearAll()` is included in the database cleanup callback alongside direct message table cleanup so stale DM sync cursors cannot survive after the local DM rows are cleared.

## Verification
- CI is green across analyze, format, generated files, all 8 test shards, web preview, semantic PR, CLA, and mergeability
- DAO tests cover `deleteAllForUser()` and `claimLegacyRows()` behavior
- Auth service tests assert destructive vs non-destructive cleanup flags
- User data cleanup tests assert callback forwarding for `userPubkey` and `deleteUserData`

## Notes
- Shared data such as profiles, video feeds, and stats is not deleted
- Cleanup operations are isolated through `safeDelete()` so one failed DAO cleanup does not prevent the rest from running

### CODE REVIEW

**Review by rabble — CHANGES_REQUESTED** [review]
Request changes.

The intent here is good: scoping cleanup by pubkey is the right direction, and the DAO-level `deleteAllForUser(...)` methods are straightforward and well-tested. But I don’t think this is safe to merge in its current form, because the trigger conditions are wrong and the legacy-data leak is only partially addressed.

The blocking issue is that this cleanup now runs on plain `signOut()`, not just destructive account deletion. In the current app flow, plain `signOut()` is the normal account-switch/add-account path, not a “delete this account’s local state” path. `SettingsAccountCubit.switchToAccount()` and `addNewAccount()` both call `signOut()` with defaults, and `AuthService.signOut()` now always calls `clearUserSpecificData(reason: 'explicit_logout', userPubkey: ...)`, which flows into the new provider callback that deletes drafts, clips, pending uploads, reactions, reposts, and pending actions for that pubkey. That means switching away from account A now deletes A’s local draft/upload state, even though the surrounding `signOut(deleteKeys: false)` behavior is explicitly non-destructive and intended for later restoration. These stores are already read/write scoped by `ownerPubkey`, so deleting them on account switch is a product behavior change, not just a cleanup improvement. I think this needs to be gated behind a destructive path such as `deleteKeys == true` or a separate explicit “delete local user data” flag, and it should have a test that proves switch-away/switch-back preserves account-local drafts/uploads.

The second blocking issue is that the fix is incomplete for legacy rows with `NULL` ownership. The new deleters intentionally preserve `NULL`-owner rows in `DraftsDao` and `ClipsDao`, but the read side still exposes those rows to every authenticated user via `_ownedOrLegacy(...)`. So this PR does not actually eliminate cross-account leakage for pre-multi-account drafts/clips; it just avoids deleting those rows. Preserving legacy rows is only safe if they are no longer visible across accounts. Right now they still are. I think this needs one of: a migration that claims legacy rows for the current user, a stricter read filter once a concrete user exists, or explicit cleanup of legacy rows during identity change if keeping them is not required. At minimum, the residual leak should be called out explicitly and covered by tests.

A few non-blocking points while you’re in here:
- The auth-service tests verify `reason: 'explicit_logout'` but still use `any(named: 'userPubkey')`. At least one test should assert the exact pubkey value, otherwise passing the wrong pubkey or `null` would still pass.
- The sequential cleanup in `app_providers.dart` means one thrown DAO call skips the rest. The outer catch in `clearUserSpecificData()` logs the failure, but it also turns this into partial cleanup. If best-effort cleanup is the goal, each step should probably be isolated.
- The parameter naming is inconsistent across DAOs (`ownerPubkey`, `userPubkey`, `nostrPubkey`). Not blocking, but worth normalizing before this pattern spreads.

So my suggestion is:
1. Restrict per-user DAO deletion to destructive sign-out/account deletion only, or introduce a dedicated explicit flag for that behavior.
2. Decide what the intended behavior is for legacy `NULL`-owner rows and fix both the delete path and the read path consistently.
3. Add end-to-end tests for the real trigger conditions, especially account switch and identity change.

As written, the implementation is clean, but the cleanup is happening on the wrong trigger and the legacy leak remains unresolved.

**Review by realmeylisdev — COMMENTED** [review]
## Review

Clean, well-scoped fix for #2999. The approach is solid — adding `deleteAllForUser` to the three DAOs that were missing it, threading the pubkey through the cleanup callback, and wiring everything at the provider layer. Legacy NULL-owner rows being preserved is the right call.

### Looks good

- DAO methods are simple WHERE-clause deletes scoped by pubkey — correct and easy to reason about
- `if (userPubkey != null)` guard fails safe (skip cleanup) rather than dangerous (nuke everything)
- Test coverage on the new DAO methods is thorough (delete for user, preserve other users, preserve legacy, empty table)

### Suggestions

**1. Link to #2999**
The bot flagged this PR isn't linked to a tracking issue yet. Looks like it should be linked to #2999.

**2. Consider asserting the actual pubkey value in signOut cleanup test**
The signOut cleanup test uses `any(named: 'userPubkey')` in the `verify` call — this confirms the method was called but would pass even if the wrong pubkey (or null) were passed. A stricter assertion like `userPubkey: testPubkeyHex` would catch that.

### Note on #2834

This PR was cross-referenced to #2834 (DMs missing after TestFlight update), but it addresses the separate #2999 data-leak issue. The DMs-missing fixes are in the already-merged #2887, #2921, and #2836.

**Comment by dcadenas** [comment]
@rabble Thanks for the thorough review. The new commit (`587c0bb`) addresses all three blocking issues:

1. **Cleanup gated behind destructive sign-out**: `clearUserSpecificData` now receives a `deleteUserData` parameter wired to `deleteKeys`. Non-destructive sign-out (account switch) preserves per-user DAO rows — drafts, clips, and uploads survive switch-away/switch-back.

2. **Legacy NULL-owner rows claimed on session setup**: New `claimLegacyRows()` in DraftsDao and ClipsDao runs `UPDATE SET ownerPubkey = ? WHERE ownerPubkey IS NULL` during identity setup. Once claimed, legacy rows are scoped to the claiming user and invisible to other accounts.

3. **Non-blocking items**: Each DAO deletion is now isolated in a `safeDelete()` wrapper (no cascading failures). Tests assert the exact pubkey value rather than `any(named: 'userPubkey')`. Parameter naming is normalized at the service→DAO boundary (`userPubkey` in service, `ownerPubkey` in DAOs).

---

@realmeylisdev Thanks for the review. The pubkey assertion point (shared with rabble's feedback) is addressed — tests now verify the exact pubkey value. #2999 is linked.

File: mobile/lib/providers/app_providers.dart [hunk 1]
```diff
@@ -1303,19 +1303,72 @@ UserDataCleanupService userDataCleanupService(Ref ref) {
...
+      ({String? userPubkey, bool deleteUserData = false}) async {
+        try {
+          await ref.read(dmRepositoryProvider).stopListening();
+        } catch (_) {
+          // DmRepository may not exist yet (e.g., first launch).
+        }
+        await db.directMessagesDao.clearAll();
+        await db.conversationsDao.clearAll();
+        await db.notificationsDao.clearAll();
+        await NotificationServiceEnhanced.instance.clearAllData();
```
Comment (realmeylisdev) [inline mobile/lib/providers/app_providers.dart:1321]: `DmSyncState(prefs).clearAll()` was removed from this callback (it used to be right after `NotificationServiceEnhanced.instance.clearAllData()`), and the `dm.newestSyncedAt.` / `dm.oldestSyncedAt.` prefixes were removed from `identityChangePrefixes`.

But `directMessagesDao.clearAll()` on L1318 still wipes **all** DM messages unconditionally. This creates a stale-cursor + empty-DB mismatch:

1. User A syncs DMs → cursor at timestamp T, DB has messages up to T
2. Account switch → `directMessagesDao.clearAll()` wipes all DMs, but cursor survives
3. Switch back to A → `DmRepository.startListening` sees `newestSyncedAt != null`, sets `since: T - 2d`
4. Messages older than T-2d are never re-fetched → missing DMs

**Fix**: restore the `DmSyncState` clearing alongside the DM table clearing:

```dart
await NotificationServiceEnhanced.instance.clearAllData();
// Clear DM sync cursors so the next login triggers a full re-fetch
// from relays instead of using stale `since:` boundaries.
await DmSyncState(prefs).clearAll();
```

One-line restore. The sync cursors need to stay consistent with the DM tables until those tables are also scoped per-user.

**Review by realmeylisdev — COMMENTED** [review]
The latest commit (587c0bb) addresses all of rabble's blocking concerns — cleanup gated behind destructive sign-out, legacy rows claimed, isolated deletions, exact pubkey assertions. Nice work.

One regression to fix before merge (inline comment below).

Also: the PR description body needs `Closes #2999` to clear the `needs-issue` label — having `#2999` only in the title doesn't satisfy the bot.

File: mobile/lib/providers/app_providers.dart (hunk 1 above)
Comment (dcadenas) [reply mobile/lib/providers/app_providers.dart:1321]: Fixed in d2b2c37. Restored `DmSyncState(prefs).clearAll()` right after `NotificationServiceEnhanced.instance.clearAllData()` — same position as before the refactor. Also restored the `dm.newestSyncedAt.` and `dm.oldestSyncedAt.` prefixes in `identityChangePrefixes` for belt-and-suspenders coverage on identity change. Added test assertions verifying the DM sync cursor prefixes are cleared during identity change.

**Review by realmeylisdev — APPROVED** [review]
All blocking concerns resolved across the three fix commits:

- **Cleanup gating** (`587c0bb`): per-user DAO deletion correctly gated behind `deleteUserData && userPubkey != null` — account switches preserve scoped rows.
- **Legacy row claiming** (`587c0bb`): `claimLegacyRows()` during session setup attributes NULL-owner drafts/clips to the current user, closing the cross-account leak via `_ownedOrLegacy`.
- **DmSyncState regression** (`d2b2c37`): `DmSyncState(prefs).clearAll()` restored alongside DM table clearing, and `dm.newestSyncedAt.`/`dm.oldestSyncedAt.` prefixes restored in `identityChangePrefixes`.

`safeDelete()` isolation, exact pubkey assertions in tests, and DAO-level coverage for `deleteAllForUser`/`claimLegacyRows` all look solid.

**Comment by NotThatKindOfDrLiz** [comment]
@rabble could you take another look and clear your previous request-changes review if this matches what you were asking for?

The latest commits address the blocking items:
- destructive per-user DAO cleanup is now gated behind `deleteUserData` / `deleteKeys`
- non-destructive account switches preserve account-local rows
- legacy NULL-owner drafts/clips are claimed on session setup via `claimLegacyRows`
- DAO deletions are isolated through `safeDelete`
- `DmSyncState.clearAll()` was restored after the cleanup refactor regression
- tests now assert exact pubkey/deleteUserData behavior

CI is green and @realmeylisdev has approved the latest version. I updated the PR body to describe the final behavior.

**Review by rabble — APPROVED** [review]
LGTM. All three blocking concerns from my prior review are addressed:

1. **Cleanup gating** — `onDatabaseCleanup` now takes `{userPubkey, deleteUserData}` and per-user DAO deletion is behind `if (deleteUserData && userPubkey != null)`. `signOut(deleteKeys: false)` (account switch) preserves scoped rows; `signOut(deleteKeys: true)` and the identity-change path in `_setupUserSession` pass `deleteUserData: true` with the outgoing pubkey.

2. **Legacy NULL-owner leak** — `claimLegacyRows()` in DraftsDao/ClipsDao (`UPDATE … WHERE ownerPubkey IS NULL`) is wired via `onClaimLegacyRows` and called during session setup, so legacy rows are attributed to the current user and stop leaking through `_ownedOrLegacy` to other accounts.

3. **Non-blocking items** — each DAO call is isolated via `safeDelete()` so one failure doesn't skip the rest; tests assert exact pubkey values; naming is normalized (`userPubkey` at service boundary, `ownerPubkey` at DAO).

DmSyncState regression also restored. CI is green across analyze/format/codegen and all 8 test shards. Thanks for the thorough follow-up.
