### PR TITLE
fix(feed): harden pagination across feeds

### LINKED ISSUE #2611: fix(feed): harden pagination across feeds
Auto-created from PR #2610.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2610
**Branch:** `fix/feed-pagination`

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2611

## Summary
- Harden shared feed pagination with a reusable `ScrollPaginationController` and adopt it across profile, inbox, notification, discover list, classic vines, search, and composable grid feeds
- Wire the For You grid into load-more behavior and fix ProfileFeed REST has-more detection so filtered 50-item pages still paginate correctly
- Switch ProfileFeed from cursor-based to offset-based REST pagination
- Add regression coverage for the shared pagination controller, profile REST pagination contract, profile grid scrolling, and inbox scroll pagination

## Test Plan
- [x] `cd mobile && flutter test --no-pub test/widgets/scroll_pagination_controller_test.dart test/providers/profile_feed_pagination_contract_test.dart test/screens/profile_grid_tap_navigation_test.dart test/screens/inbox/inbox_view_test.dart`
- [x] `cd mobile && flutter analyze --no-pub lib/widgets/for_you_tab.dart lib/widgets/profile/profile_liked_grid.dart lib/widgets/profile/profile_reposts_grid.dart lib/widgets/profile/profile_collabs_grid.dart lib/widgets/profile/profile_comments_grid.dart lib/screens/inbox/inbox_view.dart lib/widgets/composable_video_grid.dart lib/widgets/profile/profile_videos_grid.dart lib/screens/notifications_screen.dart lib/widgets/classic_vines_tab.dart lib/widgets/user_search_view.dart lib/screens/discover_lists_screen.dart lib/providers/profile_feed_provider.dart`
- [x] Pre-push hook targeted changed-file test suite

### CODE REVIEW

File: mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart [hunk 1]
```diff
@@ -106,7 +106,10 @@ class FunnelcakeApiClient {
   ///
   /// [pubkey] is the author's public key (hex format).
   /// [limit] is the maximum number of videos to return (defaults to 50).
-  /// [before] is an optional Unix timestamp cursor for pagination.
+  /// [offset] is an optional pagination offset.
+  ///
+  /// [before] is retained for legacy compatibility, but the live
```
Comment (ryzizub) [inline mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart]: Seems that before is not used anymore

File: mobile/lib/widgets/scroll_pagination_controller.dart [hunk 2]
```diff
@@ -0,0 +1,46 @@
+import 'dart:async';
+
+import 'package:flutter/widgets.dart';
+
+typedef ScrollPaginationCallback = FutureOr<void> Function();
+typedef CanLoadMoreCallback = bool Function();
+
+/// Reusable near-bottom pagination trigger for scroll-driven feeds and lists.
+class ScrollPaginationController {
```
Comment (ryzizub) [inline mobile/lib/widgets/scroll_pagination_controller.dart]: this is not exactly a widget but more like a utils, i would consider it moving there.

Also The current API requires creating a separate object and manually managing its lifecycle alongside the `ScrollController`. A mixin on `State` (like `GridPrefetchMixin` in the codebase) would reduce boilerplate across all 11 adoption sites.

File: mobile/lib/providers/profile_feed_provider.dart [hunk 3]
```diff
@@ -265,10 +271,17 @@ class ProfileFeed extends _$ProfileFeed {
     refresh();
   }
 
-  /// Get oldest timestamp from videos for cursor pagination
-  int? _getOldestTimestamp(List<VideoEvent> videos) {
-    if (videos.isEmpty) return null;
-    return videos.map((v) => v.createdAt).reduce((a, b) => a < b ? a : b);
+  int _estimateNextRestOffset(VideoFeedState currentState) {
```
Comment (ryzizub) [inline mobile/lib/providers/profile_feed_provider.dart]: this seems to me not trivial, i would consider extracting it as static and @visibleForTesting and write unit test to double verify its functionality

File: mobile/lib/widgets/scroll_pagination_controller.dart [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+  ScrollPaginationController({
+    required ScrollController scrollController,
+    required CanLoadMoreCallback canLoadMore,
+    required ScrollPaginationCallback onLoadMore,
+    this.threshold = 200,
```
Comment (ryzizub) [inline mobile/lib/widgets/scroll_pagination_controller.dart]: This parameter is never used

File: mobile/lib/screens/inbox/inbox_view.dart [hunk 5]
```diff
@@ -255,9 +284,13 @@ class _ConversationList extends ConsumerWidget {
     final hasMore = context.select<ConversationListBloc, bool>(
       (bloc) => bloc.state.hasMore,
     );
+    final isLoadingMore = context.select<ConversationListBloc, bool>(
+      (bloc) => bloc.state.isLoadingMore,
+    );
 
     final hasRequests = requestConversations.isNotEmpty;
     final bannerOffset = hasRequests ? 1 : 0;
+    _canLoadMore = hasMore && !isLoadingMore;
```
Comment (ryzizub) [inline mobile/lib/screens/inbox/inbox_view.dart]: This is not good practice, to use Bloc state and assign it to mutable field

pass the BLoC state check directly into the `canLoadMore` closure via `context.read<ConversationListBloc>()` inside the callback (similar to how profile grids do it).

File: docs/superpowers/plans/2026-03-30-feed-pagination-hardening.md
Comment (ryzizub) [inline docs/superpowers/plans/2026-03-30-feed-pagination-hardening.md:1]: Should we commit those plans even if already implemented?
