### PR TITLE
fix(block): persist blocks and filter blocked content from feeds

### LINKED ISSUE #1724: fix: Block button not working I guess
### Summary

----------------------------------------------

!*** Sjaced Vrivera was not signed in when this comment was submitted. Learn more ***!

Sjaced Vrivera, 23 Feb 2026, 04:36

I've blocked the same user numerous times. Just not interested in the content, my feed is filled with like 20 videos of the same user.

I block the user, states blocked on profile yet I can see the pvideos on my feed and every time I get back on the app the profile no longer appears as blocked 😐

I have a s25 ultra running one ui 8.5 ( beta tester )

### Environment

**Platform:** android_app
**Build Number:** 
**OS Version:** 

### Steps to Reproduce

Their's no visual queue like a perceivable glitch or foreclosure, its just not blocking

### Actual Result

----------------------------------------------

!*** Sjaced Vrivera was not signed in when this comment was submitted. Learn more ***!

Sjaced Vrivera, 23 Feb 2026, 04:36

I've blocked the same user numerous times. Just not interested in the content, my feed is filled with like 20 videos of the same user.

I block the user, states blocked on profile yet I can see the pvideos on my feed and every time I get back on the app the profile no longer appears as blocked 😐

I have a s25 ultra running one ui 8.5 ( beta tester )

### Expected Result

That I only need to block the user profile once and not see that user on the feed I guess

(Generated from Zendesk Ticket: rabblelabs.zendesk.com/agent/tickets/782)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary
- Fix block not persisting across app restarts by awaiting SharedPreferences writes
- Filter blocked users' videos from the home feed via new `VideoFeedBlocklistChanged` event
- Filter blocked users' conversations from the DM inbox via `ContentBlocklistService` injection into `ConversationListBloc`
- Remove dead `BlocklistVersionIncrementer` callback from `OtherProfileBloc`

## Test plan
- [x] Existing tests updated and passing (115 tests across 3 test files)
- [ ] Manual: Block a user from profile → videos disappear from feed immediately
- [ ] Manual: Block a user → force-kill app → reopen → block persists
- [ ] Manual: Block a user → their DM conversation disappears from inbox
- [ ] Manual: Unblock a user → videos and conversations reappear

Closes #1724

### CODE REVIEW

File: mobile/lib/blocs/dm/conversation_list/conversation_list_bloc.dart [hunk 1]
```diff
@@ -161,4 +169,27 @@ class ConversationListBloc
...
+
+    final userPubkey = _dmRepository.userPubkey;
+    return conversations.where((conv) {
+      final otherPubkey = conv.participantPubkeys.firstWhere(
+        (pk) => pk != userPubkey,
+        orElse: () => '',
+      );
+      return otherPubkey.isEmpty || !service.shouldFilterFromFeeds(otherPubkey);
+    }).toList();
+  }
```
Comment (hm21) [inline mobile/lib/blocs/dm/conversation_list/conversation_list_bloc.dart]: I think it would be better to have that method in the `ContentBlocklistService` instead inside of the bloc, to keep the bloc small. We might also need it in other places later on.

File: mobile/lib/blocs/video_feed/video_feed_bloc.dart [hunk 2]
```diff
@@ -375,6 +376,37 @@ class VideoFeedBloc extends Bloc<VideoFeedEvent, VideoFeedState> {
...
+    if (state.status == VideoFeedStatus.loading) return;
+    emit(
+      state.copyWith(
+        status: VideoFeedStatus.loading,
+        videos: [],
+        hasMore: true,
+        clearError: true,
+      ),
+    );
+    await _loadVideos(state.mode, emit, skipCache: true);
```
Comment (hm21) [inline mobile/lib/blocs/video_feed/video_feed_bloc.dart]: Shouldn’t we just filter out the videos from blocked users instead of reloading everything, or wouldn’t that work?
