### PR TITLE
fix(notifications): land on the post when a mention has no referenced event

### LINKED ISSUE #3168: feat: Notifications in app, android, on a oneplus n30 with lineage OS, me...
### Summary

----------------------------------------------

Fortfox666, 20 Apr 2026, 03:11

Notifications in app, android, on a oneplus n30 with lineage OS, mentions send me to a profile page, but not to the mention. Would be nice to have it go to wherever account was mentioned directly.

### Environment

**Platform:** android_app
**Build Number:** 
**OS Version:** 

### Steps to Reproduce

Clicked in a " ... Mentioned you." Under general notifications, sent to profile page. After scrolling through account, saw it was a reply to one of my comments.

### Actual Result

----------------------------------------------

Fortfox666, 20 Apr 2026, 03:11

Notifications in app, android, on a oneplus n30 with lineage OS, mentions send me to a profile page, but not to the mention. Would be nice to have it go to wherever account was mentioned directly.

### Expected Result

Gone directly to the post and showed comments.

(Generated from Zendesk Ticket: rabblelabs.zendesk.com/agent/tickets/1059)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Description

PR #3431 routed mention taps to the post when the relay populated `referenced_event_id`, but kept the actor's-profile fallback for the null case. Mentions where the relay returns `referenced_event_id == null` (e.g. a mention inside a NIP-22 comment) still send the user to the mentioner's profile.

For mention notifications only, the converter and BLoC repository now fall back to `source_event_id` when `referenced_event_id` is null. `NotificationTargetResolver` already walks the source event's NIP-22 `E` and NIP-10 `e` tags back to the root video, so passing the comment/reply event resolves to the correct post. Mentions also auto-open the comments overlay so the user lands near where they were mentioned.

The fix is applied in both the legacy path (`notification_model_converter`, used by the Inbox today via `NotificationsScreen`) and the BLoC path (`notification_repository`, used by the new `NotificationsView`), matching the mid-flight migration. Like-grouping is untouched and still keys on `referencedEventId` only.

**Related Issue:** Closes #3168

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

## Test plan

- [x] \`flutter analyze lib test integration_test\` clean from \`mobile/\`
- [x] \`flutter analyze\` clean inside \`mobile/packages/notification_repository\`
- [x] \`flutter test test/services/notification_model_converter_test.dart\` — 14/14 (4 new mention-fallback cases)
- [x] \`flutter test\` inside \`notification_repository\` — 30/30 (3 new mention-fallback cases)
- [x] \`flutter test test/models/notification_model_test.dart test/screens/notifications_screen_test.dart\` — 22/22, no regressions
- [x] \`flutter test test/notifications/\` — 48/48, no regressions
- [ ] Manual on Android: tap a mention notification with no \`referenced_event_id\` from the relay → lands on the post with comments open, not the mentioner's profile

## Follow-ups (not in this PR)

- Backend: have the relay populate \`referenced_event_id\` for every mention whose source event has a discoverable root video, so the frontend fallback becomes purely defensive.
- Push notification handler in \`mobile/lib/main.dart\` reads \`referencedEventId\` from FCM data but only logs it; navigation is not wired. Separate bug, separate PR.

### CODE REVIEW

File: mobile/lib/screens/notifications_screen.dart [hunk 1]
```diff
@@ -693,7 +693,9 @@ class _NotificationTabContentState
       return;
     }
 
-    final shouldAutoOpenComments = notificationType == NotificationType.comment;
+    final shouldAutoOpenComments =
+        notificationType == NotificationType.comment ||
+        notificationType == NotificationType.mention;
```
Comment (hm21) [inline mobile/lib/screens/notifications_screen.dart:698]: In `notifications_view.dart` i see `notificationKind == NotificationKind.reply` is also included, but not here. Is that intentional? 

If not, it might be cleaner to extend the `NotificationType` enum with a getter like `shouldAutoOpenComments`. That way, we could simply call `notificationType.shouldAutoOpenComments` and make it easier to extend in the future.

Comment (realmeylisdev) [reply mobile/lib/screens/notifications_screen.dart:698]: Intentional — NotificationType (legacy) doesn't have a reply value, only NotificationKind does. The two shouldAutoOpenComments checks each list every member of their own enum that should auto-open comments. The getter idea is nice for NotificationKind since that's the long-lived enum; happy to add it there in this PR or a follow-up.

**Review by hm21 — APPROVED** [review]
