### PR TITLE
fix(block): restore block list from relay on app reinstall (#2192)

### LINKED ISSUE #2192: 582 unblocked my blocked user
### Summary

582 unblocked the only user I had blocked (for testing purposes) he was just unblocked, not by me, and I was able to follow him again. 
Before 582 update user could still see my post and interact with my account. I would get a notification of their interaction. Yet I could not visit their profile. 

### Environment

Build 582
iOS 26.3 
iPhone 12 Pro

### Steps to Reproduce

1. Block user 
2. Update to 582 
3. Go to the profile of the user you blocked and check if they are still blocked or if you follow them again 

### Actual Result

I was able to see the user's profile. When I had blocked them I was no longer able to see their profile. 
I was able to follow the user again. 

### Expected Result

the user would remain blocked and I would not see his profile. 

### Regression?

Yes

### Evidence

In builds from thr 570s (when I blocked him) when a user is blocked is simply wont show YOU their profile. It seems they can see YOUR profile. But there was no other sign. 

Now there is a more clear block AND unblock process. 

[openvine_full_logs_2026-03-12T17-08-16.331736.txt](https://github.com/user-attachments/files/25960173/openvine_full_logs_2026-03-12T17-08-16.331736.txt)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary
- Restore user's block list from Nostr relays (kind 30000, d=block) on startup so blocks survive app reinstalls
- Adds a second filter to `syncBlockListsInBackground` to also receive our own block list event; when it arrives, blocked pubkeys are merged into the local blocklist and persisted to SharedPreferences
- Publishes block list to a configurable fallback relay (`wss://nos.lol`) in addition to connected relays, since FunnelCake now supports kind 30000 (divinevideo/divine-funnelcake#199 merged)
- Replaces fragile `Future.microtask` startup sync in `main.dart` with a reactive `blocklistSyncBridgeProvider` that responds to auth state changes
- Makes `contentBlocklistServiceProvider` `keepAlive` to prevent subscription loss on widget rebuild
- Resets sync guards when `NostrClient` changes (account switch / reconnect)

Continues the work from #2625 (closed pending funnelcake dependency, now resolved).

Closes #2192

## Test plan
- [x] 47 unit tests pass (including 10 new relay restoration tests)
- [x] `flutter analyze` clean on all changed files
- [ ] Manual: block user → uninstall → reinstall → verify blocks restored
- [ ] Manual: block user → switch account → switch back → verify blocks still present

### CODE REVIEW

File: mobile/lib/models/environment_config.dart [hunk 1]
```diff
@@ -95,6 +95,18 @@ class EnvironmentConfig {
...
+  /// Fallback relays for block list persistence (kind 30000, d=block).
+  ///
+  /// Funnelcake does not persist kind 30000 events, so we publish to and
+  /// subscribe from these relays as well. In LOCAL mode, the local relay
+  /// is used instead of external public relays.
+  List<String> get blockListFallbackRelays {
+    if (environment == AppEnvironment.local) {
+      return ['ws://$localHost:$localRelayPort'];
+    }
+    return const ['wss://nos.lol'];
```
Comment (hm21) [inline mobile/lib/models/environment_config.dart]: Do you think we should extract the value `'wss://nos.lol'` into a global const so we can reuse it everywhere, like in the content_blocklist_service?

File: mobile/lib/providers/app_providers.dart [hunk 2]
```diff
@@ -696,6 +703,68 @@ class BlocklistVersion extends _$BlocklistVersion {
...
+    try {
+      await blocklistService.syncMuteListsInBackground(
+        nostrService,
+        pubkey,
+      );
+      await blocklistService.syncBlockListsInBackground(
+        nostrService,
+        authService,
+        pubkey,
+      );
```
Comment (hm21) [inline mobile/lib/providers/app_providers.dart]: Could we run it at the same time using Future.wait, or do we need to wait for `syncMuteListsInBackground` to finish first?

File: mobile/lib/services/content_blocklist_service.dart [hunk 3]
```diff
@@ -30,8 +31,10 @@ class ContentBlocklistService {
   ContentBlocklistService({
     SharedPreferences? prefs,
     void Function()? onChanged,
+    List<String> blockListFallbackRelays = const ['wss://nos.lol'],
```
Comment (hm21) [inline mobile/lib/services/content_blocklist_service.dart]: Here is the value I mentioned above regarding the global const.

File: mobile/lib/services/content_blocklist_service.dart [hunk 4]
```diff
@@ -590,6 +687,49 @@ class ContentBlocklistService {
...
+  /// Extracts blocked pubkeys from 'p' tags and merges them into the
+  /// runtime blocklist. This ensures blocks survive app reinstalls where
+  /// SharedPreferences data is lost but the relay still holds our event.
+  void _handleOwnBlockListEvent(Event event) {
+    final relayPubkeys = <String>{};
+    for (final tag in event.tags) {
+      if (tag.isNotEmpty &&
+          tag[0] == 'p' &&
+          tag.length >= 2 &&
+          tag[1] != _ourPubkey) {
```
Comment (hm21) [inline mobile/lib/services/content_blocklist_service.dart:645]: I wonder if in the future we should have a method in a package that makes it easier to parse things like this, where we can just pass in the tag and directly get the value.

File: mobile/lib/models/environment_config.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/models/environment_config.dart]: Good call — extracted into `const defaultBlockListFallbackRelay = 'wss://nos.lol'` in `environment_config.dart` and referenced from both places now.

File: mobile/lib/providers/app_providers.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/providers/app_providers.dart]: They're independent — separate guards, separate filters, separate subscriptions. Both write `_ourPubkey` and `_nostrClient` but to the same values, so order doesn't matter. Switched to `Future.wait`.

File: mobile/lib/services/content_blocklist_service.dart (hunk 3 above)
Comment (realmeylisdev) [reply mobile/lib/services/content_blocklist_service.dart]: Done — now uses `defaultBlockListFallbackRelay` from `environment_config.dart`.

File: mobile/lib/services/content_blocklist_service.dart (hunk 4 above)
Comment (realmeylisdev) [reply mobile/lib/services/content_blocklist_service.dart:645]: Agreed, that'd be useful — the tag parsing is repetitive across block list, mute list, and profile handlers. I'll track that as a follow-up since it'd touch multiple files and is out of scope for this fix.

File: mobile/test/models/environment_config_test.dart [hunk 5]
```diff
@@ -75,6 +75,35 @@ void main() {
...
+      test('local returns local relay', () {
+        const config = EnvironmentConfig(environment: AppEnvironment.local);
+        expect(config.blockListFallbackRelays, ['ws://10.0.2.2:47777']);
+      });
+
+      test('production returns nos.lol', () {
+        const config = EnvironmentConfig(
+          environment: AppEnvironment.production,
+        );
+        expect(config.blockListFallbackRelays, ['wss://nos.lol']);
```
Comment (hm21) [inline mobile/test/models/environment_config_test.dart]: Could we reuse the global const here now

Comment (realmeylisdev) [reply mobile/test/models/environment_config_test.dart]: Done — updated both test assertions to use `defaultBlockListFallbackRelay`. Also regenerated `app_providers.g.dart` which was causing the CI failure.

**Review by hm21 — APPROVED** [review]
