### PR TITLE
fix(countdown): adjust delay for countdown beep playback to prevent audio bleed

### LINKED ISSUE #1940: fix: Camera countdown audio is recorded in the final video (iOS only)
### Summary

When using the camera countdown feature on iOS, the countdown sound is audible in the final recorded video.

### Environment

iOS

### Steps to Reproduce

1. Open the camera on an iOS device.
2. Enable the countdown (e.g., 3 seconds).
3. Start recording.
4. Wait for the countdown to finish.
5. Stop recording and play back the video.

### Actual Result

On iOS, the countdown sound is captured by the microphone and becomes part of the exported video.

### Expected Result

The countdown sound should only play locally as UI feedback and must not be included in the recorded audio track.

### Regression?

No

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by hm21**
## Description

When using the camera countdown feature on iOS, the countdown sound is audible in the final recorded video. This PR add now a small delay to prevent that issue.

**Related Issue:** Closes #1940

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/providers/video_recorder_provider.dart [hunk 1]
```diff
@@ -610,9 +610,9 @@ class VideoRecorderNotifier extends Notifier<VideoRecorderProviderState> {
         state = state.copyWith(countdownValue: i);
 
         unawaited(_countdownSoundService!.playShortBeep());
-        // 940ms to compensate for following ~60ms long beep playback duration,
-        // keeping each tick at ~1 second total
-        await Future<void>.delayed(Duration(milliseconds: i > 0 ? 1000 : 940));
+        // 790ms to compensate for following ~60ms long beep playback duration,
+        // and the 150ms pause which ensure the audio definitely stopped.
```
Comment (omartinma) [inline mobile/lib/providers/video_recorder_provider.dart]: Should we put all these constants somehow together so that it is easier to track them?

Comment (hm21) [reply mobile/lib/providers/video_recorder_provider.dart]: Oh, yeah, that's a very good point

Fixed [fb3fd11](https://github.com/divinevideo/divine-mobile/pull/1941/commits/fb3fd11fb9ca8f7af867603da86c510e020e9a91)
