### PR TITLE
fix(video_player): improve seek handling and preroll functionality

### LINKED ISSUE #3467: fix(video_player): improve seek handling and preroll functionality
Auto-created from PR #3466.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3466
**Branch:** `fix/seekto-ios-issue`

### PR DESCRIPTION
**Pull request by hm21**
Closes #3467

## Description

Resolved an issue where, when a user had multiple clips and slowly scrolled from one clip to the next, the video preview would get stuck on iOS at that position until the user scrolled back to the first clip.

### Incidental fix

`VideoTextureOutput.attach(to:)` (iOS + macOS) now detaches the previous output via `prev.remove(old)` instead of `item.remove(old)`. The old call was a silent no-op because `old` had been added to the previous item, not the new one — flagging here so future bisects don't conflate this with the seek-stuck fix.

**Related Issue:** Closes # or Relates to #

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by rabble** [comment]
Code review (Claude on rabble's behalf):

**Verdict:** LGTM with concerns — safe to merge for launch.

**Summary.** iOS-only Swift fix in `DivineVideoPlayerInstance.swift` and `VideoTextureOutput.swift`. Adds a 600 ms post-seek force-window that polls `copyPixelBuffer` every display-link tick, registers an `AVPlayerItemOutputPullDelegate`, calls `AVPlayer.preroll(atRate:)` (KVO-deferred until `.readyToPlay`), and adds a stuck-seek recovery that retries with 100 ms tolerance. Targets exactly the reported failure mode (paused player, exact seek on `AVMutableComposition` not delivering a frame). Android + Dart untouched.

**Blockers:** none. CI green.

**Concerns (post-launch follow-ups):**
- **Thread-safety on `pendingPrerollObservation`.** `safePreroll` reads/writes the field across the seek completion handler and `loadVideo`. Between the `invalidate()` and `= nil` lines, a second `safePreroll` from a different queue could leak the observation. Most callers are main-queue today; assert main-queue or use a serial dispatch guard.
- **`forceRefreshDeadline` uses `Date()` wall clock.** Device clock jumps (NTP, TZ change) can collapse or extend the 600 ms window. `CACurrentMediaTime()` is safer.
- **`onSeekStuck` retry recursion.** If the tolerant retry also fails, the next display-link tick re-fires `onSeekStuck`. `forceWindowFailCount = 0` reset prevents same-window re-trigger; a persistently broken composition could still loop. Worth a guard counter.
- **100 ms before/after tolerance.** Long-GOP content may need a wider window; if reports persist after this ships, widen or fall back to non-exact seek.

**Tests.** None added — package has no Swift test infra; Dart line-coverage rule doesn't apply here. **Manual iOS retest required before tagging the launch build:** slow-scroll-between-clips repro from #3467, multi-clip reload-same-URL path (`DivineVideoPlayerInstance.swift:172`), stuck-seek recovery path. Test on iOS 16 + iOS 17, low-end (iPhone 11) for the 600 ms timing.

Disposal hygiene is correct (`pendingPrerollObservation?.invalidate()` added to dispose path at `:678`).

**Comment by hm21** [comment]
@rabble thanks for the review:

> Thread-safety on pendingPrerollObservation

Added `assert(Thread.isMainThread)` in `safePreroll` as a tripwire, but in a Flutter plugin this race is practically unreachable — all entry points (MethodChannel handlers, EventChannel callbacks, `Task { @MainActor }`, AVPlayer seek completions) land on the platform thread (= main on iOS), and `AVPlayer`'s API is itself main-bound, so no realistic caller could come in off-thread.

> forceRefreshDeadline uses Date() wall clock. 

Switched the deadline to `CACurrentMediaTime()` since it's the correct API for frame timing per Apple's docs, though realistically `Date()` would only have caused a problem if an NTP sync shifted the clock by >100 ms during the exact 600 ms window of an active seek — practically never.

> onSeekStuck retry recursion

Added a one-shot `isRetry` flag on `forceRefresh` so the tolerant-seek recovery can't re-fire `onSeekStuck` and loop, though realistically the only way to hit this is a corrupt source file or hardware decoder pressure, since `buildComposition` already validates tracks/sizes/durations upfront, so this is more belt-and-braces than a real-world fix.

> 100 ms before/after tolerance. 

100 ms (~3 frames @30fps) is the smallest tolerance that reliably escapes the GOP dead zone while staying below the threshold where the user perceives the seek landing on the wrong frame — wider would visibly snap away, narrower would re-land in the same dead zone.

> None added — package has no Swift test infra; Dart line-coverage rule doesn't apply here. Manual iOS retest

Yup i always test the stuff first before marking a PR ready for review.

**Review by realmeylisdev — COMMENTED** [review]
Solid fix — every concern from the prior review round looks addressed (thread-safety assert, monotonic clock, retry-recursion guard, tolerance reasoning).

One parity gap noted inline on both platforms: `handleJumpToClip` runs the same zero-tolerance boundary seek as `handleSeekTo` but didn't get the new `forceRefresh` + `safePreroll` treatment. Worth folding into this PR or tracking as a follow-up so the public `jumpToClip(int)` Dart API doesn't surface the same stuck-frame symptom by a different entry point.

File: mobile/packages/divine_video_player/ios/Classes/DivineVideoPlayerInstance.swift [hunk 1]
```diff
@@ -278,7 +305,16 @@ final class DivineVideoPlayerInstance: NSObject, FlutterStreamHandler {
...
+            guard let self else {
+                result(nil)
+                return
+            }
+            self.textureOutput?.forceRefresh(for: time)
+            self.syncAudioOverlays()
+            // Preroll primes the output pipeline at the new position;
+            // without it a paused player near a clip boundary keeps
+            // returning the pre-seek buffer until play() is pressed.
+            self.safePreroll(at: time)
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/ios/Classes/DivineVideoPlayerInstance.swift:317]: `handleJumpToClip` further down in this file (around lines 325–339) does the same `seek(to:, toleranceBefore: .zero, toleranceAfter: .zero)` to a clip boundary (`clipOffsets[index]`) on a potentially paused player — the same trigger condition as #3467 — but its completion handler still only calls `syncAudioOverlays()`. The `forceRefresh` + `safePreroll` treatment from `handleSeekTo` should be mirrored there too, otherwise `jumpToClip(int)` from Dart can reproduce the stuck-frame symptom by a different code path.

Suggested completion body, mirroring this method:

```swift
player?.seek(to: targetTime, toleranceBefore: .zero, toleranceAfter: .zero) { [weak self] _ in
    guard let self else {
        result(nil)
        return
    }
    self.textureOutput?.forceRefresh(for: targetTime)
    self.syncAudioOverlays()
    self.safePreroll(at: targetTime)
    result(nil)
}
```

File: mobile/packages/divine_video_player/macos/Classes/DivineVideoPlayerInstance.swift [hunk 2]
```diff
@@ -260,7 +287,16 @@ final class DivineVideoPlayerInstance: NSObject, FlutterStreamHandler {
...
+            guard let self else {
+                result(nil)
+                return
+            }
+            self.textureOutput?.forceRefresh(for: time)
+            self.syncAudioOverlays()
+            // Preroll primes the output pipeline at the new position;
+            // without it a paused player near a clip boundary keeps
+            // returning the pre-seek buffer until play() is pressed.
+            self.safePreroll(at: time)
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/macos/Classes/DivineVideoPlayerInstance.swift:299]: Same parity gap on macOS — `handleJumpToClip` (around lines 303–315 in this file) seeks to a clip boundary with zero tolerance and only calls `syncAudioOverlays()` in its completion. Worth mirroring the fix so iOS and macOS stay in lockstep.

File: mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift [hunk 3]
```diff
@@ -39,9 +65,9 @@ final class VideoTextureOutput: NSObject, FlutterTexture {
     /// Attaches the video output to a player item so frames can be
     /// pulled from it.
     func attach(to item: AVPlayerItem) {
-        // Remove previous output if any.
-        if let old = videoOutput {
-            item.remove(old)
+        // Remove the old output from the item it was actually added to.
+        if let old = videoOutput, let prev = attachedItem {
+            prev.remove(old)
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift:70]: Note for the PR/commit body: this `prev.remove(old)` change also corrects a separate, smaller issue — the old `item.remove(old)` referenced the new item rather than the previous one, so the call was a no-op (the output had been added to the previous item, not the new one). The new `weak attachedItem` path performs the intended detach. Worth flagging alongside the seek-stuck fix so future bisects don't conflate the two.

**Review by realmeylisdev — COMMENTED** [review]
Two follow-up notes on the latest commit — both non-blocking. Parity-gap thread above (`handleJumpToClip`) is still the only thing that affects user-visible behavior.

File: mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift [hunk 4]
```diff
@@ -38,9 +64,9 @@ final class VideoTextureOutput: NSObject, FlutterTexture {
     /// Attaches the video output to a player item so frames can be
     /// pulled from it.
     func attach(to item: AVPlayerItem) {
-        // Remove previous output if any.
-        if let old = videoOutput {
-            item.remove(old)
+        // Remove the old output from the item it was actually added to.
+        if let old = videoOutput, let prev = attachedItem {
+            prev.remove(old)
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift:69]: Same incidental correctness fix as the iOS comment — `prev.remove(old)` here correctly detaches from the previous item, where the old `item.remove(old)` was a no-op (`old` had been added to a different item). Worth flagging in the PR body.

File: mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift [hunk 5]
```diff
@@ -96,24 +175,55 @@ final class VideoTextureOutput: NSObject, FlutterTexture {
...
+
     @objc private func onDisplayLink() {
         guard let output = videoOutput,
               let player else { return }
 
         let itemTime = player.currentTime()
+
+        if CACurrentMediaTime() < forceRefreshDeadline {
+            if let pixelBuffer = output.copyPixelBuffer(
+                forItemTime: itemTime,
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift:195]: Nit, non-blocking: this `copyPixelBuffer(forItemTime: itemTime)` uses `player.currentTime()`, while `outputMediaDataWillChange` above uses `pendingSeekTime` for the same call. They converge in steady state — every `forceRefresh` caller is inside a seek completion handler, so `currentTime()` has already snapped to the seek target by the time the force window opens. Future-proofing only: if a caller ever invokes `forceRefresh` from outside a completion handler, the two paths would query different times. Cheap consistency cleanup would be to prefer `pendingSeekTime` if valid here too.

File: mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift [hunk 6]
```diff
@@ -101,19 +180,50 @@ final class VideoTextureOutput: NSObject, FlutterTexture {
               let player else { return }
 
         let itemTime = player.currentTime()
+
+        if CACurrentMediaTime() < forceRefreshDeadline {
+            if let pixelBuffer = output.copyPixelBuffer(
+                forItemTime: itemTime,
```
Comment (realmeylisdev) [inline mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift:186]: Same asymmetry nit as the iOS comment — poll loop here uses `player.currentTime()` while `outputMediaDataWillChange` uses `pendingSeekTime`. Future-proofing only, not a current bug.

File: mobile/packages/divine_video_player/ios/Classes/DivineVideoPlayerInstance.swift (hunk 1 above)
Comment (hm21) [reply mobile/packages/divine_video_player/ios/Classes/DivineVideoPlayerInstance.swift:317]: Addressed in ec260cbc — `handleJumpToClip` now mirrors `handleSeekTo` with `textureOutput?.forceRefresh(for:)` + `safePreroll(at:)` after the zero-tolerance seek, so `jumpToClip(int)` no longer surfaces the stuck-frame symptom by a different entry point.

File: mobile/packages/divine_video_player/macos/Classes/DivineVideoPlayerInstance.swift (hunk 2 above)
Comment (hm21) [reply mobile/packages/divine_video_player/macos/Classes/DivineVideoPlayerInstance.swift:299]: Same fix applied on macOS in ec260cbc — `handleJumpToClip` now mirrors `handleSeekTo`. iOS and macOS stay in lockstep.

File: mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift (hunk 3 above)
Comment (hm21) [reply mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift:70]: Good catch — will call this out in the PR body so future bisects don't conflate the two fixes.

File: mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift (hunk 4 above)
Comment (hm21) [reply mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift:69]: Good catch — will call this out in the PR body so future bisects don't conflate the two fixes.

File: mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift (hunk 5 above)
Comment (hm21) [reply mobile/packages/divine_video_player/ios/Classes/VideoTextureOutput.swift:195]: The asymmetry is intentional rather than a cleanup target. `outputMediaDataWillChange` is a one-shot notification tied to the seek, so `pendingSeekTime` is the right anchor. `onDisplayLink` is a periodic poll that keeps running even if playback resumes within the 600 ms force window — using `pendingSeekTime` there would request frames at a stale time once `currentTime()` advances past the seek target, racking up `forceWindowFailCount` and risking a spurious `onSeekStuck` callback. Leaving as is.

File: mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift (hunk 6 above)
Comment (hm21) [reply mobile/packages/divine_video_player/macos/Classes/VideoTextureOutput.swift:186]: The asymmetry is intentional rather than a cleanup target. `outputMediaDataWillChange` is a one-shot notification tied to the seek, so `pendingSeekTime` is the right anchor. `onDisplayLink` is a periodic poll that keeps running even if playback resumes within the 600 ms force window — using `pendingSeekTime` there would request frames at a stale time once `currentTime()` advances past the seek target, racking up `forceWindowFailCount` and risking a spurious `onSeekStuck` callback. Leaving as is.

**Review by realmeylisdev — APPROVED** [review]
LGTM — prior round's parity gap (`handleJumpToClip`) is fixed on both iOS and macOS, asymmetry nit was justified intentional, and the incidental `prev.remove(old)` correctness fix is now called out in the PR body. Thread-safety, monotonic-clock deadline, retry-loop guard, and KVO cleanup all check out. CI green.
