### PR TITLE
fix(social): bind feed-item BlocProvider to repo identity (#3503)

### LINKED ISSUE #3503: fix: cannot like first two videos in home feed
### Summary

The first two videos in the home feed cannot be liked.

### Environment

galaxy s26, main-branch

### Steps to Reproduce

1. Open the home feed.
2. Try to like one of the first two videos.
3. Observe the result.
4. Scroll further and try liking another video.

### Actual Result

Liking fails for the first two videos with error: `Bad state: No public key available — signer may not be configured`. After scrolling, liking works normally.

### Expected Result

Users should be able to like all videos in the feed without errors.

### Regression?

Yes

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Description

Fixes the regression where users could not like the first two videos in the home feed at cold launch (`Bad state: No public key available — signer may not be configured`).

**Related Issue:** Closes #3503

## Root cause

`_PooledVideoFeedItem` and friends were calling `ref.read` on `likesRepositoryProvider` / `commentsRepositoryProvider` / `repostsRepositoryProvider` and capturing those instances permanently in the `BlocProvider.create:` callback.

At cold launch, the warmup chain
(`popularNowFeedProvider` → `videoEventServiceProvider` →
`likesRepositoryProvider` → `nostrServiceProvider`)
materialises the provider graph **before** `AuthService.initialize()` resolves. The resulting `Nostr` instance is built around the `LocalKeySigner(null)` placeholder, so `Nostr._cachedPublicKey` ends up as `''`.

When auth flips, `NostrService._onAuthStateChanged` swaps to a fresh `NostrClient`, but the first two `_PooledVideoFeedItem` slots — current + adjacent in the PageView cache — already snapshotted the stale chain. Every `sendLike` from those blocs hits `Nostr.ensurePublicKey()` (`packages/nostr_sdk/lib/nostr.dart:61`) on the *stale* `Nostr` and throws. Scrolling to video 3+ mounts a fresh feed item, which captures the post‑auth providers and works.

This matches @hm21's reproduction exactly: "I have to swipe to exactly the third video before I'm able to like anything." There are two `Nostr` instances live at the same time — the stale one (placeholder signer, empty cached pubkey) referenced by videos 1 & 2's blocs, and the fresh one referenced by video 3+'s bloc.

## The fix

Switch the four `BlocProvider<VideoInteractionsBloc>` creation sites to `ref.watch` and add a record `ValueKey((likesRepository, commentsRepository, repostsRepository))` on the `BlocProvider`:

- `_PooledVideoFeedItem.build` and `_WebVideoFeedItem.build` in `video_feed_page.dart`
- `_PooledFullscreenItem.build` and `_WebFullscreenItem.build` in `pooled_fullscreen_video_feed_screen.dart`

Records compare per-field with `==`; for these classes (no custom `==`) that falls through to identity. So the key changes iff *any* of the three repository instances changes identity. When any of the three provider values changes (auth flip, account switch, sign-out), the feed item rebuilds, the key changes, the stale bloc is closed, and a fresh bloc captures the new repository chain — including the cached PageView slots for videos 1 and 2.

This mirrors the existing identity-scoped subtree pattern already in this codebase at finer scope:
- `inbox_view.dart:86` — `KeyedSubtree(key: ValueKey('messages-$currentPubkey'))`
- `video_feed_page.dart:79` — `MultiBlocProvider(key: ValueKey('video-feed-$showDivineHostedOnly'))`
- `pooled_fullscreen_video_feed_screen.dart:1214` — `key: ValueKey('metrics-${video.id}')`

## Tradeoff: bloc state is reset on swap (intentional)

When the record key changes, the old `VideoInteractionsBloc` is closed and a new one is constructed at initial state. **In-flight optimistic state — heart flipped, count incremented, pending publish — is dropped.** This is intentional and correct:

- The optimistic state was bound to the *previous* repository, which wraps a different `NostrClient` (different signer, possibly different user). Replaying it against the new one is unsafe.
- The only paths that today flip this key are auth state transitions (the cold-launch race this PR fixes) and sign-in / sign-out / account switch — all cases where the user's previous interaction state is no longer meaningful.
- A grep confirms no code today calls `ref.invalidate(likesRepositoryProvider)` or its siblings outside the auth path.

The new test `resets bloc state when likesRepositoryProvider rebuilds (intentional)` in `pooled_video_feed_item_repo_swap_test.dart` pins this contract: it forces a non-auth invalidation, asserts the bloc is recreated, and asserts the synthesised optimistic state on the previous bloc does NOT carry over to the new one. If a future change introduces a manual invalidation of one of these providers without auth context, this test will fail loudly so the state-loss can be re-evaluated.

## Why not Pattern A (return null until `isNostrReady`)?

The codebase already gates `profileRepositoryProvider` and `pendingActionServiceProvider` on `isNostrReadyProvider` (return `null` until ready). Extending that to `likesRepositoryProvider` / `commentsRepositoryProvider` / `repostsRepositoryProvider` would require a UX decision on what the feed-item action buttons render during the unready window — a designer-involved change.

The current PR uses a Flutter idiom already present in this codebase, with no UX impact. Pattern A is filed as #3523 so it can move at its own pace.

## Why this isn't a #3409 revert

The race predates #3409 by weeks: PR #2777 (2026-04-06) introduced `Nostr.ensurePublicKey` which surfaces the empty cached pubkey as `StateError`. Before that, the same race produced an `ArgumentError("Invalid key")`. PR #3409 (2026-04-26) made the failure visible to users by switching likes to optimistic-first (heart fills then rolls back) — the underlying race is unchanged. Reverting #3409 would re-hide the race but not fix it.

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

## Test plan

- [x] New widget test `pooled_video_feed_item_repo_swap_test.dart` (3 cases):
  - bloc swaps when `likesRepositoryProvider` is overridden mid-pump
  - bloc preserved when no repo identity changes (so we don't regress into "rebuild every frame")
  - bloc state resets on swap, intentionally — pins the state-loss contract
- [x] Extended `video_interactions_bloc_test.dart` — pins that `StateError("No public key available …")` from `LikesRepository.toggleLike` produces the rollback + `error: VideoInteractionsError.likeFailed`.
- [x] Existing `video_interactions_bloc_test.dart` (47 tests), `nostr_ensure_public_key_test.dart` — pass unchanged.
- [ ] **Manual**: cold-launch on a previously-authenticated session on Android (Galaxy preferred — @hm21's repro device); tap like on videos 1, 2, 3 in the home feed. All three should publish kind-7 successfully.

## Follow-ups (separate issues)

- #3523 — Apply Pattern A consistency across `likesRepository` / `commentsRepository` / `repostsRepository` (gate on `isNostrReady`, return `null` until ready) to match `profileRepository` precedent. Independent of this PR.
- #3524 — Atomic state swap in `NostrService._onAuthStateChanged` (commit `state = newClient` before disposing the old client). Defense-in-depth for any other consumer that captures `nostrServiceProvider` in a closure.
- #3525 — `VideoInteractionsState.error` is currently dead code (no widget reads it). Either wire it to a UI affordance or remove.
- #3526 — `addError(...)` in `VideoInteractionsBloc._publishLike` flows into nowhere (no `BlocObserver` registered). Forward Bloc errors to Crashlytics.
- #3527 — RFC tracker: migrate `nostrServiceProvider` to `AsyncValue<NostrClient>` and remove the `LocalKeySigner(null)` placeholder. Multi-PR migration.

cc @NotThatKindOfDrLiz — issue is assigned to you. Happy to drive review iterations or hand off; whichever you prefer.

### CODE REVIEW

File: mobile/lib/screens/feed/video_feed_page.dart [hunk 1]
```diff
@@ -895,14 +895,25 @@ class _PooledVideoFeedItem extends ConsumerWidget {
...
+    final likesRepository = ref.watch(likesRepositoryProvider);
+    final commentsRepository = ref.watch(commentsRepositoryProvider);
+    final repostsRepository = ref.watch(repostsRepositoryProvider);
 
     // Build addressable ID for reposts if video has a d-tag (vineId)
     final addressableId = video.addressableId;
 
     return BlocProvider<VideoInteractionsBloc>(
+      key: ValueKey(
+        Object.hash(
```
Comment (hm21) [inline mobile/lib/screens/feed/video_feed_page.dart]: **Record key instead of `Object.hash` + `identityHashCode`.**

`Object.hash(a, b, c)` folds three ints into a single int — theoretically collidable. Vanishingly unlikely in practice, but unnecessary. A record key compares structurally, which for classes without a custom `==` is identity-equality per field:

```dart
key: ValueKey((likesRepository, commentsRepository, repostsRepository)),
```

Strictly safer, shorter, no `identityHashCode` needed. Same suggestion applies to the three other sites (`_WebVideoFeedItem` below, `_PooledFullscreenItem` and `_WebFullscreenItem` in `pooled_fullscreen_video_feed_screen.dart`).

File: mobile/lib/screens/feed/video_feed_page.dart [hunk 2]
```diff
@@ -895,14 +895,25 @@ class _PooledVideoFeedItem extends ConsumerWidget {
...
+          identityHashCode(likesRepository),
+          identityHashCode(commentsRepository),
+          identityHashCode(repostsRepository),
+        ),
+      ),
```
Comment (hm21) [inline mobile/lib/screens/feed/video_feed_page.dart]: **Bloc-recreate state loss isn't acknowledged.**

When this composite key changes, the old bloc is closed. Optimistic like counters, in-flight `sendComment` / `sendRepost`, pending subscriptions — all gone. For a true auth flip that's probably fine (the user changed identity anyway), but for cases where identity changes for other reasons (NIP-42 reauth, network switch, manual `ref.invalidate`) this could surface as a visible reset of the user's optimistic interactions. Please call this trade-off out in the PR description, or add a test that pins the non-auth invalidation path so we know it can't regress quietly.

File: mobile/lib/screens/feed/video_feed_page.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/screens/feed/video_feed_page.dart]: Adopted in ea0aa3e. Switched to `ValueKey((likesRepository, commentsRepository, repostsRepository))` at all four production sites (`_PooledVideoFeedItem`, `_WebVideoFeedItem`, `_PooledFullscreenItem`, `_WebFullscreenItem`) and the test fixture. Per-field `==` falling through to identity for these classes is exactly the semantics we wanted; no folded-hash collision concern. Thanks for the suggestion.

File: mobile/lib/screens/feed/video_feed_page.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/screens/feed/video_feed_page.dart]: Both addressed in ea0aa3e:

**PR description**: added a "Tradeoff: bloc state is reset on swap (intentional)" section that calls out exactly what's lost (in-flight optimistic flip, pending publish), why it's correct (state is bound to the previous repo's NostrClient/signer; replaying against the new one is unsafe), and what flips the key today (only auth state transitions and sign-in/out/account switch — verified `ref.invalidate(likesRepositoryProvider)` doesn't appear elsewhere in `mobile/lib/`).

**Test**: added `resets bloc state when likesRepositoryProvider rebuilds (intentional)` in `pooled_video_feed_item_repo_swap_test.dart`. It synthesises a non-initial state on `blocBefore` (heart flipped, count=7), flips the override, and asserts both that a swap happened *and* that `blocAfter.state` is back at defaults (`isLiked: false`, `likeCount: null`, `error: null`). If a future change introduces a non-auth invalidation that we'd want to behave differently — e.g. preserve optimistic state across the swap — this test will fail loudly so the trade-off can be re-evaluated in that context rather than regressing quietly.

**Comment by realmeylisdev** [comment]
@hm21 — both review comments addressed in ea0aa3e:

1. **Record key** — switched all four production sites + the test fixture to `ValueKey((likesRepository, commentsRepository, repostsRepository))`. No more `Object.hash` / `identityHashCode`.
2. **State-loss tradeoff** — added a "Tradeoff: bloc state is reset on swap (intentional)" section to the PR body, plus a third widget test (`resets bloc state when likesRepositoryProvider rebuilds (intentional)`) that locks the contract by synthesising state on the previous bloc and asserting it doesn't carry over to the swapped-in bloc.

`dart format`, `flutter analyze lib test integration_test`, and the two scoped test files all pass locally (50 / 50). Ready for another look when you have time.

**Review by hm21 — APPROVED** [review]
LGTM and in my tests it worked perfectly fine now :)
