### PR TITLE
fix(test): await startUpload future in serialization test to prevent async leak

### LINKED ISSUE #2650: fix(test): await startUpload future in serialization test to prevent async leak
Auto-created from PR #2649.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2649
**Branch:** `fix/upload-serialization-test-async-leak`

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2650

## Summary
- Fixes async leak in the resumable upload serialization test where `unawaited(startUpload(...))` caused the upload future to outlive the test, triggering spurious "test failed after it had already completed" errors
- Captures the future and awaits it after completing the upload so post-upload logic finishes before `tearDown` disposes the manager

Extracted from #2626 (closed — the bounded resume method was dead code per review from @ryzizub and @hm21).

## Test plan
- [x] `flutter test test/services/upload_manager_resumable_upload_test.dart` — all 11 tests pass
- [x] `flutter analyze` clean
- [x] Pre-commit hooks pass

### CODE REVIEW

File: mobile/test/services/upload_manager_resumable_upload_test.dart [hunk 1]
```diff
@@ -304,6 +308,7 @@ void main() {
             fallbackUrl: 'https://media.divine.video/video-serial',
           ),
         );
+        await uploadFuture;
```
Comment (ryzizub) [inline mobile/test/services/upload_manager_resumable_upload_test.dart:311]: since the future is after but might fail, it will report progress as a success even in failure

Comment (realmeylisdev) [reply mobile/test/services/upload_manager_resumable_upload_test.dart:311]: The progress assertions at lines 292–299 run **before** `uploadCompleter.complete()` — so they're checking mid-upload serialization while the completer is still pending, not final success state.

`await uploadFuture` at the end actually **improves** failure detection: if post-upload logic (thumbnail gen, state persistence, etc.) throws, the exception now propagates and fails the test. With the old `unawaited()`, that exception was silently lost.

So the ordering is intentional:
1. Assert mid-upload progress (completer still pending → upload still "in flight")
2. Complete the mock upload
3. `await uploadFuture` — catches any post-upload failures before tearDown disposes the manager

Comment (ryzizub) [reply mobile/test/services/upload_manager_resumable_upload_test.dart:311]: My bad, i didnt realised its test 😅
