### PR TITLE
fix: pause video when modals open (#810)

### LINKED ISSUE #810: fix: background playing while creating account
### Summary

Impact: user creation experience 

Experienced
I liked a post and clicked the heart. I was prompted to create an account whilst the video in the background was looping.

Expected
The video should pause while the new user creates an account. 

Dee

### Environment

Unknown - user ticket 

### Steps to Reproduce

Unknown - user ticket 

### Actual Result

Unknown - user ticket 

### Expected Result

Unknown - user ticket 

### Regression?

Unknown

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary
- Add `onShow`/`onDismiss` callbacks to `VineBottomSheet.show()` for video pause integration
- Create `pause_aware_modals.dart` with `BuildContext` extensions that auto-pause videos
- Update share menu, report dialog, and badge modal to use video-pausing variants

Fixes #810

## Test plan
- [ ] Open share menu → video pauses
- [ ] Close share menu → video resumes
- [ ] Open report dialog → video pauses
- [ ] Close report dialog → video resumes
- [ ] Open badge explanation modal → video pauses
- [ ] Close badge modal → video resumes

### CODE REVIEW

File: mobile/lib/utils/pause_aware_modals.dart [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+    RouteSettings? routeSettings,
+    AnimationController? transitionAnimationController,
+    Offset? anchorPoint,
+  }) {
+    final container = ProviderScope.containerOf(this, listen: false);
+    final overlayNotifier = container.read(overlayVisibilityProvider.notifier);
+
+    overlayNotifier.setModalOpen(true);
+
+    return showModalBottomSheet<T>(
```
Comment (omartinma) [inline mobile/lib/utils/pause_aware_modals.dart]: We have in the package divine_ui a class to display bottom sheet. While not all bottom sheets are following this approach, from now we should aim to start using that directly for UI consistency where possible

Comment (realmeylisdev) [reply mobile/lib/utils/pause_aware_modals.dart]: Thanks for the feedback! This file already has showVideoPausingVineBottomSheet() (line 117) that uses VineBottomSheet.show() from divine_ui. Should I deprecate the raw showVideoPausingBottomSheet() method, or just add documentation recommending the VineBottomSheet version as preferred?

Comment (omartinma) [reply mobile/lib/utils/pause_aware_modals.dart]: showVideoPausingVineBottomSheet is fine, and it should be the method used. showVideoPausingBottomSheet cant be deprecated since it is a new method added on this PR, so we just need to use  showVideoPausingVineBottomSheet instead

**Review by omartinma — APPROVED** [review]
