### PR TITLE
fix(router): stop double-decoding hashtag/search path params (#3413)

### LINKED ISSUE #3413: fix(crashlytics): tolerate malformed percent-encoding in routed URI params
## Crashlytics evidence

Crashlytics issue: `489d5ebc7bd571dfd29e4701e92abdf6`

Console: https://console.firebase.google.com/project/openvine-co/crashlytics/app/ios:co.openvine.app/issues/489d5ebc7bd571dfd29e4701e92abdf6?&time=1776614940000:1777219740000

Window queried with Firebase MCP: `2026-04-19T16:09:00Z` to `2026-04-26T16:09:00Z`

Impact in that window:

- Events: 2
- Impacted users: 2
- Sessions: 2
- First seen: `1.0.8`
- Last seen: `1.0.8`

Sample event:

- Event: `projects/972941478875/apps/1:972941478875:ios:f61272b3cf485df244b5fe/events/21a5cb7439544ed0841f0343afce5bd8_2210482796804345867`
- App version: `1.0.8`
- Breadcrumbs included repeated pooled feed screen views, explore tab changes, and profile-view navigation.

Exception:

```text
FlutterError: Invalid argument(s): Illegal percent encoding in URI. Error thrown .
at Uri.decodeComponent (dart:core)
at goRouterProvider.<fn>.<fn> (package:openvine/router/app_router.dart:388)
at _CustomNavigatorState._buildPageForGoRoute.<fn> (package:go_router/src/builder.dart:267)
```

## Start here

Likely code path:

- `mobile/lib/router/app_router.dart`
- Search/hashtag/search-results route builders manually call `Uri.decodeComponent(...)` on `state.pathParameters`.
- `Uri.decodeComponent` throws on malformed percent encoding such as a dangling `%` or invalid escape sequence.

Relevant local code at time of triage includes:

```text
app_router.dart:431  final decoded = Uri.decodeComponent(tag);
app_router.dart:441  final decoded = query != null ? Uri.decodeComponent(query) : '';
```

Line numbers may have drifted from Crashlytics symbolication, but the failing operation is the explicit `Uri.decodeComponent` call in a route builder.

## Investigation requirements

- Identify all route builders that decode user-controlled path params.
- Determine whether `go_router` has already decoded these path params in the current version.
- Determine which route path can receive malformed percent-encoded input from deep links, hashtags, search terms, or profile/video IDs.
- Do not silently route malformed input to the wrong destination; choose a safe fallback UI or normalized route.

## Suggested fix direction

- Add a small helper for safe decoding of path parameters.
- Return an error route/screen or fallback string when decoding fails.
- Prefer preserving the raw value for logging without crashing.
- Add tests for malformed path params like `%`, `%2`, `%ZZ`, and mixed valid/invalid escaped input.

## Verification

- Add router tests for malformed percent-encoded deep links.
- Run the router-focused Flutter tests from `mobile/`.
- Manually open malformed search/hashtag links on iOS and confirm the app does not crash.
- After release, confirm Crashlytics issue `489d5ebc7bd571dfd29e4701e92abdf6` stops receiving events.

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Description

Fixes the iOS Crashlytics crash `489d5ebc7bd571dfd29e4701e92abdf6` (*"Invalid argument(s): Illegal percent encoding in URI"*) raised from `app_router.dart` whenever a hashtag or search-results route receives a path parameter that contains a literal `%` after one URL decode (e.g. searching for `100%`).

`go_router` 16.3.0 already calls `Uri.decodeComponent` on path parameters during route matching ([`go_router/src/match.dart:223`](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/match.dart#L223)). The two GoRoute builders for `/hashtag/:tag` and `/search-results/:query` were decoding a second time, so any value whose raw URL form contained `%25` round-tripped to a single `%`, which then crashed the second decode.

The primary commit removes the redundant decode in those two builders. The secondary commit hardens `parseRoute` in `page_context_provider.dart` (which still parses raw URL strings and therefore still needs to decode segments) by routing every segment decode **in `parseRoute`** through a `_safeDecode` helper that returns the raw input on `ArgumentError` instead of throwing.

Other decode sites in the codebase are intentionally untouched. In particular `deep_link_service.dart:206` still calls `Uri.decodeComponent` directly on the invite-code segment — the entire `parseDeepLink` body is wrapped in a top-level `try/catch` (see `deep_link_service.dart:227-234`) that converts any decode error into `DeepLinkType.unknown`, which is a different but functional crash-prevention mechanism. Routing it through `_safeDecode` would change the user-visible failure (raw segment forwarded to redemption vs. "unknown deep link"), which is a scoped behavior decision, not a drive-by hardening.

**Related Issue:** Closes #3413

## Reproduction (pre-fix)

1. Run the app on iOS in release mode (or debug — the crash is the same).
2. Open the search bar and submit any query containing a literal `%`, such as `100%` or `50% off`.
   - Equivalent deep link: `divine://search-results/100%25` (or `https://divine.video/search/100%25`).
3. Observe `FlutterError: Invalid argument(s): Illegal percent encoding in URI. Error thrown.` from `Uri.decodeComponent` at `app_router.dart` (line 418/428 pre-fix).

The same crash reproduces for hashtags via `divine://hashtag/100%25fun` (a hashtag like `100%fun`).

## Root cause

```
'100%' → Uri.encodeComponent('100%') = '100%25'             // SearchResultsPage.pathForQuery / HashtagScreenRouter.pathForTag
       → URL '/search-results/100%25'
       → go_router extractPathParams: 'query' = '100%25'    // raw regex capture
       → match.dart:223  Uri.decodeComponent('100%25') = '100%'
       → state.pathParameters['query'] == '100%'
       → app_router.dart  Uri.decodeComponent('100%') ❌ throws  // double-decode
```

## Fix

- **`app_router.dart`** — pass `state.pathParameters['tag']` / `['query']` directly to `HashtagFeedScreen` / `SearchResultsPage`. `go_router` already gives a fully-decoded value.
- **`page_context_provider.dart`** — add a private `_safeDecode(segment)` helper and route all 14 `Uri.decodeComponent(segments[...])` callsites in `parseRoute` through it so a hand-crafted deep link (e.g. `/hashtag/foo%`) cannot crash the location stream.

The split is intentional: the first commit closes the Crashlytics issue; the second commit is defensive hardening for any other malformed URL that reaches the parse path.

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

## Test plan

New tests, all passing locally:

- `test/router/app_router_test.dart` — round-trip tests covering `pathForTag('100%fun')`, `pathForTag('c#dev')`, `pathForQuery('100%')`, `pathForQuery('50% off deals')`. Each pumps a minimal `GoRouter` mirroring the production builders, navigates via the canonical helper, and verifies that the captured `state.pathParameters` value equals the original input with no thrown exceptions. A second group adds a static-source guard that reads `lib/router/app_router.dart` and fails if either the hashtag or search-results builder region reintroduces `Uri.decodeComponent` (the exact regression that caused the crash) — closes the gap that the round-trip tests' synthetic builder doesn't cover.
- `test/router/route_coverage_test.dart` — `parseRoute` malformed-input regressions for `foo%`, `foo%2`, `foo%ZZ`, `%` against `/hashtag`, `/profile`, and `/video` routes, plus a sanity test that valid `Uri.encodeComponent` input still decodes correctly.

Verification commands run from `mobile/`:

```sh
dart format <changed files>           # 0 changes
flutter analyze lib test               # No issues found
flutter test test/router/              # 134 passed, 65 pre-existing skips
flutter test test/services/deep_link_service_test.dart \
             test/providers/deep_link_provider_test.dart   # All passed
```

## Risk

- **Behavior change for legitimate inputs**: none. `pathForTag` / `pathForQuery` always encode once via `Uri.encodeComponent` and `go_router` decodes once on the way back, so the post-fix path is the symmetric counterpart of how URLs are constructed. Inputs without `%` are unaffected.
- **External callers**: `grep` shows no call site that bypasses `pathForTag` / `pathForQuery` to construct these URLs by hand inside `mobile/lib`.
- **Universal links / share sheets**: handled upstream by `universal_link_resolver.dart` before reaching the GoRoute builder; that layer already passes through encoded paths.

## Post-release verification

After this lands in a release build, confirm Crashlytics issue [`489d5ebc7bd571dfd29e4701e92abdf6`](https://console.firebase.google.com/project/openvine-co/crashlytics/app/ios:co.openvine.app/issues/489d5ebc7bd571dfd29e4701e92abdf6) stops receiving new events.

### CODE REVIEW

File: mobile/test/router/app_router_test.dart [hunk 1]
```diff
@@ -75,4 +78,112 @@ void main() {
...
+  // contract — "the value reaching state.pathParameters equals the original
+  // string passed to pathForTag/pathForQuery" — can be exercised without
+  // pulling in the full app provider graph.
+  group('Path-parameter round-trip (#3413)', () {
+    Future<({String? capturedTag, String? capturedQuery})> navigateAndCapture(
+      WidgetTester tester,
+      String location,
+    ) async {
+      String? capturedTag;
+      String? capturedQuery;
```
Comment (hm21) [inline mobile/test/router/app_router_test.dart:100]: Test-fidelity nit (non-blocking): this `GoRouter` is a synthetic stand-in — it captures `pathParameters['tag']` directly and never exercises the production builder in `app_router.dart`. So what's actually being asserted here is *"go_router decodes a `pathForTag`-encoded URL once back to the original"*, i.e. an assumption about go_router's internals — not the production behavior.

Concrete failure mode this misses: if a future change re-introduces `Uri.decodeComponent(tag)` inside the real builder at `app_router.dart:411-435`, this test still passes. The crash only comes back at runtime.

A more direct regression test would pump the real `goRouterProvider`, navigate to `pathForTag('100%fun')`, and `expect(find.byType(HashtagFeedScreen), findsOneWidget)` plus assert the screen's `hashtag` prop equals the original. That binds the test to the production builder, not to go_router.

File: mobile/lib/router/providers/page_context_provider.dart [hunk 2]
```diff
@@ -133,6 +133,22 @@ class RouteContext {
...
+/// Decodes a URL path segment, returning the raw input on malformed
+/// percent-encoding instead of throwing. See #3413.
+///
+/// `Uri.decodeComponent` throws `ArgumentError` on malformed input
+/// (e.g. a dangling `%` from a hand-crafted deep link). Treating that
+/// as a recoverable boundary error rather than a programmer bug is
+/// intentional here, so the lint is suppressed locally.
+String _safeDecode(String segment) {
+  try {
+    return Uri.decodeComponent(segment);
```
Comment (hm21) [inline mobile/lib/router/providers/page_context_provider.dart:145]: The PR body says the secondary commit hardens *"every segment decode"* against malformed input — but `deep_link_service.dart:206` still calls `Uri.decodeComponent(pathSegments[1])` ungeguardetly for the invite-code path. The whole `parseDeepLink` is wrapped in a top-level `try/catch`, so it can't actually crash — it falls through to `DeepLinkType.unknown`. So no functional bug, but the "all decodes routed through `_safeDecode`" claim isn't quite true. Either route the invite decode through `_safeDecode` for consistency, or narrow the PR-body claim. Non-blocking.

File: mobile/test/router/app_router_test.dart [hunk 3]
```diff
@@ -75,4 +78,112 @@ void main() {
...
+          tester,
+          HashtagScreenRouter.pathForTag(original),
+        );
+
+        expect(tester.takeException(), isNull);
+        expect(result.capturedTag, equals(original));
+      },
+    );
+
+    testWidgets(
```
Comment (hm21) [inline mobile/test/router/app_router_test.dart:162]: Cosmetic: this test is labeled `"with literal #"`, which suggests it covers Fragment-Delimiter behavior. It doesn't — `Uri.encodeComponent('c#dev')` is `c%23dev`, so this is just another percent-encoding round-trip (the `#` never reaches the URL parser as a fragment delimiter). The test is fine, but the name is misleading. Consider `"with characters that require percent-encoding"` or similar.

File: mobile/test/router/app_router_test.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/test/router/app_router_test.dart:100]: Good catch. Pumping the real `goRouterProvider` + `HashtagFeedScreen` would require a fairly large mock graph (`HashtagService`, `view_event_publisher`, the curation providers, the video stream), so I went with a static-source guard instead: `test/router/app_router_test.dart` now reads `lib/router/app_router.dart` and fails if either the hashtag or search-results builder region contains `Uri.decodeComponent`. That covers the exact failure mode you named — re-introducing the decode in those builders — without paying the screen-rendering cost. Done in a2e3c2735.

File: mobile/lib/router/providers/page_context_provider.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/router/providers/page_context_provider.dart:145]: Fair — re-reading the PR body, "every segment decode" is broader than the scope of the change. I deliberately didn't touch `deep_link_service.dart:206`: that path is already wrapped in a top-level `try/catch` that converts any decode error into `DeepLinkType.unknown`, which is a different — but functional — crash-prevention mechanism. Routing it through `_safeDecode` would silently change the user-visible failure (raw segment forwarded to redemption vs. "unknown deep link"), which I'd want to do as its own scoped change rather than a drive-by here. Updated the PR description to explicitly scope the wording to `parseRoute` and call out that other decode sites are intentionally untouched.

File: mobile/test/router/app_router_test.dart (hunk 3 above)
Comment (realmeylisdev) [reply mobile/test/router/app_router_test.dart:162]: Renamed to `'pathForTag with literal `#` (encoded as `%23`) round-trips correctly'` in a2e3c2735 — agree the old name implied fragment-delimiter semantics that the test doesn't actually exercise.

**Review by hm21 — APPROVED** [review]
