### PR TITLE
fix: resolve various user-profile issues

### LINKED ISSUE #3223: Profile scroll topInset updates rebuild the full profile surface during scroll
## Problem
The new profile scroll architecture updates `_tabBarTopInset` via `setState()` inside the scroll listener. That inset changes continuously through the status-bar transition band, so the entire `ProfileGridView` subtree rebuilds while scrolling.

The rebuilt subtree includes the `NestedScrollView`, `MultiBlocProvider`, and `TabBarView`, which is much broader than the visual surface that actually depends on the inset.

## Current code
- `mobile/lib/widgets/profile/profile_grid.dart`

## Why this matters
This is a likely source of avoidable jank on the new profile screen, especially on lower-end devices or when the profile tabs are heavy.

## Suggested fix
Move the inset into the same narrow update pattern already used for other scroll-driven profile layers:
- use a `ValueNotifier<double>` (or equivalent narrow state holder)
- rebuild only the pinned tab-bar header that consumes `topInset`
- avoid full `ProfileGridView` rebuilds from `_onScroll()`

## Acceptance
- `_onScroll()` no longer triggers a full widget `setState()` just to update tab-bar inset.
- Only the pinned-header surface rebuilds when the inset changes.
- Add a targeted test if practical, or include a short manual verification note focused on scroll smoothness.

### PR DESCRIPTION
**Pull request by hm21**
## Description

This PR resolves several minor issues in the user profile.

* Fixed performance issues while scrolling and corrected the misuse of IntrinsicHeight
* Improved layout structure so the button row is properly placed within a column instead of relying on recalculating top offsets
* Fixed issues where deleting the profile picture, selected color, or “About Me” section did not work
* Resolved broken layout during the initial frames when the widget builds
* Ensured the correct user profile is shown immediately instead of briefly displaying an empty profile
* Loading more spinner was hidden behind the safearea on newer android devices

#### Example of what the first few frames look like before the fix.
image

**Related Issue:** Closes #3223

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/widgets/profile/profile_header_widget.dart [hunk 1]
```diff
@@ -77,30 +83,74 @@ class ProfileHeaderWidget extends ConsumerWidget {
...
+class _ProfileHeaderWidgetState extends ConsumerState<ProfileHeaderWidget> {
+  /// Whether the profile content has been revealed.
+  /// Flips to true once profile data arrives and never resets.
+  bool _profileVisible = false;
+
+  @override
+  void initState() {
+    super.initState();
+
+    WidgetsBinding.instance.addPostFrameCallback((_) {
```
Comment (omartinma) [inline mobile/lib/widgets/profile/profile_header_widget.dart:115]: Not sure i fully understand why this is needed if we have the logic about fetching the profile before with the bloc or provider

Comment (hm21) [reply mobile/lib/widgets/profile/profile_header_widget.dart:115]: The problem was that while we’re fetching the profile, we still render this widget in an empty state. That means every time you open your own profile, the empty header briefly appears for a frame or two, even though a cached profile exists.

When i look on the bloc logic [here](https://github.com/divinevideo/divine-mobile/blob/eea178f0e14aef7d1a95bbb1f55c9c7a6e12be5e/mobile/lib/blocs/my_profile/my_profile_bloc.dart#L40-L42) we read the cached profile on initialization, but since that call is async, the widget builds before the data is available. So this change helps by checking whether the profile is ready. If it is, we show it immediately. If not, we skip a frame and fade it in, which avoids the visible flicker.

As alternatives, we could show a skeleton while loading (but would require a decision from the design-team) or we could move the bloc higher up in the tree so the cached profile is fetched on app start. That way, the profile would already be available instantly when navigating to the page.

**Comment by rabble** [comment]
Second-pass review found a stale-layout bug in the sticky tab trigger.

`_ProfileTabBarState` caches `_cachedHeaderHeight` on first scroll and then reuses it forever (`mobile/lib/widgets/profile/profile_grid.dart:467-507`). But the profile header can still change height after that first measurement: `ProfileHeaderWidget` flips `_profileVisible` after the first frame and also resolves `effectiveProfile` asynchronously from bloc/provider state (`mobile/lib/widgets/profile/profile_header_widget.dart:115-143`).

So if the user scrolls before the final bio/stats/name state has settled, the tab bar pins against an old header height and the sticky threshold is wrong for the rest of the session. I’d either invalidate the cached height whenever the header subtree changes, or stop caching it across async header updates.

**Comment by hm21** [comment]
@rabble I’m not sure I fully understand your point. This PR actually removes `_cachedHeaderHeight` entirely, so that old behavior doesn’t exist anymore. Also, it doesn’t seem related to `_tabBarTopInset`, since that value should stay at 0 until the user has fully scrolled to the top of the page. Or did you mean something else?
