### PR TITLE
fix(dm): resolve search flash-and-stuck bug in new message sheet

### LINKED ISSUE #2402: fix(dm): resolve search flash-and-stuck bug in new message sheet
Auto-created from PR #2401.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2401
**Branch:** `fix/dm-search-flash-and-stuck`

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2402

## Summary

- **Fix event normalization** — pass trimmed value to `UserSearchQueryChanged` instead of raw TextField value, preventing phantom events that bypass Equatable dedup in the debounce stream
- **Remove dedup guard** — the `restartable()` transformer (switchMap) already cancels previous handlers; the manual same-query skip was stranding the BLoC in `loading` or empty-`success` with no recovery path
- **Merge local + network results** — redesign `_NetworkResults` to combine followed contacts with network search results via O(n+m) map keyed by pubkey, showing results during loading and falling back to local contacts on failure

## Root cause

Three interacting bugs in the DM user search (new message sheet):

1. `_onSearchChanged` passed raw `value` to the BLoC event while the handler trimmed it. Events like `"alice"` and `"alice "` had different Equatable props but the same trimmed query, causing `restartable()` to cancel handler A while the dedup check blocked handler B → state stuck at `loading` forever.

2. The dedup guard (`query == state.query && status != initial`) blocked re-search on `loading`, `failure`, and empty `success` states. Once stuck, the user could never re-trigger the same query without fully clearing the text field.

3. `_NetworkResults` replaced local contact matches with a bare spinner on `loading`, then showed only network results on `success`. Followed contacts that weren't indexed by the search API would flash for ~300ms (during `initial` state) then vanish permanently.

## Test plan

- [x] `flutter analyze` passes on changed files
- [x] All 33 `UserSearchBloc` tests pass (updated dedup test → fresh search test)
- [ ] Manual: open new message sheet → type a followed contact's name → contact appears immediately and persists through loading → network results merge in
- [ ] Manual: search for a name → see results → backspace partially and retype same name → search runs again (no stuck state)
- [ ] Manual: search while offline → failure state shows local contact matches as fallback
- [ ] Manual: type rapidly → only one search fires after 300ms of silence (debounce still works)

### CODE REVIEW

File: mobile/lib/screens/inbox/new_message_sheet.dart [hunk 1]
```diff
@@ -297,32 +297,43 @@ class _NetworkResults extends StatelessWidget {
   final List<UserProfile> localResults;
   final ValueChanged<UserProfile> onSelectUser;
 
+  /// O(n+m) merge: network results take precedence, local fills gaps.
+  /// Uses LinkedHashMap to preserve insertion order and dedup by pubkey.
+  List<UserProfile> _mergeResults(List<UserProfile> networkResults) {
```
Comment (omartinma) [inline mobile/lib/screens/inbox/new_message_sheet.dart]: Cant be handle in the bloc directly?

Comment (realmeylisdev) [reply mobile/lib/screens/inbox/new_message_sheet.dart]: totally agree with that, tackling now.

File: mobile/lib/screens/inbox/new_message_sheet.dart [hunk 2]
```diff
@@ -103,15 +103,16 @@ class _NewMessageSheetState extends State<NewMessageSheet> {
...
-      _searchBloc.add(UserSearchQueryChanged(value));
-      setState(() {
-        _filteredContacts = _contacts.where((profile) {
-          final name = profile.bestDisplayName.toLowerCase();
-          final nip05 = (profile.nip05 ?? '').toLowerCase();
-          return name.contains(trimmed.toLowerCase()) ||
-              nip05.contains(trimmed.toLowerCase());
-        }).toList();
-      });
+      final filtered = _contacts.where((profile) {
```
Comment (omartinma) [inline mobile/lib/screens/inbox/new_message_sheet.dart]: Good for now, but a follow up PR creating an specific bloc for this functionality might be the ideal. This bloc will have some similar functionality of UserSearchBloc, but it will contain the logic of loading contacts. That way we will have a much cleaner UI here and will have all the logic on that bloc
