### PR TITLE
fix(dm): restore DMs orphaned by database path change

### LINKED ISSUE #2834: fix: previous DMs missing after latest TestFlight update
### Summary

All previously existing direct messages are missing after updating via TestFlight.

### Environment

latest release

### Steps to Reproduce

1. Install the latest TestFlight update.
2. Open the app.
3. Navigate to direct messages.

### Actual Result

All prior direct messages are missing.

### Expected Result

Existing direct messages should remain visible after updating the app.

### Regression?

Yes

### Evidence

Reported on Discord [here](https://discord.com/channels/1470168817589158040/1470255950408454164/1490754414485569729)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary
Closes #2834

PR #2840 moved the SQLite database from `getApplicationDocumentsDirectory()` to `getApplicationSupportDirectory()` without a data migration. Users who updated via TestFlight got a fresh empty DB at the new path while their real DMs stayed at the old path. The migration added in PR #2887 skips the move when the new DB already exists, leaving intermediate-build users stuck with missing DMs.

### Root Cause
- **Primary**: DB path change in #2840 orphaned all local data (DMs, conversations, notifications, etc.)
- **Secondary**: `DmSyncState` SharedPreferences keys were never cleared alongside DB table wipes, so stale sync cursors prevented a full relay re-fetch after data loss

### Changes

1. **`dbCacheVersion` reset mechanism** — A file-based cache version constant (`divine_db.version`) next to the database. Bumping `dbCacheVersion` forces a full DB reset on next app launch. Since all local data is re-fetchable from Nostr relays, the database is effectively a cache. This gives us a deterministic, general-purpose reset lever for future schema changes, path migrations, or data corruption — no heuristics tied to user data.

2. **Simplified `migrateLegacyDatabase()`** — When both old-path and new-path databases exist, always prefer the legacy (old-path) DB. It predates the path change and has more history by definition. Removed the conversation-count heuristic and the `sqlite3` runtime dependency.

3. **Added `DmSyncState.clearAll()`** — Wired into `onDatabaseCleanup` callback so stale sync cursors are cleared alongside table wipes, forcing a full `limit: 50` relay re-fetch on next login.

4. **Added DM sync cursor prefixes to `identityChangePrefixes`** — Identity-change cleanup now also clears `dm.newestSyncedAt.*` and `dm.oldestSyncedAt.*` keys.

### Risk Assessment

| Risk | Likelihood | Mitigation |
|------|-----------|-----------|
| Future version bump wipes all users' local data | By design — Nostr data is re-fetchable from relays | Version history is documented in the constant's docstring. Local-only data (drafts, pending uploads) is lost on reset — acceptable trade-off for a clean-slate recovery |
| First deployment doesn't fix "both DBs" users | Low — the "prefer legacy when both exist" rule handles this regardless of version state | Tested with both-DBs scenario in `connection_native_test.dart` |
| Version file deleted by user/OS cleanup | Low | Falls back to "no version = treat as current" — writes the current version without wiping, so the mechanism re-initializes safely |

## Steps to Reproduce (original bug)
1. Install a build from before PR #2840 (database at Documents path)
2. Seed DM conversations
3. Update to a build containing #2840 but before #2887 (database path changes to Application Support, no migration)
4. Open app → all prior DMs are missing
5. Update to a build with #2887 → DMs still missing (migration is a no-op because new DB already exists)

## Test Plan
- [x] `connection_native_test.dart`: 16 tests covering `applyDbCacheVersionReset` (first run, stale version, current version, missing DB), `readDbCacheVersion`/`writeDbCacheVersion` (round-trip, missing file, corrupt file), and `migrateLegacyDatabase` (move, both-exist replacement, sidecar cleanup, fresh install, sidecar migration)
- [x] `dm_sync_state_test.dart`: `clearAll()` removes all sync cursor keys while preserving unrelated keys
- [x] `dm_repository_test.dart`: `_FakeDmSyncState.clearAll()` implemented for test coverage
- [x] `user_data_cleanup_service_test.dart`: DM sync cursor prefixes present in `identityChangePrefixes`, cleared on identity change, preserved on non-identity cleanup

### CODE REVIEW

File: mobile/packages/db_client/lib/src/database/connection/connection_native.dart [hunk 1]
```diff
@@ -46,12 +47,21 @@ Future<String> getSharedDatabasePath() async {
   return newPath;
 }
 
+/// If the new DB has at most this many conversations it is considered an
+/// artifact of the relay re-fetch (`limit: 50`) and is safe to replace
+/// with the legacy database that contains the user's real history.
+@visibleForTesting
+const int maxConversationsForReplacement = 5;
```
Comment (untreu2) [inline mobile/packages/db_client/lib/src/database/connection/connection_native.dart]: I think there's a better way to do this.

We could have a database reset mechanism that we can control directly ourselves. We would put the database version in the constants and reset the entire database in the version we want. I think this is a better solution because Nostr clients store a lot of data locally. We may encounter similar issues with other event kinds as well in the future.

And I don't think that the number of conversations user has is a good metric. None of the data logic should be linked to the user’s personal data. I’m not saying this for privacy reasons, because it’s a local operation, but it’s inconsistent.

**Review by untreu2 — CHANGES_REQUESTED** [review]

**Review by untreu2 — APPROVED** [review]
Okay, approved. Let’s see if the issue persists on the users’ end. At least we’ll have ensured that the problem has been resolved on the database side. 

If the issue persists, we can check event processing in more detail.
