### PR TITLE
fix: display thumbnail with progress while video uploading

### LINKED ISSUE #1267: fix: Missing thumbnail preview during video upload processing
### Summary

The video placeholder in the profile page displays a black background instead of the video thumbnail while the upload is in progress.

### Environment

Build: 1.0.4(344) on iOS and 1.0.4(209) on Android
Device: Samsung A54 and Iphone Se v26.3

### Steps to Reproduce

Open the app
Open the camera
Create a video

### Actual Result

When a new post is being uploaded, a loading indicator is displayed, but the video thumbnail area remains completely black.

### Expected Result

The profile grid should show the video's thumbnail with a loading overlay  to provide visual context to the user while the processing completes.

Image

### Regression?

Yes

### Evidence

https://github.com/user-attachments/assets/10a50e68-e483-4c64-b302-26b991bbaad2

### PR DESCRIPTION
**Pull request by JohnWeidner**
While a video is being uploaded and the user is on the "My Videos" tab of their profile page, we will display a thumbnail of the video with a progress overlay.

<details>
  <summary>Video showing change</summary>

- Jump to 20 seconds in

https://github.com/user-attachments/assets/71eaf338-46be-4a12-af21-c8ea8cc0f524

</details>

**Related Issue:** Closes #1267 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/widgets/profile/profile_videos_grid.dart [hunk 1]
```diff
@@ -155,40 +153,37 @@ class _ProfileVideosEmptyState extends StatelessWidget {
...
+        children: [
+          if (thumbnailPath != null)
+            Image.file(
+              File(thumbnailPath),
+              fit: BoxFit.cover,
+              errorBuilder: (_, __, ___) => const _ThumbnailPlaceholder(),
+            )
+          else
+            const _ThumbnailPlaceholder(),
+          const ColoredBox(color: Color(0x66000000)),
```
Comment (omartinma) [inline mobile/lib/widgets/profile/profile_videos_grid.dart:179]: Question: does this make sense to live in the divine_ui for consistency if we need to reuse it?
