### PR TITLE
fix(feed): make followRepository non-nullable and skip duplicate API call

### LINKED ISSUE #1977: perf: improve home feed initial load performance
## Summary

Home feed takes noticeably longer to load than expected, especially on cold app open. The Funnelcake REST API fast path is available but never used for the home feed — all requests go through the slower Nostr relay WebSocket fallback.

## Environment

- All devices and OS versions
- All network conditions (most noticeable on slower connections)
- Affected feeds: Home, For You

## Steps to Reproduce

1. Open the app (cold start)
2. Land on the home feed
3. Observe loading time before first video appears

## Actual Result

Home feed loading takes ~200-2000ms for the data fetch step because it always uses the Nostr relay WebSocket path, even when the faster Funnelcake API is available and configured.

## Expected Result

Home feed should load in ~50-200ms by using the Funnelcake REST API when available, significantly reducing time-to-first-video.

## Regression?

No — the `userPubkey` parameter was never wired through to `getHomeFeedVideos()` since the `VideoFeedBloc` was introduced.

## Evidence

In `video_feed_bloc.dart`, `_fetchVideosForMode()` calls `getHomeFeedVideos()` without passing `userPubkey`, which is required for the Funnelcake API path (see `videos_repository.dart` line 90: `if (userPubkey != null && _funnelcakeApiClient != null ...)`).

### PR DESCRIPTION
**Pull request by omartinma**
## Description

Make `followRepositoryProvider` non-nullable by removing the `isNostrReadyProvider` gate that blocked the entire UI until Nostr keys were ready. This eliminates null checks from 12+ consumer files and removes a redundant duplicate Funnelcake API call on startup (caused by the BehaviorSubject replay on `followingStream`) that was adding ~4s of wasted load time.

To avoid losing the "no follows" CTA (which previously relied on the BehaviorSubject replay reaching `_onFollowingListChanged`), `_onStarted` now checks `followingPubkeys` directly after the initial load. This handles BLoC re-creation (e.g. navigating back to home) where `.skip(1)` would skip the only replay.

**Related Issue:** Closes #1977

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

### CODE REVIEW

File: mobile/lib/blocs/other_profile/other_profile_bloc.dart [hunk 1]
```diff
@@ -145,10 +145,9 @@ class OtherProfileBloc extends Bloc<OtherProfileEvent, OtherProfileState> {
     _blocklistService.blockUser(pubkey, ourPubkey: _currentUserPubkey);
 
     // Unfollow the user if we're currently following them
-    final followRepo = _followRepository;
-    if (followRepo != null && followRepo.isFollowing(pubkey)) {
+    if (_followRepository.isFollowing(pubkey)) {
```
Comment (hm21) [inline mobile/lib/blocs/other_profile/other_profile_bloc.dart:148]: Nit: we could use directly `isFollowing`

```suggestion
    if (isFollowing) {
```

**Comment by omartinma** [comment]
@NotThatKindOfDrLiz @rabble please dont merge this for now. I'm trying to debug this with @hm21 and @meylis1998 since we are not able to find the the cause of what Alex is experiencing.
