### PR TITLE
fix: rollback username claim on profile publish failure

### LINKED ISSUE #823: fix:  Profile | P0 | Username save returns error but still reserves the username
### Summary

When editing the profile and saving an optional username, sometimes the app shows an error but after restarting the app the username appears as “taken,” suggesting it was reserved even though the update failed.

### Environment

App version: 1.0.4 (223)
OS: iOS v26.3 
Device: Iphone Se

### Steps to Reproduce

Open the app and go to Profile → Edit Profile.
Enter a new value in the optional Username field.
Tap Save.
Observe the error message
Close and reopen the app.
Try saving the same username again.

### Actual Result

Sometimes the save action returns an error (profile update appears to fail).

After restarting, the username is marked as already taken.

### Expected Result

The user should not see any error.

### Regression?

No

### Evidence

https://github.com/user-attachments/assets/c053d5b1-6c19-47c3-a6d1-2259df0786c2

### LINKED ISSUE #910: feat: user information repository
It will have method to get information of the user, reusable for scenarios like displaying it on video feed.

### PR DESCRIPTION
**Pull request by Josh-Sanford**
## Summary

Fixes #823, #704 - Username claims are now rolled back when profile publishing fails, preventing orphaned username reservations.
Closes #910 

**Key changes:**
- Add `ProfileEditorNotifier` to orchestrate profile save + username claim with automatic rollback
- Add `ProfileRepository` package for profile fetching and publishing
- Refactor `Nip05Service` to be stateless and throw typed exceptions
- Simplify `UsernameNotifier` to only handle availability checking (registration moved to ProfileEditorNotifier)
- Replace reserved username snackbar with email dialog for support contact

**Profile save success**

https://github.com/user-attachments/assets/eac9522f-81ea-487b-a0c2-8e74b1655cac

**Profile save failed and old profile rolled back**
 Known edge case: When testing rollback with a taken username, the rollback restores the profile to the relay state, not the locally cached state. If the local cache is out of sync with the relay (e.g., from a previous session), the restored username may differ from what was displayed in the edit form. This is expected behavior - the rollback fetches currentProfile from the relay as the source of truth. A separate stale cache issue may cause the local cache and relay to diverge.

https://github.com/user-attachments/assets/0ff1aa26-b8e4-463f-9466-267dd7b03c69

### CODE REVIEW

File: mobile/lib/providers/profile_editor_notifier.dart [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+  ///
+  /// The operation follows this sequence:
+  /// 1. Publish profile to Nostr with the new nip05 (if username provided)
+  /// 2. Claim the username via the name server
+  /// 3. If claim fails, rollback by publishing profile without the nip05
+  ///
+  /// [pubkey] is the user's public key in hex format.
+  /// [displayName] is required and will be shown as the user's name.
+  /// [username] if provided, will be claimed as `username@divine.video`.
+  Future<void> saveProfile({
```
Comment (ryzizub) [inline mobile/lib/providers/profile_editor_notifier.dart]: This seems to me like a something that we can use to move to bloc as a part of continous movement to bloc

File: mobile/lib/services/nip05_service.dart [hunk 2]
```diff
@@ -120,119 +102,23 @@ class Nip05Service {
...
-      _isVerified = true;
-    } else {
-      _currentUsername = null;
-      _isVerified = false;
+    switch (response.statusCode) {
+      case (200 || 201):
+        return;
+      case 403:
+        throw UsernameReservedException(
+          'Username is reserved. Contact support if you are the original owner.',
```
Comment (ryzizub) [inline mobile/lib/services/nip05_service.dart]: nit: this text should come from UI not be maintained in service as long-term we want to introduce l10n

File: mobile/packages/profile_repository/README.md [hunk 3]
```diff
@@ -0,0 +1,62 @@
+# Profile Repository
+
+[![style: very good analysis][very_good_analysis_badge]][very_good_analysis_link]
+[![Powered by Mason](https://img.shields.io/endpoint?url=https%3A%2F%2Ftinyurl.com%2Fmason-badge)](https://github.com/felangel/mason)
+[![License: MIT][license_badge]][license_link]
```
Comment (ryzizub) [inline mobile/packages/profile_repository/README.md]: nit: please remove unecessary things from README link MIT Lincense etc.

File: mobile/lib/providers/profile_editor_notifier.dart [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+    state = const AsyncLoading();
+    final usernameRepository = ref.read(usernameRepositoryProvider);
+    final profileRepository = ref.read(profileRepositoryProvider);
+    final userProfileService = ref.read(userProfileServiceProvider);
+    final currentProfile = await profileRepository.getProfile(pubkey: pubkey);
+    final nip05 = (username != null && username.isNotEmpty)
+        ? '$username@divine.video'
+        : null;
+
+    Log.info(
```
Comment (ryzizub) [inline mobile/lib/providers/profile_editor_notifier.dart]: Do we need here all these logs?, especially when we have two in a row

File: mobile/packages/profile_repository/lib/src/profile_repository.dart [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    : _nostrClient = nostrClient;
+
+  final NostrClient _nostrClient;
+
+  /// Fetches a user profile by pubkey.
+  ///
+  /// Returns `null` if no profile exists for the given pubkey.
+  Future<UserProfile?> getProfile({required String pubkey}) async {
+    final profileEvent = await _nostrClient.fetchProfile(pubkey);
+    if (profileEvent == null) return null;
```
Comment (omartinma) [inline mobile/packages/profile_repository/lib/src/profile_repository.dart:22]: Wondering if we should better throw a not found exception to avoid handle null

File: mobile/packages/profile_repository/pubspec.yaml [hunk 6]
```diff
@@ -0,0 +1,23 @@
+name: profile_repository
+description: A Very Good Project created by Very Good CLI.
```
Comment (omartinma) [inline mobile/packages/profile_repository/pubspec.yaml]: We should update description

File: mobile/packages/profile_repository/pubspec.yaml [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+version: 0.1.0+1
+publish_to: none
+
+environment:
+  sdk: ^3.9.0
```
Comment (omartinma) [inline mobile/packages/profile_repository/pubspec.yaml]: We can use 3.10.0

File: mobile/lib/providers/profile_editor_notifier.dart (hunk 1 above)
Comment (omartinma) [reply mobile/lib/providers/profile_editor_notifier.dart]: +1 to this

File: mobile/packages/profile_repository/lib/src/profile_repository.dart (hunk 5 above)
Comment (Josh-Sanford) [reply mobile/packages/profile_repository/lib/src/profile_repository.dart:22]: Good point! I considered this, but in this case "not found" is actually an expected state - users can log in with their Nostr identity (keypair) without ever having published a Kind 0 profile event. The nullable return lets us handle it cleanly with `currentProfile?.nip05` without needing a try/catch for what's really a valid scenario. Does that make sense, or would you still prefer the exception?

Comment (omartinma) [reply mobile/packages/profile_repository/lib/src/profile_repository.dart:22]: Ok considering that let's keep it like, we can always come back to this later if we need to adjust

File: mobile/lib/blocs/profile_editor/profile_editor_bloc.dart [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+        nip05: nip05,
+        picture: event.picture,
+        currentProfile: currentProfile,
+      );
+      Log.info(
+        '📝 Profile published: nip05=${savedProfile.nip05}',
+        name: 'ProfileEditorBloc',
+      );
+      final appProfile = app_models.UserProfile.fromJson(savedProfile.toJson());
+      await _userProfileService.updateCachedProfile(appProfile);
```
Comment (omartinma) [inline mobile/lib/blocs/profile_editor/profile_editor_bloc.dart:69]: We might want to tackle this in different PR, but i believe we could introduce the cache into the ProfileRepository directly and remove the dependency of UserProfileService. Would you mind adding a TODO here?

Comment (Josh-Sanford) [reply mobile/lib/blocs/profile_editor/profile_editor_bloc.dart:69]: Absolutely!
