### PR TITLE
fix(video): differentiate moderation errors from missing content in video feed

### LINKED ISSUE #2427: fix: differentiate moderation errors from missing content in video feed
## Problem

When a video returns 404 from the blossom server, the app shows "Video not found" or "Failed to load video" regardless of the reason. This includes moderation-restricted content where the video exists but is blocked. 14% of videos are affected.

## Evidence

- 14% of videos return 404 due to moderation status (8% pending, 4% banned, 2% restricted)
- The feed shows ALL nostr events regardless of media availability — users see broken video entries
- `BrokenVideoTracker` marks them broken for 7 days with no automatic recovery
- `VideoModerationStatusService` already knows moderation status but is only used for badge display
- The app already handles `401` differently (shows "Age-restricted" + "Verify Age" button) — same pattern needed for `403`
- `unmarkVideoBroken()` exists but is dead code — no automatic recovery path

## Proposed fix

1. When server returns 403 (new, from divinevideo/divine-blossom#TBD): show "Content restricted" instead of "Failed to load"
2. Wire `VideoModerationStatusService` into error handling as fallback for 404s
3. Consider pre-filtering pending/restricted content from the feed before rendering

## Related

- Blossom: 403 for restricted content (divinevideo/divine-blossom issue pending)
- PR #33 (access control cleanup)
- Issue #2269 (Content Moderation epic)
- Epic #604 (Content Moderation)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary

Closes #2427

When a video returns an HTTP error from the blossom server, the app now distinguishes **moderation-restricted content** (403 Forbidden, or 404 with moderation status) from **genuinely missing content** (404 without moderation), instead of showing the same generic "Failed to load video" message for all failures.

**This targets the active pooled video player path** (home feed + all fullscreen feeds), not the legacy `individualVideoControllerProvider` path which only serves `ProfileVideoFeedView` (tracked in #2683).

- **403 Forbidden**: Shield icon + "Content restricted" — no retry button
- **404 with moderation status (blocked/quarantined)**: Shield icon + "Content restricted" — enriched via `VideoModerationStatusService`
- **404 without moderation**: Error icon + "Video not found" + Retry
- **401 Unauthorized**: Lock icon + "Age-restricted content" + Verify Age
- **Other errors**: Error icon + "Video playback error" + Retry

### pooled_video_player package
- **`VideoFeedController`**: Store error messages per index (`_errorMessages` map), pass to `_markLoadError()` and `_notifyIndex()`
- **`VideoIndexState`**: Add `errorMessage` field so the UI can inspect the raw error string
- **`ErrorBuilder` typedef**: Updated to `Widget Function(BuildContext, VoidCallback, String?)` — passes the error message to consuming screens

### App layer
- **`PooledVideoErrorOverlay`** (new widget): Classifies errors by type (401/403/404/generic), integrates `VideoModerationStatusService` for 404 enrichment, shows appropriate icon/message/action
- **`video_feed_page.dart`**: Wire `errorBuilder` into home feed `PooledVideoPlayer`
- **`pooled_fullscreen_video_feed_screen.dart`**: Wire `errorBuilder` into fullscreen feed `PooledVideoPlayer`
- **Reverted** legacy `individual_video_providers.dart` and `VideoErrorOverlay` changes (deferred to #2683)

### Tests
- 12 new tests for `PooledVideoErrorOverlay` (403 shield/message/no-retry, forbidden keyword, 401 lock/verify-age, 404 plain vs blocked vs quarantined, generic errors, null message, retry callback)
- Updated 2 existing `pooled_video_player` tests for new `ErrorBuilder` signature
- All 426 tests pass, 0 analyzer issues

## Test plan

- [ ] Verify 403 errors show shield icon + "Content restricted" with no retry button (home feed)
- [ ] Verify 404 from a divine.video URL with blocked moderation status shows "Content restricted" (home feed)
- [ ] Verify 404 from a non-divine URL still shows "Video not found" + Retry
- [ ] Verify 401 age-restricted shows lock icon + "Verify Age" button
- [ ] Verify generic errors show "Video playback error" + Retry
- [ ] Verify same behavior in fullscreen feed (explore, profile, hashtag grids)
- [ ] Run `flutter test packages/pooled_video_player/test/ test/widgets/pooled_video_error_overlay_test.dart` — all pass

## Related

- Issue #2427 (differentiate moderation errors)
- Issue #2683 (migrate ProfileVideoFeedView to pooled_video_player — follow-up)
- Epic #604 (Content Moderation)

### CODE REVIEW

File: mobile/lib/widgets/video_feed_item/video_error_overlay.dart [hunk 1]
```diff
@@ -66,6 +84,59 @@ class VideoErrorOverlay extends ConsumerWidget {
...
+    final isModerationRestricted =
+        _is403Error ||
+        (moderationStatus != null &&
+            moderationStatus.isUnavailableDueToModeration);
+
+    // Clear stale broken marking when moderation confirms restricted.
+    // Uses ref.listen instead of a direct call so the side-effect fires only
+    // on provider state changes, not on every widget rebuild.
+    if (sha256 != null && !_is401Error) {
+      ref.listen<AsyncValue<VideoModerationStatus?>>(
```
Comment (ryzizub) [inline mobile/lib/widgets/video_feed_item/video_error_overlay.dart]: On rebuilds where the condition flips, the listener alternates between registered/unregistered, risking unexpected unmarkVideoBroken side-effects. 
I think right now its better to use here ConsumerStatefulWidget.

File: mobile/lib/providers/individual_video_providers.dart
Comment (ryzizub) [inline mobile/lib/providers/individual_video_providers.dart:961]: _extractSha256FromUrl duplicates VideoModerationStatusService.extractSha256FromVideoUrl

Comment (ryzizub) [inline mobile/lib/providers/individual_video_providers.dart:957]: params.videoEvent as dynamic then .sha256 as String? bypasses type safety. Cast to VideoEvent

**Review by realmeylisdev — COMMENTED** [review]
Thanks for catching this — you're right. I traced the code paths and confirmed:

**`individualVideoControllerProvider` + `VideoErrorOverlay` are only live in `ProfileVideoFeedView`** (profile video feeds). The main home feed and all fullscreen feeds use `PooledVideoPlayer` → `VideoFeedController`, which has a completely separate error system that never touches either of these.

### What's happening in the pooled path today

- `VideoFeedController` catches errors from `player.open()` and `player.stream.error` but **only stores `LoadState.error`** — the actual error string (which does contain HTTP status codes like `'403'`, `'forbidden'`) is logged and discarded
- `ErrorBuilder` typedef is `Widget Function(BuildContext context, VoidCallback onRetry)` — no error details are passed to the UI
- Neither feed screen provides a custom `errorBuilder`, so everything falls through to `_DefaultErrorState` (generic "Failed to load video")

### Proposed fix (3 layers)

1. **`pooled_video_player` package** — Store error messages per index in `VideoFeedController`, add `errorMessage` to `VideoIndexState`, update `ErrorBuilder` typedef to include `String? errorMessage`
2. **App error overlay** — Create a pooled-path error widget that differentiates 401/403/404 using the error string + `VideoModerationStatusService` for moderation enrichment
3. **Feed screens** — Pass custom `errorBuilder` to `PooledVideoPlayer` in both `video_feed_page.dart` and `pooled_fullscreen_video_feed_screen.dart`

The existing `individual_video_providers.dart` changes could be kept for the `ProfileVideoFeedView` path (only remaining consumer), or dropped to keep the PR focused on the active path.

Does this direction make sense to you? Any concerns about touching the `pooled_video_player` package API?

File: mobile/lib/widgets/video_feed_item/video_error_overlay.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/widgets/video_feed_item/video_error_overlay.dart]: Thanks for catching this, Roman. Good call on the ConsumerStatefulWidget approach to avoid the register/unregister alternation on rebuilds. This file was reverted in the latest commit (3b33326) — the changes are deferred to #2683, where I'll incorporate this feedback.

File: mobile/lib/providers/individual_video_providers.dart
Comment (realmeylisdev) [reply mobile/lib/providers/individual_video_providers.dart:961]: Good catch — agreed, that was unnecessary duplication. This file was reverted in the latest commit (3b33326) and the changes are deferred to #2683. I'll make sure to reuse VideoModerationStatusService.extractSha256FromVideoUrl there instead of duplicating it.

Comment (realmeylisdev) [reply mobile/lib/providers/individual_video_providers.dart:957]: You're right — the dynamic cast bypasses type safety unnecessarily. This file was reverted in the latest commit (3b33326) and the changes are deferred to #2683. I'll use a proper VideoEvent cast when picking this back up. Thanks for the review\!

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart [hunk 2]
```diff
@@ -0,0 +1,153 @@
...
+    final isModerationRestricted =
+        errorType == _VideoErrorType.forbidden ||
+        (moderationStatus != null &&
+            moderationStatus.isUnavailableDueToModeration);
+
+    final icon = errorType == _VideoErrorType.ageRestricted
+        ? Icons.lock_outline
+        : isModerationRestricted
+        ? Icons.shield_outlined
+        : Icons.error_outline;
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: Can we use DivineIcon here?

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+      children: [
+        VideoThumbnailWidget(video: video),
+        ColoredBox(
+          color: VineTheme.scrim50,
+          child: Center(
+            child: Column(
+              mainAxisSize: MainAxisSize.min,
+              children: [
+                Icon(icon, color: VineTheme.whiteText, size: 48),
+                const SizedBox(height: 16),
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: Nit you can use spacing in the Column

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: Done — switched to `DivineIcon` with `DivineIconName.lockSimple`, `.shieldCheck`, and `.warningCircle`.

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart (hunk 3 above)
Comment (realmeylisdev) [reply mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: Done — using `spacing: 16` on the Column.

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+                  icon: icon,
+                  color: VineTheme.whiteText,
+                  size: 48,
+                ),
+                Text(
+                  message,
+                  style: const TextStyle(
+                    color: VineTheme.whiteText,
+                    fontSize: 14,
+                  ),
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: I think we should use a font from VineTheme

File: mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart [hunk 5]
```diff
@@ -0,0 +1,165 @@
...
+                    onPressed: onRetry,
+                    style: ElevatedButton.styleFrom(
+                      backgroundColor: VineTheme.whiteText,
+                      foregroundColor: VineTheme.backgroundColor,
+                    ),
+                    child: Text(
+                      effectiveType == _VideoErrorType.ageRestricted
+                          ? 'Verify Age'
+                          : 'Retry',
+                    ),
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/pooled_video_error_overlay.dart]: Maybe we should use DivineButton
