### PR TITLE
refactor(images): migrate ImageCacheManager to media_cache and fix is404 detection

### LINKED ISSUE #3037: refactor(images): migrate ImageCacheManager to media_cache and fix is404 detection
Auto-created from PR #3031.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3031
**Branch:** `fix/evict-failed-thumbnail-cache`

### PR DESCRIPTION
**Pull request by omartinma**
Closes #3037

## Description

Migrates the ad-hoc `ImageCacheManager` singleton to the existing `media_cache` package, which provides identical settings plus better corruption recovery and testability — eliminating 5 redundant files. Also fixes the `is404` detection in `_SafeNetworkImage` that incorrectly matched all `HttpExceptionWithStatus` errors (503, 500, etc.) instead of just 404s, suppressing their warning logs.

**Note:** During investigation we found that neither `flutter_cache_manager` (disk) nor Flutter's `ImageCache` (in-memory) actually caches failed responses — the eviction described in #2077 would be a no-op. See [comment](https://github.com/divinevideo/divine-mobile/issues/2077#issuecomment-4238629376).

**Related Issue:** #2077

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

### CODE REVIEW

File: mobile/lib/widgets/vine_cached_image.dart [hunk 1]
```diff
@@ -42,11 +53,42 @@ class VineCachedImage extends StatelessWidget {
       alignment: alignment,
       cacheManager: openVineImageCache,
       placeholder: placeholder,
-      errorWidget: errorWidget,
+      errorWidget: errorWidget != null
+          ? (context, url, error) {
+              _evictIfRetryable(url, error);
+              return errorWidget!(context, url, error);
+            }
+          : null,
```
Comment (hm21) [inline mobile/lib/widgets/vine_cached_image.dart]: If the error isn’t a 404, wouldn’t this also trigger `CachedNetworkImage.evictFromCache` on every rebuild? If so, do you think it might make sense to make this widget stateful and add a retry counter?

Comment (omartinma) [reply mobile/lib/widgets/vine_cached_image.dart]: Thanks for the review @hm21 but I just re-work this PR since I found part of the hypothesis was not 100% accurate. More details here https://github.com/divinevideo/divine-mobile/issues/2077#issuecomment-4238629376

And with that said, we might want to propose something different for other non 404 errors

**Review by hm21 — APPROVED** [review]
