### PR TITLE
fix(back_button): handle back navigation for video editing routes

### LINKED ISSUE #1675: fix(android-navigation): back button skips navigation stack during video recording/editing
### Description

When users press the Android system back button while recording or editing videos, the app immediately navigates back to the notifications screen instead of following the expected navigation stack.

This causes intermediate routes to be skipped and interrupts the user workflow.

---

### Current Behavior

Pressing the Android back button jumps directly to the notifications screen, even when multiple routes exist in between.

Example:

Metadata Screen → (Back) → Notifications Screen ❌

---

### Expected Behavior

The Android back button should respect the navigation stack and return users step-by-step through previous routes.

Example:

Metadata Screen  
→ Clips Editor  
→ Video Recorder  
→ Home  

Users should always return to the previous screen in the correct order.

---

### Impact

- Breaks expected Android navigation behavior.
- Confusing user experience during recording and editing.

---

### Platforms

- Android

### PR DESCRIPTION
**Pull request by hm21**
## Description

This PR fixes an issue where pressing the Android system back button during video recording or editing would immediately navigate users back to the notifications screen instead of respecting the navigation stack.

**NOTE** In the future we should add e2e-tests covering the complete navigation flow including back navigation behavior across all routes. 

**Related Issue:** Closes #1675
 
## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/services/back_button_handler.dart [hunk 1]
```diff
@@ -55,6 +55,13 @@ class BackButtonHandler {
         // Go back to explore
         _router!.go(ExploreScreen.path);
         return true; // Handled
+      case RouteType.videoRecorder:
+      case RouteType.videoClipEditor:
```
Comment (Josh-Sanford) [inline mobile/lib/services/back_button_handler.dart:59]: I noticed this isn't in the `tabIndexFromLocation` list in app_router.dart. Should work fine since it'll go to the default case, but just wanted to note that!
