### PR TITLE
fix: banner email verification

### LINKED ISSUE #408: [TC-AUTH-023] Account creation with existing nsec
## Test Case: TC-AUTH-023

**Section:** 1. Authentication & Login
**Feature:** 1.5 Keycast
**Priority:** P0
**Status:** Not Tested
**Size:** M
**Estimate:** 2 days
**Release:** MVP Rel 1

### Test Steps
User has existing nsec
Create Keycast account
Verify option to import current session (upload nsec to server)
Verify can switch to using Keycast OR keep nsec locally with server backup for account recovery

---
*Imported from QA Test Case Tracker*

### PR DESCRIPTION
**Pull request by calevgian100**
## Description

The banner in settings screen that asks for email validation still appears when adding an email. 
Also, when opening the app after validating the email, the app would stop polling and no navigation was visible.

Now, after validating the email and going back into the app, the polling continues and correctly checks that the email is validated, navigating back to the home screen.

https://github.com/user-attachments/assets/3e7360b6-8273-485e-933e-dc3f592dc568

**Related Issue:** Closes #408 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/main.dart [hunk 1]
```diff
@@ -1072,10 +1073,20 @@ class _DivineAppState extends ConsumerState<DivineApp> {
...
-      )..add(const CameraPermissionRefresh()),
+    Widget wrapped = MultiBlocProvider(
+      providers: [
+        BlocProvider(
+          create: (_) => CameraPermissionBloc(
+            permissionsService: const PermissionHandlerPermissionsService(),
+          )..add(const CameraPermissionRefresh()),
+        ),
+        BlocProvider(
+          create: (_) => EmailVerificationCubit(
```
Comment (Josh-Sanford) [inline mobile/lib/main.dart:1077]: Should this global cubit replace the local one in email_verification_screen.dart:66?

File: mobile/lib/screens/auth/secure_account_screen.dart [hunk 2]
```diff
@@ -111,21 +130,57 @@ class _SecureAccountScreenState extends ConsumerState<SecureAccountScreen> {
...
+      ),
+    );
+  }
+
+  void _continueToApp() {
+    // User can use the app while waiting for verification
+    // The polling continues in the background
+    // Navigate to home
+    if (mounted) {
+      context.go('/home/0');
```
Comment (Josh-Sanford) [inline mobile/lib/screens/auth/secure_account_screen.dart:180]: What happens if the user leaves the dialog but never finishes verifying their email, or there's an error? Is there some way they will know, or should we maybe add a global listener or show something on the banner?

File: mobile/lib/main.dart (hunk 1 above)
Comment (calevgian100) [reply mobile/lib/main.dart:1077]: Oh, this may be here because of some conflicts I solved before. Will work on a fix shortly.

File: mobile/lib/screens/auth/secure_account_screen.dart (hunk 2 above)
Comment (calevgian100) [reply mobile/lib/screens/auth/secure_account_screen.dart:180]: Good call. I'll create a listener and also a banner with a spinner so the user knows it's still waiting to be verified. Will share an update in a bit.

Comment (calevgian100) [reply mobile/lib/screens/auth/secure_account_screen.dart:180]: Added a spinner and error handling for when it fails. 

https://github.com/user-attachments/assets/18b44dd4-1def-4b18-88d4-39786c1b0b23
