### PR TITLE
fix: avoid overwriting newer profiles with stale data

### LINKED ISSUE #2929: fix: Bio
### Summary

----------------------------------------------

JustJed, 9 Apr 2026, 14:43

Bio

Bio will not save.

App Version: 1.0.8+624

### Steps to Reproduce
1. Go to edit profile
2. Insert bio
3. Save

### Expected Behavior
Bio should save after editing profile.

### Device Information
- **platform:** ios
- **model:** iPhone
- **systemName:** iOS
- **systemVersion:** 26.3.1
- **name:** iPhone

**Current Screen:** SupportCenterScreen
**User Pubkey:** 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a

### Recent Logs (errors/warnings + recent context)
```
[2026-04-08T16:41:30.526354] [WARNING] [VIDEO] (VideoEventService) Cannot subscribe - Nostr service not initialized (will retry when ready)
[2026-04-08T16:41:30.792178] [WARNING] [SYSTEM] Zendesk JWT: SDK not initialized
[2026-04-08T16:41:31.844203] [WARNING] [AUTH] (RelayDiscoveryService) ⚠️ No relay list found for npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp on any indexer
[2026-04-08T16:41:31.844221] [WARNING] [AUTH] (AuthService) ⚠️ No relay list found for user on any indexer
[2026-04-08T16:41:37.353062] [WARNING] [VIDEO] (VideoEventService) Default video system is disabled - users will see real content only
[2026-04-08T16:41:46.517935] [DEBUG] [UI] (AppRouter) /edit-profile route builder called
[2026-04-08T16:41:46.517936] [DEBUG] [UI] (AppRouter) /edit-profile state.uri = /edit-profile
[2026-04-08T16:41:46.517937] [DEBUG] [UI] (AppRouter) /edit-profile state.matchedLocation = /edit-profile
[2026-04-08T16:41:46.517941] [DEBUG] [UI] (AppRouter) /edit-profile state.fullPath = /edit-profile
[2026-04-08T16:41:46.537879] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:46.542990] [INFO] (ScreenAnalytics) ✅ Screen content visible: edit-profile in 25ms
[2026-04-08T16:41:46.543017] [INFO] (PagePerf) PERF: edit-profile — visible: 25ms
[2026-04-08T16:41:47.017545] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:47.018607] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.844971] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.profile npub=npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp index=null
[2026-04-08T16:41:55.845087] [DEBUG] [UI] (PageLoadObserver) Page pop tracked: edit-profile
[2026-04-08T16:41:55.845411] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/profile/npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp, authState=authenticated
[2026-04-08T16:41:55.846330] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Resuming auto-refresh timer
[2026-04-08T16:41:55.849842] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.851646] [INFO] [VIDEO] (VideoControllerCleanup) 🧹 Route type changed (RouteType.editProfile → RouteType.profile), disposing all video controllers
[2026-04-08T16:41:55.851648] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:55.872905] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:55.873426] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.874675] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Resuming auto-refresh timer
[2026-04-08T16:41:55.877734] [DEBUG] [VIDEO] (GridPrefetch) Prefetching 4 grid videos
[2026-04-08T16:41:55.878948] [DEBUG] [SYSTEM] (SocialService) Fetching follower stats for: 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a
[2026-04-08T16:41:55.878957] [DEBUG] [SYSTEM] (SocialService) 📱 Using cached follower stats: {followers: 2, following: 4}
[2026-04-08T16:41:57.015661] [DEBUG] [SYSTEM] (FollowRepository) Indexer follower pubkeys: 2 for 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a
[2026-04-08T16:41:57.015684] [INFO] [SYSTEM] (FollowRepository) Followers for 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a: API=2, relays=2, indexers=2, merged=2
[2026-04-08T16:41:57.219621] [INFO] [UI] (Navigation) User tapped settings gear
[2026-04-08T16:41:57.219753] [INFO] [UI] (OverlayVisibility) Page opened
[2026-04-08T16:41:57.219968] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/settings, authState=authenticated
[2026-04-08T16:41:57.220144] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.settings npub=null index=null
[2026-04-08T16:41:57.220169] [INFO] [VIDEO] (VideoControllerCleanup) 🧹 Route type changed (RouteType.profile → RouteType.settings), disposing all video controllers
[2026-04-08T16:41:57.220170] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:57.220470] [INFO] (ScreenAnalytics) 📱 Screen load started: settings
[2026-04-08T16:41:57.220472] [DEBUG] [UI] (PageLoadObserver) Page push tracked: settings
[2026-04-08T16:41:57.220617] [DEBUG] [VIDEO] (VideoControllerCleanup) 🛡️ Skipping duplicate invalidation (0ms since last)
[2026-04-08T16:41:57.220619] [INFO] [SYSTEM] (VideoStopNavigatorObserver) 📱 Navigation didPush to route: settings - stopped all videos
[2026-04-08T16:41:57.225293] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:57.239667] [INFO] (ScreenAnalytics) ✅ Screen content visible: settings in 19ms
[2026-04-08T16:41:57.239712] [INFO] (PagePerf) PERF: settings — visible: 19ms
[2026-04-08T16:41:57.240254] [INFO] [AUTH] (AuthService) getKnownAccounts: raw=190 chars
[2026-04-08T16:41:57.719305] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:57.720278] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:58.603202] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/support-center, authState=authenticated
[2026-04-08T16:41:58.603311] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.supportCenter npub=null index=null
[2026-04-08T16:41:58.610726] [INFO] (ScreenAnalytics) 📱 Screen load started: support-center
[2026-04-08T16:41:58.610727] [DEBUG] [UI] (PageLoadObserver) Page push tracked: support-center
[2026-04-08T16:41:58.610847] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:58.610852] [INFO] [SYSTEM] (VideoStopNavigatorObserver) 📱 Navigation didPush to route: support-center - stopped all videos
[2026-04-08T16:41:58.619996] [INFO] (ScreenAnalytics) ✅ Screen content visible: support-center in 9ms
[2026-04-08T16:41:58.620026] [INFO] (PagePerf) PERF: support-center — visible: 9ms
[2026-04-08T16:42:00.437278] [DEBUG] [SYSTEM] (VideoStopNavigatorObserver) 📱 Skipping video disposal for popup route: null
[2026-04-08T16:43:16.575805] [INFO] [SYSTEM] Collecting bug report diagnostics
```

### Environment

**Platform:** 
**Build Number:** 
**OS Version:** 

### Steps to Reproduce

1. Go to edit profile
2. Insert bio
3. Save

### Actual Result

----------------------------------------------

JustJed, 9 Apr 2026, 14:43

Bio

Bio will not save.

App Version: 1.0.8+624

### Steps to Reproduce
1. Go to edit profile
2. Insert bio
3. Save

### Expected Behavior
Bio should save after editing profile.

### Device Information
- **platform:** ios
- **model:** iPhone
- **systemName:** iOS
- **systemVersion:** 26.3.1
- **name:** iPhone

**Current Screen:** SupportCenterScreen
**User Pubkey:** 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a

### Recent Logs (errors/warnings + recent context)
```
[2026-04-08T16:41:30.526354] [WARNING] [VIDEO] (VideoEventService) Cannot subscribe - Nostr service not initialized (will retry when ready)
[2026-04-08T16:41:30.792178] [WARNING] [SYSTEM] Zendesk JWT: SDK not initialized
[2026-04-08T16:41:31.844203] [WARNING] [AUTH] (RelayDiscoveryService) ⚠️ No relay list found for npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp on any indexer
[2026-04-08T16:41:31.844221] [WARNING] [AUTH] (AuthService) ⚠️ No relay list found for user on any indexer
[2026-04-08T16:41:37.353062] [WARNING] [VIDEO] (VideoEventService) Default video system is disabled - users will see real content only
[2026-04-08T16:41:46.517935] [DEBUG] [UI] (AppRouter) /edit-profile route builder called
[2026-04-08T16:41:46.517936] [DEBUG] [UI] (AppRouter) /edit-profile state.uri = /edit-profile
[2026-04-08T16:41:46.517937] [DEBUG] [UI] (AppRouter) /edit-profile state.matchedLocation = /edit-profile
[2026-04-08T16:41:46.517941] [DEBUG] [UI] (AppRouter) /edit-profile state.fullPath = /edit-profile
[2026-04-08T16:41:46.537879] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:46.542990] [INFO] (ScreenAnalytics) ✅ Screen content visible: edit-profile in 25ms
[2026-04-08T16:41:46.543017] [INFO] (PagePerf) PERF: edit-profile — visible: 25ms
[2026-04-08T16:41:47.017545] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:47.018607] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.844971] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.profile npub=npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp index=null
[2026-04-08T16:41:55.845087] [DEBUG] [UI] (PageLoadObserver) Page pop tracked: edit-profile
[2026-04-08T16:41:55.845411] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/profile/npub1ravaujhznaph2kvr2jy0zadu4su087lwtzvxz78qz5a8sk6e55dqfv6ydp, authState=authenticated
[2026-04-08T16:41:55.846330] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Resuming auto-refresh timer
[2026-04-08T16:41:55.849842] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.851646] [INFO] [VIDEO] (VideoControllerCleanup) 🧹 Route type changed (RouteType.editProfile → RouteType.profile), disposing all video controllers
[2026-04-08T16:41:55.851648] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:55.872905] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:55.873426] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:55.874675] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Resuming auto-refresh timer
[2026-04-08T16:41:55.877734] [DEBUG] [VIDEO] (GridPrefetch) Prefetching 4 grid videos
[2026-04-08T16:41:55.878948] [DEBUG] [SYSTEM] (SocialService) Fetching follower stats for: 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a
[2026-04-08T16:41:55.878957] [DEBUG] [SYSTEM] (SocialService) 📱 Using cached follower stats: {followers: 2, following: 4}
[2026-04-08T16:41:57.015661] [DEBUG] [SYSTEM] (FollowRepository) Indexer follower pubkeys: 2 for 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a
[2026-04-08T16:41:57.015684] [INFO] [SYSTEM] (FollowRepository) Followers for 1f59de4ae29f437559835488f175bcac38f3fbee58986178e0153a785b59a51a: API=2, relays=2, indexers=2, merged=2
[2026-04-08T16:41:57.219621] [INFO] [UI] (Navigation) User tapped settings gear
[2026-04-08T16:41:57.219753] [INFO] [UI] (OverlayVisibility) Page opened
[2026-04-08T16:41:57.219968] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/settings, authState=authenticated
[2026-04-08T16:41:57.220144] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.settings npub=null index=null
[2026-04-08T16:41:57.220169] [INFO] [VIDEO] (VideoControllerCleanup) 🧹 Route type changed (RouteType.profile → RouteType.settings), disposing all video controllers
[2026-04-08T16:41:57.220170] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:57.220470] [INFO] (ScreenAnalytics) 📱 Screen load started: settings
[2026-04-08T16:41:57.220472] [DEBUG] [UI] (PageLoadObserver) Page push tracked: settings
[2026-04-08T16:41:57.220617] [DEBUG] [VIDEO] (VideoControllerCleanup) 🛡️ Skipping duplicate invalidation (0ms since last)
[2026-04-08T16:41:57.220619] [INFO] [SYSTEM] (VideoStopNavigatorObserver) 📱 Navigation didPush to route: settings - stopped all videos
[2026-04-08T16:41:57.225293] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:57.239667] [INFO] (ScreenAnalytics) ✅ Screen content visible: settings in 19ms
[2026-04-08T16:41:57.239712] [INFO] (PagePerf) PERF: settings — visible: 19ms
[2026-04-08T16:41:57.240254] [INFO] [AUTH] (AuthService) getKnownAccounts: raw=190 chars
[2026-04-08T16:41:57.719305] [DEBUG] [SYSTEM] (RelayNotificationsProvider) RelayNotifications: Pausing auto-refresh timer (no listeners)
[2026-04-08T16:41:57.720278] [INFO] (ProfileScreenRouter) 🧭 ProfileScreenRouter.build
[2026-04-08T16:41:58.603202] [DEBUG] [AUTH] (AppRouter) Router redirect: location=/support-center, authState=authenticated
[2026-04-08T16:41:58.603311] [INFO] [SYSTEM] (Route) CTX derive: type=RouteType.supportCenter npub=null index=null
[2026-04-08T16:41:58.610726] [INFO] (ScreenAnalytics) 📱 Screen load started: support-center
[2026-04-08T16:41:58.610727] [DEBUG] [UI] (PageLoadObserver) Page push tracked: support-center
[2026-04-08T16:41:58.610847] [DEBUG] [VIDEO] (VideoControllerCleanup) 🧹 Invalidating all video controllers
[2026-04-08T16:41:58.610852] [INFO] [SYSTEM] (VideoStopNavigatorObserver) 📱 Navigation didPush to route: support-center - stopped all videos
[2026-04-08T16:41:58.619996] [INFO] (ScreenAnalytics) ✅ Screen content visible: support-center in 9ms
[2026-04-08T16:41:58.620026] [INFO] (PagePerf) PERF: support-center — visible: 9ms
[2026-04-08T16:42:00.437278] [DEBUG] [SYSTEM] (VideoStopNavigatorObserver) 📱 Skipping video disposal for popup route: null
[2026-04-08T16:43:16.575805] [INFO] [SYSTEM] Collecting bug report diagnostics
```

### Expected Result

Bio should save after editing profile.

(Generated from Zendesk Ticket: rabblelabs.zendesk.com/agent/tickets/988)

### PR DESCRIPTION
**Pull request by untreu2**
## Description
Prevent Funnelcake-cached profiles from overwriting a newer locally-saved profile by checking the local DAO first and only caching when no local profile exists. Improve indexer relay fallback: request up to 5 kind-0 events and pick the event with the highest createdAt timestamp (relays may not return newest-first). Add tests covering the regression where a stale Funnelcake or older indexer event could overwrite a freshly saved bio.

**Related Issue:** Closes #2929 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by NotThatKindOfDrLiz — CHANGES_REQUESTED** [review]
Thanks for the focused fix and the tests. The indexer-relay part looks right to me: requesting a small batch and selecting the highest `createdAt` handles unordered relay responses without trusting list order.

I do think the Funnelcake branch needs one more adjustment before merge. The current change prevents stale Funnelcake data from overwriting a newer local profile, but it also returns the existing local profile immediately whenever Funnelcake returns a profile and local data exists. That means `fetchFreshProfile` no longer falls through to connected/indexer relays in that case, so a stale local profile can remain stale even if a newer Kind 0 is available on relays.

Since `UserProfileData.fromJson` currently ignores `created_at`, and `UserProfile.fromUserProfileFound` uses `DateTime.now()`, we do not currently have a trustworthy Funnelcake event timestamp to compare. If Funnelcake’s `created_at` is confirmed to be the original Kind 0 timestamp, then modeling it and comparing timestamps would be ideal.

If not, I think the safer behavior is:
- skip the Funnelcake profile upsert when a local profile already exists
- still cache Funnelcake stats
- continue to the relay/indexer fetch path instead of returning the existing profile immediately
- return/cache the relay/indexer profile if found
- only return the existing local profile as a fallback if relay/indexer lookup finds nothing

That keeps the regression fix without changing `fetchFreshProfile` into “return cached profile whenever Funnelcake has any profile.”

**Comment by untreu2** [comment]
Thanks for review @NotThatKindOfDrLiz, I updated the logic:

- Skip the upsert when a local profile already exists (protects the freshly-saved bio)
- Still cache Funnelcake stats
- Fall through to the relay/indexer path instead of returning early -- a newer Kind 0 on relays can still win
- Return the existing local profile as a fallback if relay/indexer finds nothing, rather than returning null

File: mobile/packages/profile_repository/lib/src/profile_repository.dart [hunk 1]
```diff
@@ -277,11 +277,26 @@ class ProfileRepository {
...
+            final funnelcakeProfile = UserProfile.fromUserProfileFound(result);
+            // Funnelcake profiles use DateTime.now() as a synthetic
+            // createdAt (the REST API does not expose the Nostr event
+            // timestamp), so _cacheProfileIfNewer cannot reliably guard
+            // against overwriting a freshly-saved bio. Only write to
+            // cache when no local profile exists yet; otherwise fall
+            // through to the relay/indexer path so a newer Kind 0 on
+            // relays can still upgrade the cache.
+            final existing = await _userProfilesDao.getProfile(pubkey);
+            if (existing == null) {
```
Comment (NotThatKindOfDrLiz) [inline mobile/packages/profile_repository/lib/src/profile_repository.dart:289]: This addresses the core overwrite bug: Funnelcake's synthetic timestamp cannot safely participate in newest-wins, so only using it to seed an empty cache protects freshly saved local profile data.

File: mobile/packages/profile_repository/lib/src/profile_repository.dart [hunk 2]
```diff
@@ -303,12 +318,18 @@ class ProfileRepository {
...
-    if (profile != null) {
-      await _cacheProfileIfNewer(profile);
-      return profile;
+    final relayProfile = await _fetchFromRelaysParallel(pubkey);
+    if (relayProfile != null) {
+      await _cacheProfileIfNewer(relayProfile);
+      return relayProfile;
     }
 
+    // Relay/indexer found nothing. If a local profile already exists
```
Comment (NotThatKindOfDrLiz) [inline mobile/packages/profile_repository/lib/src/profile_repository.dart:327]: Good fallback ordering. Relay/indexer gets the chance to return a real kind-0 first, and the existing local profile is only returned after those sources find nothing.

File: mobile/packages/profile_repository/test/src/profile_repository_test.dart [hunk 3]
```diff
@@ -671,6 +671,66 @@ void main() {
...
+              (_) async => UserProfileFound(
+                profile: UserProfileData.fromJson(testPubkey, const {
+                  'display_name': 'Test User',
+                  'about': '', // stale — bio not yet indexed by Funnelcake
+                  'created_at': olderTimestamp,
+                }),
+              ),
+            );
+
+            await repoWithFunnelcake.fetchFreshProfile(pubkey: testPubkey);
```
Comment (NotThatKindOfDrLiz) [inline mobile/packages/profile_repository/test/src/profile_repository_test.dart]: Non-blocking: this regression test proves the stale Funnelcake write does not happen. It would be even stronger if it also asserted the return value and verified the relay path was invoked, so a future refactor cannot accidentally turn the `break` back into an early return while keeping this test green.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
Approved. The update addresses the stale-profile overwrite concern cleanly.

The Funnelcake path now avoids writing synthetic-timestamp profile data over an existing local profile, still caches stats, falls through to relay/indexer lookup, and only returns the local profile as a final fallback when relays find nothing. The indexer path also now chooses the newest kind-0 event instead of trusting relay result order.

CI is green. The one test-strengthening note I left is non-blocking.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
Looks good to merge. The latest changes address the Funnelcake stale-profile overwrite path while preserving relay/indexer fallback behavior, and the added regression tests cover both the Funnelcake fallback case and unordered indexer results.

I’m going to track the remaining timestamp-modeling improvement separately rather than blocking this PR.
