### PR TITLE
fix(clip-library): update border-radius in masonry grid for video clips

### LINKED ISSUE #3669: fix(clip-library): update border-radius in masonry grid for video clips
Auto-created from PR #3668.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3668
**Branch:** `fix/library-clipper`

### PR DESCRIPTION
**Pull request by hm21**
Closes #3669

## Description

Previously, the border radius in the clip library was inconsistent compared to the other tabs. In the other tabs, the border radius stays visible while scrolling, but in the clip library it disappeared because it was only applied to the first clip. The radius is now applied consistently and only when there are at least three clips in the library.

**Related Issue:** Closes # or Relates to #

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/widgets/library/clips_tab.dart [hunk 1]
```diff
@@ -247,47 +247,46 @@ class _MasonryLayout extends StatelessWidget {
...
-          ),
-        );
-      },
+    return Padding(
+      padding: const .symmetric(horizontal: 8),
+      child: ClipRRect(
+        borderRadius: clips.length >= _columnCount
+            ? const .vertical(top: _radius)
+            : .zero,
+        clipBehavior: .hardEdge,
```
Comment (realmeylisdev) [inline mobile/lib/widgets/library/clips_tab.dart]: Nit: this is the only `shellInnerCornerRadius` surface in `mobile/lib/` that uses `Clip.hardEdge` — `notifications_screen.dart:123` and `explore_screen.dart:462` both use the `ClipRRect` default (`Clip.antiAlias`). On a 32px radius the aliasing is visible against video content.

If this is a deliberate perf choice (avoid an offscreen pass on a scrolling video grid), worth a one-line comment so the choice survives a future "align with siblings" cleanup. Otherwise dropping it back to the default would match precedent.

File: mobile/lib/widgets/library/clips_tab.dart [hunk 2]
```diff
@@ -247,47 +247,46 @@ class _MasonryLayout extends StatelessWidget {
...
-            onLongPress: () => onLongPressClip(clip),
-          ),
-        );
-      },
+    return Padding(
+      padding: const .symmetric(horizontal: 8),
+      child: ClipRRect(
+        borderRadius: clips.length >= _columnCount
+            ? const .vertical(top: _radius)
+            : .zero,
```
Comment (realmeylisdev) [inline mobile/lib/widgets/library/clips_tab.dart:263]: Question: what's the design reason for gating the rounding on `clips.length >= _columnCount`?

Before this PR, with 1 or 2 clips the existing items were still individually rounded (item 0 → top-left, last-in-first-row → top-right). After this PR, the partial-row case is fully square — slightly less polished than before for the 1–2 clip state.

If the design wants no rounding below a full top row, fine — but dropping the gate would also work visually: with 1 clip only column-0 has content to clip, and the empty column-1/2 region rounds nothing visible; same for 2 clips on the right. Either way, if the gate stays please add a one-line comment with the rationale so it doesn't get "fixed" back later.

(Also: when this branch evaluates to `BorderRadius.zero`, the `ClipRRect` is still constructed and paid for — if the gate stays, conditionally wrapping the grid in `ClipRRect` only when `clips.length >= _columnCount` sidesteps that.)

**Review by realmeylisdev — APPROVED** [review]
LGTM — fix is correct and on-pattern with `notifications_screen.dart:123` / `explore_screen.dart:462`. Two non-blocking observations inline.

One thing not on the diff: this PR's whole purpose is the visual contract for the rounded shell, but `test/widgets/library/clips_tab_test.dart` doesn't pin it. A regression test that asserts the wrapping `ClipRRect.borderRadius` is `BorderRadius.vertical(top: ...)` for 3+ clips and `BorderRadius.zero` below would lock in both the fix and the threshold from the inline question. Cheap to add — happy to do it as a follow-up if you'd rather keep this PR scoped.

Also worth a rebase before merge — branch is 3 commits behind `origin/main` (none touch this file).

File: mobile/lib/widgets/library/clips_tab.dart (hunk 2 above)
Comment (hm21) [reply mobile/lib/widgets/library/clips_tab.dart:263]: That's a really good question, and you're right; it's a bit special here. The goal is to follow the same design as in the notifications or DMs, where it is rounded on the top and bottom. However, the design for the Library is not complete yet. For example, there is a Sounds tab without any design. The final goal is to apply this cliprect to everything, but for now, we're only applying it to the clips tab. We have part of the design, but it's not complete. I will update this directly once the design is finished. For now, we will just apply the minimum border radius above when the first row is filled.

File: mobile/lib/widgets/library/clips_tab.dart (hunk 1 above)
Comment (hm21) [reply mobile/lib/widgets/library/clips_tab.dart]: Good catch was not necessary in this case anymore
