### PR TITLE
fix(social): track downvotes in LikesRepository; drop voteInProgressCommentId

### LINKED ISSUE #3432: fix(social): comment downvote-removal flashes; downvote not crash-resilient
## Summary

Comment **upvote** already feels instant (post-#3409 the bloc emits optimistically before the await). Two related gaps remain on the **downvote** side that this issue tracks:

1. Removing a downvote produces a brief revert flash (arrow grey → red).
2. Downvotes aren't tracked locally, so they can't survive an in-flight publish failure the way upvotes do.

Reported as Alice's follow-up: "Is the upvote working more quickly too?" — the answer to that is yes today, but tapping the down-arrow on an already-downvoted comment exposes the latent bug below.

## Environment

- App: latest `main` (post #3409 / `822c559b8`).
- Device: any (cross-platform Flutter UI in the Comments sheet).
- Network: latent bug reproduces on any connection; flash duration scales with relay RTT.

### Bug A — Downvote removal flashes

1. Open a video, expand the Comments sheet.
2. Pick any comment. Note its net score.
3. Tap the down-arrow once. Arrow turns red, count decrements.
4. Tap the down-arrow again to remove the downvote.

### Bug B — Vote-switch from downvote to upvote flashes

1. Downvote a comment (steps 1–3 above).
2. Tap the up-arrow.

## Actual result

**Bug A:** down-arrow flashes grey for a fraction of a second, then **flips back to red** before settling. Net score also bounces.

**Bug B:** down-arrow goes grey AND up-arrow goes green optimistically, then both **flash back** to red / grey before settling.

## Expected result

**Bug A:** down-arrow goes grey, count decrements, settled in the same frame. No bounce. (Should look identical to removing an upvote.)

**Bug B:** down-arrow goes grey, up-arrow goes green, count moves by +2, settled in the same frame.

## Regression?

No — pre-existing since the comment-vote feature shipped. `voteInProgressCommentId` partially masked it by blocking same-comment double-taps during the in-flight handler, but the revert flash on the first attempt is always visible.

## Root cause

`mobile/packages/likes_repository/lib/src/likes_repository.dart`:

- `_likeRecords` (line 88) tracks **only upvotes** — written by `likeEvent` (line 220), never by `downvoteEvent` (line ~785, just publishes the kind-7 with content `-`, no record).
- `unlikeEvent` (line ~319) requires the reaction to be in `_likeRecords`. For a comment the user only downvoted, that map has no entry, so `unlikeEvent` throws `NotLikedException` immediately on the optimistic-remove path.

`mobile/lib/blocs/comments/comments_bloc.dart`:

- `_onVoteToggled` calls `_likesRepository.unlikeEvent(commentId)` to remove a downvote (line ~573) and to undo the previous downvote when switching to upvote (line ~578). Both paths hit the bug above. The bloc catches the throw and reverts the optimistic update — that's the visible flash.

Secondary: `downvoteEvent` itself isn't optimistic-first like `likeEvent` post-#3409, so a publish failure mid-tap loses the optimistic state without a clean rollback path.

## Proposed fix

Three layers, all in one PR:

1. **LikesRepository:** add a parallel `_downvoteRecords` map (mirror of `_likeRecords`), `watchDownvotedEventIds` stream, `isDownvoted` / `getDownvoteRecord`, and `removeDownvote` / `toggleDownvote` methods. Refactor `downvoteEvent` to write the record + tick the stream BEFORE the kind-7 publish, with rollback on failure (mirror of `likeEvent` post-#3409). New `AlreadyDownvotedException` / `NotDownvotedException` pair.
2. **CommentsBloc:** route the downvote-removal and vote-switch paths through `removeDownvote` (when the existing vote is a downvote) instead of `unlikeEvent`. Drop the redundant `voteInProgressCommentId` guard — the existing `droppable()` transformer already covers same-event-type rapid taps. Catch the new exceptions to sync state with the repo without surfacing `voteFailed`.
3. **CommentsState:** drop `voteInProgressCommentId` field, ctor param, copyWith param, props entry, dartdoc.

`syncUserReactions` and `_processIncomingReaction` are extended to route kind-7 events into the right map by content (`+` vs `-`), so cross-device downvote sync works for the first time.

## Out of scope (separate follow-up)

**Local persistence for downvotes.** v1 keeps downvote state in-memory only. The next `getVoteCounts` call repopulates from relays, so the reload path still works, but a force-close mid-publish loses the optimistic record. Adding a schema migration in `db_client` to mirror what `DbLikesLocalStorage` does for upvotes is the cleanest fix; tracked separately to keep this PR's blast radius contained.

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Description

Closes #3432.

Comments already had an optimistic emit at the bloc level (post-#3409), so upvote felt fast. This PR closes the remaining gaps in the Follow-pattern series for the comment-vote row.

### What changed

**`LikesRepository` (Phase 1 of the Follow pattern, applied to downvotes):**
- New `_downvoteRecords` map and `_downvotedIdsController` mirror the existing upvote machinery.
- New public API: `watchDownvotedEventIds`, `isDownvoted`, `getDownvoteRecord`, `getDownvotedEventIds`, `getOrderedDownvotedEventIds`, `removeDownvote`, `toggleDownvote`.
- `downvoteEvent` is now optimistic-first: writes the record + ticks `watchDownvotedEventIds` BEFORE the kind-7 publish, with rollback on failure (mirror of `likeEvent`'s structure post-#3409).
- `_processIncomingReaction` now routes incoming kind-7 events into the right map by content (`+` → `_likeRecords`, `-` → `_downvoteRecords`). `syncUserReactions` does the same and respects kind-5 deletions for both sides — so cross-device downvote sync works for the first time.
- New `AlreadyDownvotedException` / `NotDownvotedException` pair.

**`CommentsBloc._onVoteToggled`:**
- Drops the per-comment `voteInProgressCommentId` guard. The optimistic emit + `droppable()` transformer already cover same-comment rapid taps; the per-comment guard was redundant.
- Routes downvote-removal through new `removeDownvote` (was `unlikeEvent`). This closes the latent revert-flash bug — pre-fix, removing a downvote called `unlikeEvent` on a comment that had no `_likeRecord` entry, threw `NotLikedException`, and the optimistic update reverted with a visible flash. Same fix lands the downvote→upvote vote-switch path.
- Catches `AlreadyLikedException` / `NotLikedException` / `AlreadyDownvotedException` / `NotDownvotedException` explicitly to sync state with the repo without surfacing `voteFailed`.

**`CommentsState`:** drops `voteInProgressCommentId` field, ctor param, copyWith param, props entry, dartdoc.

### Out of scope (separate follow-up)

- **Local persistence for downvotes:** v1 keeps downvote state in-memory only; the next `getVoteCounts` call repopulates from relays. Adding a schema migration in `db_client` to mirror `DbLikesLocalStorage` for downvotes is the cleanest fix — tracked separately to keep this PR's blast radius contained.

**Related Issue:** Closes #3432

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

---

## Manual test plan

Test on a real device. Throttle to 3G for the diagnostic tests — the latent bug is most visible there.

### 1. Upvote arrow + count flip together

1. Find a comment with a known net score. Tap up-arrow.

**Pass:** arrow flips green and net score increments **in the same frame**. Tap again to remove → grey + decrement together.

### 2. Downvote arrow + count flip together

1. Tap down-arrow on a comment.

**Pass:** arrow flips red and net score decrements **in the same frame**.

### 3. Remove a downvote (the previously-broken path)

1. Downvote a comment (Test 2). Arrow red.
2. Tap the down-arrow again to remove.

**Pass:** arrow goes grey, count returns to baseline, **same frame**. No revert flash.
**Fail (pre-fix):** arrow flashes grey then back to red. This is the diagnostic test — pre-fix this reproduces reliably.

### 4. Slow network (3G throttled) on Tests 1–3

Repeat with throttling. **Pass:** UI feels identical to a healthy network.

### 5a. Vote switch — upvote → downvote

1. Upvote a comment. Tap down-arrow.

**Pass:** up-arrow goes grey, down-arrow turns red, net score moves by **-2** in the same frame.

### 5b. Vote switch — downvote → upvote (also previously broken)

1. Downvote a comment. Tap up-arrow.

**Pass:** down-arrow goes grey, up-arrow turns green, net score moves by **+2** in the same frame.
**Fail (pre-fix):** both arrows flash and revert.

### 6. Same-comment rapid double-tap

Tap the same up-arrow twice as fast as you can.

**Pass:** net effect is one state change (upvoted, count +1). The second tap is dropped by the `droppable()` transformer.

### 7. Different-comment rapid taps

Quickly upvote three different comments in a row.

**Pass:** all three upvotes land. Caveat: with `droppable` active, very rapid taps faster than network RTT can drop some — known trade-off.

### 8. Crash-resilience for downvotes (NEW, in-session only)

1. Throttle to 3G. Downvote a comment. Immediately background the app (not force-close).
2. Re-foreground within ~10s.

**Pass:** down-arrow still red. The optimistic record persisted across backgrounding.

**Note:** v1 doesn't persist downvotes across app restart (deferred follow-up). Force-close + reopen will lose the downvote.

### 9. Failure rollback (best-effort)

Block relays via Charles/Proxyman returning 503. Tap upvote / downvote.

**Pass:** UI flips optimistically, then within ~30s rolls back to the pre-tap state.

### 10. Cross-device sync

1. Upvote a comment on Device A → up-arrow on Device B turns green within ~10s.
2. Downvote a comment on Device A → down-arrow on Device B turns red within ~10s. **NEW** — pre-fix, downvotes never synced because `_processIncomingReaction` filtered them out.

Known limitation (pre-existing): the **count** on Device B may not increment until the bloc re-fetches via `getVoteCounts`. Shared with likes/reposts.

### Sign-off

- [ ] Test 1 — upvote feels instant
- [ ] Test 2 — downvote feels instant
- [ ] Test 3 — **remove a downvote: no revert flash** (diagnostic)
- [ ] Test 4 — Tests 1, 2, 3 pass under 3G throttling
- [ ] Test 5a — upvote → downvote switches cleanly
- [ ] Test 5b — **downvote → upvote switches cleanly** (diagnostic)
- [ ] Test 6 — same-comment rapid double-tap is sane
- [ ] Test 7 — different-comment rapid taps land
- [ ] Test 8 — downvote survives backgrounding mid-publish
- [ ] Test 9 — publish failure rolls back (best-effort)
- [ ] Test 10 — cross-device upvote + downvote both sync

---

## Automated tests

- `mobile/packages/likes_repository/test/src/likes_repository_test.dart`: 149 tests pass (16 new for the downvote API). Coverage at 88.81% on `likes_repository.dart`, 86.84% on `exceptions.dart` — well above the package's 62% gate. Added stream-tick-ordering tests (`ticks watchDownvotedEventIds before sendLike completes`), rollback tests for both null-return and throw paths on `downvoteEvent` and `removeDownvote`, plus toggle / query coverage.
- `mobile/test/blocs/comments/comments_bloc_test.dart`: 102 tests pass. Updated existing vote-toggle blocTests to expect single optimistic emit (no second \"clear in-progress\" emit). Added a `removeDownvote` verify to the un-downvote test to pin the previously-broken path. Deleted the obsolete `voteInProgressCommentId` copyWith tests.
- `flutter analyze lib test integration_test`: clean.
- `dart format`: no changes.

## Files changed

| File | Why |
|---|---|
| `mobile/packages/likes_repository/lib/src/exceptions.dart` | New `AlreadyDownvotedException`, `NotDownvotedException`. |
| `mobile/packages/likes_repository/lib/src/likes_repository.dart` | Downvote tracking machinery + optimistic-first `downvoteEvent` / `removeDownvote` / `toggleDownvote`. Routing in `_processIncomingReaction` and `syncUserReactions`. |
| `mobile/packages/likes_repository/test/src/exceptions_test.dart` | Coverage for the new exceptions. |
| `mobile/packages/likes_repository/test/src/likes_repository_test.dart` | New downvote test groups + rewired `_processIncomingReaction` test that previously asserted dislike events were ignored. |
| `mobile/lib/blocs/comments/comments_bloc.dart` | Wire downvote API; drop `voteInProgressCommentId` guard; explicit catch for the new exceptions; updated registration comment. |
| `mobile/lib/blocs/comments/comments_state.dart` | Drop `voteInProgressCommentId` field, ctor param, copyWith param, props entry. |
| `mobile/test/blocs/comments/comments_bloc_test.dart` | Update vote-toggle expectations (single emit), drop `voteInProgressCommentId` references, swap `unlikeEvent` for `removeDownvote` mocks where applicable, delete obsolete copyWith tests. |

### CODE REVIEW

**Comment by rabble** [comment]
Read the diff. Two notes for your call before merge:

**1. Residual cross-type race on rapid up→down.**

The handlers stay split:
```dart
on<CommentUpvoteToggled>(_onUpvoteToggled, transformer: droppable());
on<CommentDownvoteToggled>(_onDownvoteToggled, transformer: droppable());
```

`droppable()` is per-event-type. It correctly drops a same-type tap during in-flight publish (Test 6 in your manual plan), but rapid `up → down` (or `down → up`) within publish-RTT runs both handlers concurrently. With `voteInProgressCommentId` removed, nothing serializes across types.

**Practical impact:** UI is fine — the optimistic emit shows the latest tap. The risk is on the relay: kind-7 `+` from the upvote and kind-5 deletion + kind-7 `-` from the downvote can interleave. Worst case: brief relay-state inconsistency that resolves on next `syncUserReactions`.

**Fix options if you want to close the gap:**

(a) Single `CommentVoteToggled` event carrying `Vote vote` enum, one handler with `droppable()`. Tests 5a/5b still work since `droppable` only drops while in-flight.

(b) Custom transformer that groups by `commentId` (different comments stay parallel, same-comment serializes regardless of type).

I'd take (a) — minimal change, identical UX, closes the window.

**2. Test 5b regression coverage.** The PR body lists vote-switch as a previously-broken path you're closing. Worth a unit test that asserts `down→up` switches without flash (drives the handler with a fake `AlreadyDownvotedException` or via the repository stub) — your manual sign-off covers it but I didn't see a unit test for the path.

LGTM otherwise — the `removeDownvote` route, downvote sync via `_processIncomingReaction`, and dropping the redundant `voteInProgressCommentId` are all the right calls. Cross-device downvote sync is a real win.

(Posted by Claude on rabble's behalf — feel free to merge as-is and file (a) as a follow-up if launch timing matters.)

**Comment by realmeylisdev** [comment]
Addressed both notes in `78595c60f`:

**1. Cross-type race — went with option (a).** Folded `CommentUpvoteToggled` and `CommentDownvoteToggled` into a single `CommentVoteToggled` carrying a `Vote` enum, and registered one `droppable()` handler. Rapid up→down (or down→up) on the same comment within publish-RTT now drops the second tap before its handler can emit competing optimistic state or hit the relay with an interleaved kind-7 / kind-5 publish.

UI ergonomics are unchanged for the sequential paths — Tests 5a/5b still complete because `droppable()` only drops while a publish is in flight, and the publish has settled by the time the user taps the opposite arrow deliberately.

**2. Vote-switch unit coverage.** Added a `CommentVoteToggled (vote switch)` test group:

- `down→up switches in a single emit with a +2 net-score delta` — the diagnostic for the original Bug B path. Asserts only one optimistic emit lands and the net-score delta is exactly +2 (no revert flash).
- `up→down switches in a single emit with a -2 net-score delta` — symmetric coverage.
- `rapid up→down on the same comment drops the second tap while in flight` — drives the handler with a `Completer` so the upvote publish is genuinely in-flight when the downvote event is queued, then `verifyNever` on `downvoteEvent` / `unlikeEvent`. This pins today's race-window fix.
- `AlreadyDownvotedException from downvoteEvent does not surface voteFailed` — proves the specific catch handler short-circuits the generic `voteFailed` revert path.
- `NotDownvotedException from removeDownvote does not surface voteFailed` — same for the removal path.

Full bloc suite is green (`110 passed`); `likes_repository` package is green (`153 passed`); `flutter analyze lib test integration_test` clean.

File: mobile/lib/blocs/comments/comments_bloc.dart [hunk 1]
```diff
@@ -69,11 +69,12 @@ class CommentsBloc extends Bloc<CommentsEvent, CommentsState> {
...
-    // droppable() prevents concurrent processing of the SAME event type,
-    // but the manual voteInProgressCommentId guard prevents
-    // rapid toggles on DIFFERENT comment IDs from racing each other.
-    on<CommentUpvoteToggled>(_onUpvoteToggled, transformer: droppable());
-    on<CommentDownvoteToggled>(_onDownvoteToggled, transformer: droppable());
+    // Single handler with droppable() so rapid taps of any vote — same
+    // comment, same direction OR opposite direction — drop while a
+    // publish is in flight. Splitting the handlers by direction would
+    // let an up-tap and a down-tap run concurrently and interleave
+    // kind-7 / kind-5 publishes on the relay.
```
Comment (hm21) [inline mobile/lib/blocs/comments/comments_bloc.dart]: Nit: maybe we should use a shorter commit message, but if you think the extra explanation is useful, it’s totally fine to keep it.

File: mobile/lib/blocs/comments/comments_bloc.dart [hunk 2]
```diff
@@ -485,39 +486,18 @@ class CommentsBloc extends Bloc<CommentsEvent, CommentsState> {
...
     if (!_authService.isAuthenticated) {
       emit(state.copyWith(error: CommentsError.notAuthenticated));
       return;
     }
 
-    // Prevent double-tap on the same comment
-    if (state.voteInProgressCommentId == commentId) return;
+    final commentId = event.commentId;
+    final authorPubkey = event.authorPubkey;
+    final isUpvote = event.vote == Vote.up;
```
Comment (hm21) [inline mobile/lib/blocs/comments/comments_bloc.dart:498]: Super small nit, but we could consider extending the enum with a bool `isUpVote`. Might be overkill though, so definitely not mandatory.

File: mobile/packages/likes_repository/lib/src/likes_repository.dart [hunk 3]
```diff
@@ -844,6 +1020,23 @@ class LikesRepository {
             _likeRecords[targetId] = record;
             newRecords.add(record);
           }
+        } else if (event.content == _downvoteContent) {
+          final record = LikeRecord(
+            targetEventId: targetId,
+            reactionEventId: event.id,
+            createdAt: DateTime.fromMillisecondsSinceEpoch(
+              event.createdAt * 1000,
```
Comment (hm21) [inline mobile/packages/likes_repository/lib/src/likes_repository.dart:1028]: Nothing to do for now, but I noticed we have logic like `DateTime.fromMillisecondsSinceEpoch(event.createdAt * 1000)` in many places, and sometimes `timeMs / 1000`. I’m wondering if we should create/extend a package with simple helpers (extension) so we could just write something like `event.createdAt.toDateTime()`. WDYT?

**Review by hm21 — APPROVED** [review]
LGTM, I just left a couple of very small nits and a question for a future PR, but it’s completely fine to merge as is :)

File: mobile/lib/blocs/comments/comments_bloc.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/blocs/comments/comments_bloc.dart]: Tightened in 0541d12 — kept the protocol-level concern (concurrent kind-7 / kind-5 publishes) and dropped the redundant tap-pattern enumeration. Down to 3 lines.

File: mobile/lib/blocs/comments/comments_bloc.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/blocs/comments/comments_bloc.dart:498]: Considered it — leaving as-is. The conversion only happens at this single call site (the result is captured into the local `isUpvote` and reused throughout), and `event.vote.isUpvote` is the same length as `event.vote == Vote.up`. So the getter wouldn't shorten the call site or remove duplication. Happy to revisit if a second comparison appears.

File: mobile/packages/likes_repository/lib/src/likes_repository.dart (hunk 3 above)
Comment (realmeylisdev) [reply mobile/packages/likes_repository/lib/src/likes_repository.dart:1028]: Good call — the duplication is real (a quick grep shows 30+ `fromMillisecondsSinceEpoch(... * 1000)` and a similar count of `/ 1000`-style conversions sprinkled across the relay/event-parsing layers). A pair of `int.toDateTimeFromSeconds()` / `DateTime.toEpochSeconds()` extensions in a small `nostr_time` (or extending an existing utility package) would clean this up uniformly. Filing a follow-up issue and leaving this PR alone.

Comment (realmeylisdev) [reply mobile/packages/likes_repository/lib/src/likes_repository.dart:1028]: Filed as #3504 with the grep numbers (58 `fromMillisecondsSinceEpoch` + 28 `* 1000` adjacent) and a proposed `toDateTimeFromEpochSeconds()` / `toEpochSeconds()` extension pair.

**Comment by realmeylisdev** [comment]
@hm21 thanks for the review! Quick summary on the three nits:

1. **Comment block on the `droppable()` registration** — tightened from 5 lines to 3 in 0541d12; kept the protocol-level "would interleave kind-7 / kind-5 publishes on the relay" rationale and dropped the redundant tap-pattern enumeration.
2. **`bool isUpVote` on the `Vote` enum** — leaving as-is; the conversion lives at a single call site and `event.vote.isUpvote` would be the same length as `event.vote == Vote.up`. Happy to revisit if a second comparison appears.
3. **Epoch-second extension helpers** — filed as #3504 with the grep numbers (58 `fromMillisecondsSinceEpoch` + 28 adjacent `* 1000` patterns in non-test code) and a proposed `toDateTimeFromEpochSeconds()` / `toEpochSeconds()` extension pair. Out of scope for this PR.
