### PR TITLE
fix: handle relay disconnection gracefully in profile save

### LINKED ISSUE #704: fix: Profile | P0 | Profile edit stuck on loading after tapping Save
### Summary

When editing profile info (title, description, picture) and tapping Save, the screen sometimes remains in a loading state and the user must restart the app, even though the changes are saved.

### Environment

Device: Iphone SE v26.2 and Samsung A54 v15
Build: 1.0.4(171 on iOS) and 1.0.4(40 on Android)

### Steps to Reproduce

Go to Profile → Edit Profile.
Change title, description, and/or profile picture.
Tap Save.
Wait for the update to complete.

### Actual Result

The screen sometimes stays in a loading state after tapping Save.
The user must close and reopen the app to continue.
After restarting, the profile changes are correctly saved.

### Expected Result

Saving profile edits should complete normally and return the user to the profile page without getting stuck.

### Regression?

Yes

### Evidence

https://github.com/user-attachments/assets/25abd584-bfe1-45dc-9b18-b77e705c029e

### PR DESCRIPTION
**Pull request by Josh-Sanford**
## Summary

Fixes profile save getting stuck when relay connections die silently.

## Changes

- **auth_service.dart**: Removed erroneous expiration tag from kind 0 (profile) events
- **nostr_client.dart**: Added relay reconnection attempt in `publishEvent()` - returns null early if no relays available

## How It Works

When `publishEvent()` is called with no connected relays:
1. Attempts reconnection via `retryDisconnectedRelays()`
2. If still no relays → returns null (triggers error message)
3. If reconnected → proceeds normally

Works with PR #835's heartbeat detection to identify zombie connections.

## Related Issues

- Closes #704
- Related: #823 (username atomicity - separate issue)

### CODE REVIEW

File: mobile/packages/nostr_client/lib/src/nostr_client.dart [hunk 1]
```diff
@@ -701,6 +701,21 @@ class NostrClient {
     Event event, {
```
Comment (ryzizub) [inline mobile/packages/nostr_client/lib/src/nostr_client.dart]: Broadcast was exchanged for publish so you might wan to update branch and if its still causing issues :)

Comment (Josh-Sanford) [reply mobile/packages/nostr_client/lib/src/nostr_client.dart]: I told myself to pull main first... haha thanks for pointing that out! I moved the logic to publishEvent, let me know what you think 🙏
