### PR TITLE
fix(seed): parameterize SeedDataPreload and swap raw SQL asset for JSON

### LINKED ISSUE #3093: fix: SeedDataPreload SQLite parse error on app start
Discovered while triaging #2954. Error fires on app start for affected users:

```
[ERROR] [SYSTEM] (SeedDataPreload) [SEED] ❌ Failed to load seed data (non-critical): SqliteException(1): while executing, unrecognized token: "'[[\"d\",\"5vQVHYMHWwq\"],[\"imeta\",\"url\",\"https://cdn.divine.video/28d49fec...mp4\",\"m\",\"video/mp4\",..."
```

The token looks like a Nostr event tag array being passed as a raw string into a SQL statement — almost certainly string-concatenation instead of a parameterized query. Logged as non-critical, but it's masking seed data loading entirely and likely logs on every cold start for users whose seed bundle contains this event.

## Next steps
- Find the SeedDataPreload path that writes/reads this column
- Switch to parameterized bindings (`?` / `@param`) rather than string interpolation
- Add a test that seed data with quotes/brackets in tag JSON round-trips cleanly

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #3093.

## Why

The old loader read `assets/seed_data/seed_events.sql` and ran it through `String.split(';')` before calling `db.customStatement` on each chunk. The splitter had no notion of SQL string literals, so a single seed row whose tags JSON contained `"ig; phaxn"` (an Instagram handle in a Vine author name) tore the INSERT apart at the embedded `;`. The remaining fragment had an unterminated `'...'` and SQLite rejected it with `unrecognized token: "'[[..."`. Because every insert ran inside one `db.transaction`, the failure rolled back **all** seed data — the local DB stayed empty, and the same error logged on every cold start until the app fetched from the relay.

The generator was already escaping `'` → `''` correctly, so single quotes were never the real issue. The title's fix — parameterize — is still the right long-term move because it removes the entire class of splitter / escape bugs.

## What changed

- **New asset**: `mobile/assets/seed_data/seed_events.json` (events + profile rows + metric rows). ~767KB vs ~819KB SQL.
- **Loader** (`SeedDataPreloadService`): loads JSON, binds every column through `db.customInsert(..., variables: [Variable.with...])`, keeps the one-shot transaction and the no-op-when-non-empty guard. `DateTime` columns use `Variable.withDateTime`, so Drift's default unix-epoch encoding is in play end-to-end (the old path wrote ISO strings into int-typed columns, which would have broken reads even if the split had worked).
- **Generator** (`scripts/generate_seed_data.dart`): emits JSON for future relay-driven regenerations.
- **Tests**: mock asset is JSON; added round-trip coverage for semicolons in tags, single quotes in content, brackets/backslashes, malformed JSON.

## Test plan

- [x] `flutter test test/services/seed_data_preload_service_test.dart` — 8/8 pass
- [x] `flutter test test/services/` — 1759/1759 pass
- [x] `flutter analyze lib test scripts` — clean
- [x] Pre-commit hook (format + analyze) ran green on commit
- [ ] Manual smoke on a fresh install — confirm seed count matches `meta.events` and no error logs

## Out of scope / follow-ups

- `docs/plans/2025-01-11-seed-data-preload*.md` still reference the SQL asset; left as historical design notes per the "older docs can drift" convention.
- Abandoned branch `origin/fix/seed-data-sql-escaping` (empty-tree commit `f87db4288`, @mbradley) can be deleted.

### CODE REVIEW

File: mobile/lib/services/seed_data_preload_service.dart [hunk 1]
```diff
@@ -34,24 +36,27 @@ class SeedDataPreloadService {
           category: LogCategory.system,
         );
 
-        // Load SQL file from assets
-        final sql = await rootBundle.loadString(
-          'assets/seed_data/seed_events.sql',
-        );
+        final raw = await rootBundle.loadString(_seedAsset);
+        final bundle = jsonDecode(raw) as Map<String, dynamic>;
```
Comment (hm21) [inline mobile/lib/services/seed_data_preload_service.dart]: I’m a bit concerned that low-end android devices might get stuck if we run this on the main thread. What do you think about the following?

```dart
final bundle = await compute(
  (raw) => jsonDecode(raw) as Map<String, dynamic>,
  raw,
);
```

File: mobile/lib/services/seed_data_preload_service.dart [hunk 2]
```diff
@@ -34,24 +36,27 @@ class SeedDataPreloadService {
...
+          for (final event in events) {
+            await _insertEvent(db, event);
+          }
+          for (final profile in profiles) {
+            await _insertProfile(db, profile);
+          }
+          for (final metric in metrics) {
+            await _insertMetric(db, metric);
           }
         });
```
Comment (hm21) [inline mobile/lib/services/seed_data_preload_service.dart]: Do you think we should use a batch write here?


```dart
await db.batch((batch) {
  for (final event in events) {
    batch.customInsert(
      'INSERT OR IGNORE INTO event ...',
      variables: [...],
    );
  }
});
```

File: mobile/lib/services/seed_data_preload_service.dart [hunk 3]
```diff
@@ -34,24 +36,27 @@ class SeedDataPreloadService {
...
-          'assets/seed_data/seed_events.sql',
-        );
+        final raw = await rootBundle.loadString(_seedAsset);
+        final bundle = jsonDecode(raw) as Map<String, dynamic>;
+        final events = (bundle['events'] as List? ?? const [])
+            .cast<Map<String, dynamic>>();
+        final profiles = (bundle['profiles'] as List? ?? const [])
+            .cast<Map<String, dynamic>>();
+        final metrics = (bundle['metrics'] as List? ?? const [])
+            .cast<Map<String, dynamic>>();
```
Comment (hm21) [inline mobile/lib/services/seed_data_preload_service.dart]: Lazy `.cast<Map<String, dynamic>>()` doesn't validate until iteration, which means a single malformed element in the middle of the list rolls back all seed data silently. `whereType<Map<String, dynamic>>()` would be safer.

**Review by hm21 — APPROVED** [review]
