### PR TITLE
fix(video_editor): correct seek position handling 

### LINKED ISSUE #3464: fix(video_editor): correct seek position handling
Auto-created from PR #3463.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3463
**Branch:** `fix/jump-wrong-trim-position`

### PR DESCRIPTION
**Pull request by hm21**
Closes #3464

## Description

After trimming a clip, the timeline didn’t match the position shown in the preview video. This PR ensures that both the timeline and the preview display the exact same position.

**Related Issue:** Closes # or Relates to #

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by rabble** [comment]
Code review (Claude on rabble's behalf):

**Verdict:** LGTM with concerns — one launch-relevant issue.

**Summary.** Two-part fix in `video_editor_canvas.dart`. (1) Move `_seekEpoch != epoch` check before `await _videoPlayer?.seekTo(pending)` so a composition swap aborts the stale seek instead of issuing it against the replaced player. (2) After trim-release `setClips` resolves, dispatch `VideoEditorPositionChanged(startPosition)` and `_proVideoController.setPlayTime` (mounted-guarded), so timeline cursor and preview frame match.

**Blockers:** none.

**Most actionable:**
- **Zero coverage on changed lines.** Project rule is 100% line coverage on changed code; `very_good_coverage` gate will likely reject. One widget test driving a trim release and asserting `VideoEditorPositionChanged(startPosition)` would clear it. Two days from launch — this is the single highest-priority follow-up.
- **`mergeable: UNKNOWN`.** Branch is significantly behind `main`; rebase before merge.
- **Builds on #3407** (just merged, same author). The dual-write between `_proVideoController` and the BLoC during live drag is now mirrored on release. Internally consistent, but iOS device QA on trim-handle release with both PRs together is warranted.

**Concerns:**
- **Async-listener typing.** `BlocListener` accepts `void Function(BuildContext, State)`; passing `(context, state) async { ... }` returns a discarded `Future<void>`. Behaviorally equivalent to the prior `unawaited(...)` wrapper, but unhandled errors inside the future no longer have an explicit `unawaited` marker. The existing try/catch covers it.

**Nits:**
- Line 962–966 uses outer `bloc` while line 944 uses local `mainBloc` — same instance; pick one.
- When `trimEndPosition != null` the position is dispatched twice (pre- and post-await) with the same value. Coalesce or comment why.

**Conflict warning:** open PR #3473 (perf/video-editor-timeline) also touches `video_editor_canvas.dart`. Whichever lands first, the other rebases. Recommend this PR (#3463) first — smaller and fixes a visible bug.

**Comment by hm21** [comment]
@rabble thanks for the review:

> Zero coverage on changed lines.

Updated, but right now we only have 100% coverage in internal packages, so `very_good_coverage` wouldn’t reject anything here.


> mergeable: UNKNOWN

It is, and GitHub would block it if it weren’t.

> Builds on https://github.com/divinevideo/divine-mobile/pull/3407

It's fine i tested it and all good.

> Concerns: Async-listener typing. 

The discarded `Future<void>` is harmless here because the entire async body is wrapped in `try/catch/finally`, so all errors are logged and `_isSeeking` is always reset, behaviorally identical to the prior `unawaited(...)` version, just without the explicit marker.

> Nits

Fixed

> Conflict warning: open PR https://github.com/divinevideo/divine-mobile/pull/3473 (perf/video-editor-timeline) also touches video_editor_canvas.dart. Whichever lands first...

It’s fine, it’s just a small merge conflict to fix. I just prefer moving quickly by building new features/fixes right away instead of waiting on reviews or splitting things into stacked PRs as fixing a merge conflict like that is less than 1min time.

**Comment by realmeylisdev** [comment]
@hm21 — two follow-up ideas after re-reading this with rabble's review in mind. Not blockers, just things worth tracking as separate issues if you agree:

**1. Gate `_onPlayerStateChanged` on `_isSeeking`.** This PR fixes the trim-release scrubber/preview gap by re-pushing `startPosition` after `await setClips`. The reason that re-push is needed is that `_onPlayerStateChanged` (`video_editor_canvas.dart:323`) dispatches `VideoEditorPositionChanged` + `setPlayTime` from the native `stateStream` without checking `_isSeeking` — so transient frames during an in-flight `setClips`/`seekTo` can overwrite the target. The trim-release path is now patched, but `_onSeekRequested`, `seekCounter`, and `_initializePlayer`'s `setClips` are still exposed to the same race. Adding `if (_isSeeking) return;` (or guarding just the dispatch block) closes it for all seek paths. The post-await `bloc.add(...)` here becomes belt-and-braces.

**2. Extract the trailing-seek loop to a `@visibleForTesting` static.** Same shape as `syncPositionAfterTrimRelease`. The epoch-check reorder in `_onSeekRequested` (lines ~300–309) is a real correctness improvement but isn't unit-tested because the loop lives on the private `_VideoEditorState`. Extracting it would let a regression around `_seekEpoch` / `_pendingSeekPosition` get caught by a unit test instead of by hand.

Happy to file both as issues if you'd rather not — say the word.

**Comment by hm21** [comment]
@realmeylisdev thanks for the review:

1. Looked at the other paths — the gate wouldn't actually help where it's claimed to. _onSeekRequested's bare seekTo doesn't produce transient native positions in practice, _initializePlayer runs before _isPlayerReadyNotifier flips so the dispatch is gated upstream, and the composition-swap path on L877 explicitly clears _isSeeking before calling setClips precisely so the new epoch can take ownership — adding if (_isSeeking) return; there would be a no-op. The trim-release fix in this PR (re-push setPlayTime ahead of seekTo) is what actually closes the visible gap. Happy to add the gate as belt-and-braces if you'd still prefer it, but it's not a real second leak today.
2. Considered, but punting — the loop's correctness hinges on its interaction with the real _seekEpoch mutation from the composition-swap path and on actual async ordering of native seekTo completions. Extracting it forces enough callback injection (epoch getter, pending getter/setter, seek fn, mounted check) that the resulting unit test would mostly verify the mock wiring, not the race behaviour. The syncPositionAfterTrimRelease extraction worked because that's a linear three-step sequence; this one is a stateful scheduler. E2E coverage of "trim-release while a seek is in flight" is the right level — adding to the editor E2E plan rather than backfilling a brittle unit test now.

File: mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart [hunk 1]
```diff
@@ -48,4 +49,84 @@ void main() {
...
+      controller = ProVideoController(
+        videoPlayer: const SizedBox.shrink(),
+        videoDuration: Duration.zero,
+        initialResolution: Size.zero,
+        fileSize: 0,
+      );
+    });
+
+    tearDown(() {
+      mainBloc.close();
```
Comment (realmeylisdev) [inline mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart]: Nit: `Bloc.close()` returns a `Future`. Consider `tearDown(() async { await mainBloc.close(); });` so cleanup completes before the next test starts — otherwise a stray handler tick from this bloc can leak into the following test (and event-spy assertions in particular get flaky-prone).

File: mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart [hunk 2]
```diff
@@ -48,4 +49,84 @@ void main() {
...
+
+    setUp(() {
+      mainBloc = _SpyVideoEditorMainBloc();
+      controller = ProVideoController(
+        videoPlayer: const SizedBox.shrink(),
+        videoDuration: Duration.zero,
+        initialResolution: Size.zero,
+        fileSize: 0,
+      );
+    });
```
Comment (realmeylisdev) [inline mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart:65]: Nit: `controller` (and its `playTimeNotifier`) is leaked between tests in this group. If `ProVideoController` exposes a `dispose()`, add it to the `tearDown` alongside `mainBloc.close()`.

File: mobile/lib/widgets/video_editor/main_editor/video_editor_canvas.dart [hunk 3]
```diff
@@ -280,11 +301,11 @@ class _VideoEditorState extends ConsumerState<_VideoEditor> {
       while (_pendingSeekPosition != null && mounted) {
         final pending = _pendingSeekPosition!;
         _pendingSeekPosition = null;
-        await _videoPlayer?.seekTo(pending);
         if (_seekEpoch != epoch) {
           _pendingSeekPosition = null;
           break;
         }
+        await _videoPlayer?.seekTo(pending);
```
Comment (realmeylisdev) [inline mobile/lib/widgets/video_editor/main_editor/video_editor_canvas.dart:308]: Pre-await check is the right move — but note the post-await guard that previously lived here is now gone, so this loop relies on the invariant that **every composition-swap path nulls `_pendingSeekPosition`** (today: L878 trim-start swap, L967 trim-release swap). If a future change drops one of those `_pendingSeekPosition = null;` assignments, a swap mid-`await` here would let the loop keep iterating with a stale pending value against the new player.

Worth a one-line `// _pendingSeekPosition = null is load-bearing for the trailing-seek loop in _onSeekRequested` near each swap site, or above the loop, so the invariant doesn't get accidentally undone in a future refactor.

**Review by realmeylisdev — COMMENTED** [review]
Tiny follow-ups on top of the earlier rounds — none blocking. Already-addressed feedback (the `bloc`/`mainBloc` cleanup, double-dispatch nit, the `_isSeeking` gate / loop extraction) covered in prior threads.

- Two test-cleanup nits below.
- One comment on the moved epoch check — the deletion of the post-await guard makes the loop rely on a load-bearing invariant elsewhere in the file; worth a one-line note so a future change doesn't drop it.

Also minor: PR template has `Breaking change` checked — this is a bug fix.

File: mobile/lib/widgets/video_editor/main_editor/video_editor_canvas.dart (hunk 3 above)
Comment (hm21) [reply mobile/lib/widgets/video_editor/main_editor/video_editor_canvas.dart:308]: The loop is already guarded by the _seekEpoch != epoch check inside it — a composition swap mid-await bumps the epoch, which breaks the loop on the next iteration regardless of whether the swap site nulled _pendingSeekPosition. The nulling at swap sites is hygiene, not load-bearing, so I'd rather not add a comment that implies an invariant the code doesn't actually depend on.

File: mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart (hunk 2 above)
Comment (hm21) [reply mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart:65]: Good catch in principle, but ProVideoController.dispose() reads isPlayingNotifier, which is late final and only initialized via initialize() (called with the editor's full callbacks/configs in production). Calling dispose() on a freshly-constructed controller therefore throws LateInitializationError. Since this unit test doesn't go through initialize(), leaving dispose() off is the right move — only the constructor-built notifiers (thumbnailsNotifier, resolutionNotifier) would leak, and they hold trivial values.

File: mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart (hunk 1 above)
Comment (hm21) [reply mobile/test/widgets/video_editor/main_editor/video_editor_canvas_test.dart]: await doesn't change behavior here — both tests are fully synchronous, and setUp builds a fresh bloc + spy list each time, so a stray handler tick from the previous bloc would fire against an unreferenced instance and can't influence the next test's assertions. Happy to keep the await as defensive hygiene though.

**Review by realmeylisdev — APPROVED** [review]
LGTM. The await on bloc.close() addresses the test-isolation concern. Remaining items (controller disposal, swap-site invariant comment, PR template checkbox) are nits — fine to fold into a follow-up or skip.

**Comment by realmeylisdev** [comment]
Items still open from the previous round (none blocking, fine for follow-up):

- `ProVideoController` disposal in `tearDown` — unchanged.
- Load-bearing `_pendingSeekPosition = null` invariant comment near swap sites (L877, L965) — no comment added; correctness is unaffected, this was about future-proofing.
- "Breaking change" checkbox in PR template — still ticked; cosmetic.
