### PR TITLE
fix: black camera on recording

### LINKED ISSUE #306: fix: Camera | P1 | Camera turns black after exiting metadata screen
### Summary

If the user records a video, proceeds to the metadata screen (title/description), then goes back without publishing, the camera becomes completely black when trying to record a new video

### Environment

App version: 1.0.2 (131)
OS: iOS v26.2
Device: iPhone Se
Network: Wi-Fi

### Steps to Reproduce

Open the app
tap the camera button
Record a video.
Continue until reaching the metadata screen (title, description, etc.).
Do NOT publish the video.
Tap Back to exit the upload flow.
Start recording a new video.

### Actual Result

The camera view is completely black.

### Expected Result

The camera should initialize correctly after returning from the metadata screen.

### Regression?

Yes

### Evidence

https://github.com/user-attachments/assets/af2c2023-0c35-42db-9897-2c7bafd810b8

### PR DESCRIPTION
**Pull request by hudson-proenca**
## Description

https://github.com/user-attachments/assets/6d373752-10a8-4f41-863a-55e5dffa0603

**Related Issue:** Closes #306 
Part of #426 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/screens/pure/universal_camera_screen_pure.dart [hunk 1]
```diff
@@ -1478,10 +1483,7 @@ class _UniversalCameraScreenPureState
             category: LogCategory.video,
           );
 
-          // Reset processing flag after navigation
-          setState(() {
-            _isProcessing = false;
-          });
+          // // Reset processing flag after navigation
```
Comment (erickzanardo) [inline mobile/lib/screens/pure/universal_camera_screen_pure.dart]:
```suggestion
          // Reset processing flag after navigation
```

**Review by erickzanardo — APPROVED** [review]
One nit, but LGTM when that is addressed
