### PR TITLE
fix(router): rewrite divine.video universal links before GoRouter match

### LINKED ISSUE #3032: fix: deep links bypass DeepLinkService and hit GoRouter directly, showing Page Not Found
## Summary

While working on #2477, it has been noticed that deep links opened via `adb shell am start` (and likely universal links in production) are routed directly to GoRouter instead of through `DeepLinkService`. GoRouter receives the full URL (e.g. `https://divine.video/search/music`) as the location, fails to match any route, and shows the default "Page Not Found" error page.

## Environment
- App version: Latest (debug build)
- Device: Android Emulator (Medium Phone API 36)
- Network: N/A

## Steps to Reproduce
1. Run the app on an Android emulator
2. In a terminal, run:
   ```
   adb shell am start -a android.intent.action.VIEW -d "https://divine.video/search/music" co.openvine.app
   ```
3. See "Page Not Found" with `GoException: no routes for location: https://divine.video/search/music`

## Actual Result
GoRouter intercepts the deep link URL directly and tries to match `https://divine.video/search/music` against its route table. No route matches, so it shows the default error page. `DeepLinkService` (which correctly parses the URL and calls `router.go()` with the right internal path) never receives the event.

## Expected Result
Deep links should be parsed by `DeepLinkService`, which converts them to internal routes (e.g. `/search-results/music`) and navigates via `router.go()`.

## Regression?
Unknown — this likely affects all deep link types (`/video`, `/profile`, `/hashtag`, `/search`), not just search. It may have been masked because GoRouter happened to have matching route patterns for some URL paths.

## Evidence
`MaterialApp.router` with `routerConfig: router` gives GoRouter full control over incoming URLs. GoRouter's `redirect` callback only fires after a route matches — unmatched URLs throw `GoException` before redirect runs. `DeepLinkService` listens via `app_links` but GoRouter processes the intent first.

### PR DESCRIPTION
**Pull request by untreu2**
## Description
Android delivers the full intent URL (scheme + host + path) toMaterialApp.router, and GoRouter only matches on path. Paths that differ between the public URL contract and the internal route table — notably /search/:term vs /search-results/:query —fell through to GoRouter's Page Not Found error page.

Add a pure universalLinkToRouterPath(Uri) resolver in router/universal_link_resolver.dart, share it with the existing DeepLinkService parser (now static), and call it at the top of the GoRouter.redirect callback. Video is intentionally deferred to the stream listener so router.push keeps the home feed under the detail page for back-navigation. Idempotency guards added to profile/hashtag/ search listener arms to absorb double-emit from app_links. Stale

**Related Issue:** Closes #3032 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/main.dart [hunk 1]
```diff
@@ -1189,6 +1189,10 @@ class _DivineAppState extends ConsumerState<DivineApp> {
                   category: LogCategory.ui,
                 );
                 try {
+                  // GoRouter's universal-link redirect may have already
+                  // navigated here; skip the duplicate go() to avoid a
+                  // second navigation frame on the same target.
+                  if (currentLocation == targetPath) break;
```
Comment (realmeylisdev) [inline mobile/lib/main.dart:1202]: Potential regression — this guard won't fire for profile universal links **without** an index.

For `https://divine.video/profile/<npub>` (no index):
- `universalLinkToRouterPath` returns `/profile/<npub>` (grid mode, via `ProfileScreenRouter.pathForNpub`)
- This arm computes `targetPath = '/profile/<npub>/0'` on line 1185 (because `deepLink.index ?? 0`)

So `currentLocation` is `/profile/<npub>` but `targetPath` is `/profile/<npub>/0` — the `==` check is false, and `router.go` then overrides the resolver's grid-mode landing with feed mode at index 0. The two layers disagree on which UX state to land in.

Suggest mirroring the resolver logic here so both paths agree:

```dart
case DeepLinkType.profile:
  if (deepLink.npub != null) {
    final index = deepLink.index;
    final targetPath = index != null
        ? ProfileScreenRouter.pathForIndex(deepLink.npub!, index)
        : ProfileScreenRouter.pathForNpub(deepLink.npub!);
    …
  }
```

File: mobile/test/router/universal_link_resolver_test.dart [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+      test('preserves URL-encoded non-ASCII tags', () {
+        // `Uri` round-trips the encoded form back through `parseDeepLink`,
+        // which in turn passes it to `HashtagScreenRouter.pathForTag`. The
+        // caller (route matcher) decodes it before rendering.
+        final encoded = Uri.encodeComponent('🔥');
+        final result = universalLinkToRouterPath(
+          Uri.parse('https://divine.video/hashtag/$encoded'),
+        );
+        expect(result, startsWith('/hashtag/'));
+        expect(result!.length, greaterThan('/hashtag/'.length));
```
Comment (realmeylisdev) [inline mobile/test/router/universal_link_resolver_test.dart]: This assertion is very loose — it passes for almost any non-null string that starts with `/hashtag/`. Since `HashtagScreenRouter.pathForTag` re-encodes via `Uri.encodeComponent`, the expected output is deterministic:

```dart
expect(result, equals('/hashtag/${Uri.encodeComponent('🔥')}'));
```

That also documents the round-trip behavior the comment above is describing.

File: mobile/lib/services/deep_link_service.dart [hunk 3]
```diff
@@ -104,8 +104,10 @@ class DeepLinkService {
     }
   }
 
-  /// Parse a divine.video URL into a DeepLink
-  DeepLink parseDeepLink(String url) {
+  /// Parse a divine.video URL into a [DeepLink].
+  ///
+  /// Pure: no instance state is touched, safe to call from route redirects.
+  static DeepLink parseDeepLink(String url) {
```
Comment (realmeylisdev) [inline mobile/lib/services/deep_link_service.dart:110]: Nit — the router redirect call site does `parseDeepLink(uri.toString())` and this method immediately calls `Uri.parse(url)` again, so the same URI gets serialized and re-parsed on every redirect (which fires for every navigation). Since the remaining in-service callers already hold a `Uri`, either changing the signature to `static DeepLink parseDeepLink(Uri uri)` or adding a `parseDeepLinkUri` overload would avoid the round trip. Non-blocking.

File: mobile/lib/main.dart [hunk 4]
```diff
@@ -1253,6 +1259,10 @@ class _DivineAppState extends ConsumerState<DivineApp> {
...
```
Comment (realmeylisdev) [inline mobile/lib/main.dart:1272]: Nit — the profile / hashtag / search arms now share the identical shape: `if (currentLocation == targetPath) break; router.go(targetPath);` wrapped in the same try/catch + log pair. A small `_navigateIfDifferent(router, currentLocation, targetPath)` helper would DRY this up. Out of scope for a bug fix; flagging for future cleanup.

**Review by realmeylisdev — COMMENTED** [review]
Nice fix — shared resolver + static `parseDeepLink` is the right shape. A few inline comments; only the first one looks like a real behavior issue, the rest are nits.

**Review by rabble — APPROVED** [review]
Clean additive change: pure `universalLinkToRouterPath` invoked before GoRouter match, 163-line unit test, video deep-link stacking preserved. LGTM.

File: mobile/lib/main.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/main.dart:1202]: Confirmed in cdbe714c8 — the listener now mirrors `universalLinkToRouterPath` exactly:

```dart
final index = deepLink.index;
final targetPath = index != null
    ? ProfileScreenRouter.pathForIndex(deepLink.npub!, index)
    : ProfileScreenRouter.pathForNpub(deepLink.npub!);
```

Traced both cases end-to-end:
- `/profile/<npub>` → resolver + listener both produce `/profile/<npub>` → idempotency guard fires, grid mode preserved.
- `/profile/<npub>/3` → both produce `/profile/<npub>/3` → guard fires, feed mode preserved.

Targeted tests pass (53/53). Thanks for the quick turnaround.

File: mobile/test/router/universal_link_resolver_test.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/test/router/universal_link_resolver_test.dart]: Confirmed in cdbe714c8 — exact-equals check on `/hashtag/$encoded` reads much better, and the updated comment (`Uri.parse` decodes → `pathForTag` re-encodes) describes the determinism clearly. Nice.

File: mobile/lib/services/deep_link_service.dart (hunk 3 above)
Comment (realmeylisdev) [reply mobile/lib/services/deep_link_service.dart:110]: Happy to defer — marking this nit as acknowledged per the non-blocking label. No action needed on this PR.

File: mobile/lib/main.dart (hunk 4 above)
Comment (realmeylisdev) [reply mobile/lib/main.dart:1272]: Acknowledged — this was flagged as out-of-scope future cleanup. No action needed here.

**Review by realmeylisdev — APPROVED** [review]
Blocker from my previous review is addressed in cdbe714c8 — listener now mirrors `universalLinkToRouterPath`, so index-less universal links land in grid mode as intended and the idempotency guard catches both modes. Test assertion tightened to an exact-equals. Two non-blocking nits (Uri signature, DRY helper) acknowledged as deferred. LGTM.
