### PR TITLE
fix(video-editor): allow adding duplicate clips from library to editor

### LINKED ISSUE #1080: fix: Failure when adding multiple clips to edit page
### Summary

Adding multiple clips in the Edit page often fails.

### Environment

Build: 1.0.4(306) on iOS and 1.0.4(171) on Android
Device: Samsung A54 and Iphone Se v26.3

### Steps to Reproduce

Open the app
Go to the create video feature
Recod a video
Go to the edit page
Attempt to add several clips

### Actual Result

When selecting two or more clips, the app frequently only imports one.

### Expected Result

All selected clips should be successfully imported to the video

### Regression?

No

### Evidence

https://github.com/user-attachments/assets/def9d839-5575-4294-8a66-6c8e9201468e

### PR DESCRIPTION
**Pull request by hm21**
## Description

Reported issue from QA: 

> not able to add multiple clips in the edit page, you pick 2 and only one is added to the video (not able to reproduce all the time, but 80% of the time).

The problem was that, for example, when a user had clips with IDs A and B in the clip editor and then opened the clip library to select clips with IDs C and A, clip A was skipped because its ID was already in use. Now, it's also possible to add the same clip multiple times, which can be useful if the user wants to clip different parts of the same clip at various positions.

**Related Issue:** Closes #1080

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/screens/clip_library_screen.dart [hunk 1]
```diff
@@ -141,18 +141,15 @@ class _ClipLibraryScreenState extends ConsumerState<ClipLibraryScreen> {
...
-          video: EditorVideo.file(clip.filePath),
-          duration: clip.duration,
-          thumbnailPath: clip.thumbnailPath,
-          aspectRatio: model.AspectRatio.values.firstWhere(
-            (el) => el.name == clip.aspectRatio,
-            orElse: () => .vertical,
-          ),
-        );
-      }
+      clipManagerNotifier.addClip(
```
Comment (erickzanardo) [inline mobile/lib/screens/clip_library_screen.dart:144]: Would be good if we could add a unit test that would verify the specific context that caused the bug that this PR is fixing. Wdyt?

Comment (hm21) [reply mobile/lib/screens/clip_library_screen.dart:144]: That makes absolute sense. I just added it in [fccbf92](https://github.com/divinevideo/divine-mobile/pull/1068/commits/fccbf926502662f4ad1de0541e3f3e022919116e)
