### PR TITLE
fix(collabs): emit lowercase collaborator marker on video p-tags

### LINKED ISSUE #3682: fix(collabs): emit lowercase collaborator marker on video p-tags
## Summary

divine-connect now accepts collaborator marker casing case-insensitively because real mobile-published Kind 34236 events are emitting `"Collaborator"` instead of canonical lowercase `"collaborator"`.

That unblocks inbox visibility in Connect, but divine-mobile should still normalize its outbound marker casing so newly published events are consistent.

## Scope

- Update the Kind 34236 video event publisher to emit lowercase `"collaborator"` for collaborator `p` tags
- Add or update a regression test covering the emitted tag shape
- Verify no other collaborator marker emitters in mobile use the capitalized form

## Why this still matters

Connect now tolerates both casings for backward compatibility with already-published relay data, but keeping mobile output canonical avoids carrying compatibility tax forever and prevents other consumers from making the same mistake.

### PR DESCRIPTION
**Pull request by mbradley**
## Summary

- Normalizes outbound Kind 34236 p-tag marker from `"Collaborator"` to canonical lowercase `"collaborator"` in both emitter locations (direct upload publish and post-publish edit)
- Updates regression test to assert lowercase and reject capitalized form
- DM role tags (`collaborator_invite_service.dart`) intentionally unchanged -- separate NIP-17 protocol surface, closed loop within mobile

Closes #3682

## Test plan

- [x] Existing collaborator tag test passes with lowercase assertion
- [x] `flutter analyze` clean on changed files
- [ ] Publish a video with a collaborator tagged, verify the relay event carries lowercase `"collaborator"` marker

### CODE REVIEW

**Comment by NotThatKindOfDrLiz** [comment]
Non-blocking follow-up filed for edit-path regression coverage so the two Kind 34236 collaborator emitters stay aligned: #3689. The code change here is correct and merge-ready.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
The lowercase collaborator marker change is correct and covers both Kind 34236 emitters. I verified the mobile parser does not depend on the 4th p-tag element, so this is a safe wire-format normalization. Follow-up edit-path test coverage is tracked in #3689.

File: mobile/lib/services/video_event_publisher.dart [hunk 1]
```diff
@@ -650,7 +650,7 @@ class VideoEventPublisher {
 
       // Add collaborator p-tags (standard NIP-71 format)
       for (final pubkey in collaboratorPubkeys) {
-        tags.add(['p', pubkey, 'wss://relay.divine.video', 'Collaborator']);
+        tags.add(['p', pubkey, 'wss://relay.divine.video', 'collaborator']);
```
Comment (realmeylisdev) [inline mobile/lib/services/video_event_publisher.dart:653]: **Context, not blocking.** The `(standard NIP-71 format)` framing on the line above is slightly misleading — NIP-71's `p` tag is `["p", pubkey, optional_relay]`, with no fourth-element marker defined. The `'collaborator'` marker is a Divine-internal convention, not a NIP-71 one. The original comment may have nudged the marker toward feeling like informal styling rather than a wire-format invariant, which is part of why the divergence in #3373 surfaced only when divine-connect's parser flagged it.

Two follow-up ideas (separate PR, not asking for them here):

- Lift `'collaborator'` and `'wss://relay.divine.video'` into named constants in `nip71_migration.dart`. The same literal lives at `share_video_menu.dart:1743`, which is how the casing was wrong in two places at once.
- Reword the comment to something like `// Divine convention: 4th element is a Divine-internal role marker; NIP-71 specifies no marker.`

File: mobile/lib/widgets/share_video_menu.dart [hunk 2]
```diff
@@ -1740,7 +1740,7 @@ class _EditVideoDialogState extends ConsumerState<_EditVideoDialog> {
 
       // Add collaborator p-tags
       for (final pubkey in _collaboratorPubkeys) {
-        tags.add(['p', pubkey, 'wss://relay.divine.video', 'Collaborator']);
+        tags.add(['p', pubkey, 'wss://relay.divine.video', 'collaborator']);
```
Comment (realmeylisdev) [inline mobile/lib/widgets/share_video_menu.dart:1743]: **Pre-existing observation, not introduced by this PR.** The same 4-element tag is being hand-built here and at `video_event_publisher.dart:653`. That duplication is the structural reason the casing drifted in two places simultaneously — neither call site referenced a single source of truth.

Per `architecture.md`, tag construction belongs in the publisher rather than in a widget's State. A clean follow-up would (a) add `buildCollaboratorPTag(pubkey)` (or a publisher method that takes `collaboratorPubkeys`) and (b) have this dialog hand pubkeys to the publisher rather than pre-built tag arrays. That would close the duplication permanently and pull the publish work out of `_EditVideoDialogState`. Worth a follow-up issue; not a reason to hold this fix.

File: mobile/test/services/video_event_publisher_collaborator_tags_test.dart [hunk 3]
```diff
@@ -153,10 +153,20 @@ void main() {
...
+      // Verify no capitalized form is emitted
+      expect(
+        _containsTag(capturedTags, const [
+          'p',
+          collaboratorPubkey,
+          'wss://relay.divine.video',
+          'Collaborator',
+        ]),
+        isFalse,
+      );
```
Comment (realmeylisdev) [inline mobile/test/services/video_event_publisher_collaborator_tags_test.dart:169]: **Coverage gap, optional follow-up.** The fix at `share_video_menu.dart:1743` has no equivalent regression test — only the `publishDirectUpload` path is covered here. If the follow-up to extract a shared helper happens, both sites get covered for free via one helper test. If not, an `_EditVideoDialog` widget-level assertion of the same tag shape would guard the edit-dialog path against the same class of drift. Reasonable to defer either way given the widget-test setup cost.

**Review by realmeylisdev — APPROVED** [review]
Approving — change is tight and low-risk:

- Both emitter sites updated consistently.
- DM `['role', 'Collaborator']` correctly left alone — separate NIP-17 surface.
- Mobile's own parser at `packages/models/lib/src/video_event.dart:437-440` doesn't inspect the marker, so zero in-app behavior risk.
- Test gains a real negative assertion, not just a snapshot of current output.

Worth knowing for context: NIP-71 itself defines `["p", pubkey, optional_relay]` and **no fourth-element marker**. The `'collaborator'` marker is a Divine convention between mobile and divine-connect, not a NIP-71 requirement — that's what makes this a wire-format hygiene fix rather than a spec-compliance one.

A few inline notes left as follow-up context, none blocking this PR. Manual-test box in the description is still unchecked — worth a quick real-device confirmation before merge once CI clears.

**Comment by NotThatKindOfDrLiz** [comment]
Re-reviewed the current head. The diff is still the intended lowercase collaborator-marker fix, all checks are green, and the edit-path test follow-up is already tracked in #3687. Ready to ship.

File: mobile/lib/services/video_event_publisher.dart (hunk 1 above)
Comment (NotThatKindOfDrLiz) [reply mobile/lib/services/video_event_publisher.dart:653]: Tracked in #3704. I rolled the constant extraction and the NIP-71 comment clarification into one cleanup item so it stays as a single refactor instead of multiple tiny issues.

File: mobile/test/services/video_event_publisher_collaborator_tags_test.dart (hunk 3 above)
Comment (NotThatKindOfDrLiz) [reply mobile/test/services/video_event_publisher_collaborator_tags_test.dart:169]: The edit-path regression coverage thread is already tracked separately in #3689, so I did not open a duplicate issue for that one.

File: mobile/lib/widgets/share_video_menu.dart (hunk 2 above)
Comment (NotThatKindOfDrLiz) [reply mobile/lib/widgets/share_video_menu.dart:1743]: Tracked in #3704. I kept the DRY/helper extraction and the UI-state-to-publisher cleanup together as one structural follow-up.
