### PR TITLE
fix: fetch images for user search results

### LINKED ISSUE #1340: fix: missing profile photo on search results
### Summary

----------------------------------------------

!*** This comment has been flagged. Learn more ***!

AC555, 7 Feb 2026, 09:58

When you search for a profile, no profile photos are visible, and also not visible when you click the link through to look at the specific profile

### Environment

**Platform:** 
**Build Number:** 
**OS Version:** 

### Actual Result

----------------------------------------------

!*** This comment has been flagged. Learn more ***!

AC555, 7 Feb 2026, 09:58

When you search for a profile, no profile photos are visible, and also not visible when you click the link through to look at the specific profile

### LINKED ISSUE #1390: fix: Profile photos not visible
### Summary

User report from Alice: When you search for a profile, no profile photos are visible, and also not visible when you click the link through to look at the specific profile

### Environment

iOS

### Steps to Reproduce

Search for a profile. 

### Actual Result

No profile photos are showing. 

### Expected Result

Profile photos shown 

### Regression?

Yes

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by JohnWeidner**
## Description

Root cause found and fixed: UserProfile.== only compares pubkey and eventId, ignoring picture. When the BLoC enriched results with profile pictures, BLoC's Equatable comparison considered the new state equal to the old one and suppressed the emit — meaning enrichment would silently do nothing in production.

Changes made in this session:

[user_search_state.dart](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/blocs/user_search/user_search_state.dart) — Added profileVersion counter field to UserSearchState. Included in props, copyWith, and constructor.

[user_search_bloc.dart](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/blocs/user_search/user_search_bloc.dart) — Bumps profileVersion when enrichment actually changes results, forcing BLoC to recognize the state change.

[user_search_bloc_test.dart](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/test/blocs/user_search/user_search_bloc_test.dart) — Fixed dual UserProfile type mismatch by importing app_model.UserProfile for getCachedProfile mock return values. Updated props test to include profileVersion. Added wait to enrichment tests for transformer timing.

**Related Issue:** 
Closes #1390 
Closes #1340 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/blocs/user_search/user_search_bloc.dart [hunk 1]
```diff
@@ -25,19 +27,38 @@ EventTransformer<E> _debounceRestartable<E>() {
...
+/// After search results arrive, triggers background profile fetches for
+/// results missing pictures. When [UserProfileService] notifies that
+/// profiles have been updated, enriches the results with cached pictures.
 class UserSearchBloc extends Bloc<UserSearchEvent, UserSearchState> {
-  UserSearchBloc({required ProfileRepository profileRepository})
-    : _profileRepository = profileRepository,
-      super(const UserSearchState()) {
+  UserSearchBloc({
+    required ProfileRepository profileRepository,
+    UserProfileService? userProfileService,
```
Comment (omartinma) [inline mobile/lib/blocs/user_search/user_search_bloc.dart]: Can we rely only on ProfileRepository?
