### PR TITLE
fix(video-editor): store video clips in persistent storage instead of cache

### LINKED ISSUE #1116: fix: Saved clips appear greyed out and unusable after updates
### Summary

Older video clips in the library become corrupted or inaccessible, appearing as grey placeholders. This clips were before I made the update of the app.

### Environment

Build: 1.0.4(308) on iOS and 1.0.4(173) on Android
Device: Samsung A54 and Iphone Se v26.3

### Steps to Reproduce

User should have clips saved in the app
Open the app
Open the camera
Go to the edit field
Tap the 3 dots
Tap the select clips in library option
Look for the old clips

### Actual Result

Following an app update or new build installation, previously saved clips are displayed as greyed-out images and cannot be used or edited.

### Expected Result

Saved clips should remain valid, accessible, and playable across different app versions and builds.

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/a0836b90-daa9-47b5-a03d-39c321fd5517

### PR DESCRIPTION
**Pull request by hm21**
## Description

Video clips are now stored in persistent storage instead of the cache to ensure long-term availability across app updates.
A new cleanup mechanism was added to explicitly remove clips once they are no longer required, preventing unnecessary disk usage while keeping user data safe.

**Related Issue:** Closes #1116

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/providers/clip_manager_provider.dart [hunk 1]
```diff
@@ -63,11 +64,17 @@ class ClipManagerNotifier extends Notifier<ClipManagerState> {
...
+  /// Trigger autosave via VideoEditorProvider (debounced).
   void _triggerAutosave() {
     ref.read(videoEditorProvider.notifier).triggerAutosave();
   }
 
+  /// Force immediate autosave without debounce.
+  /// Use this before file cleanup to ensure references are updated.
+  Future<void> _forceAutosave() async {
+    await ref.read(videoEditorProvider.notifier).autosaveChanges();
+  }
```
Comment (erickzanardo) [inline mobile/lib/providers/clip_manager_provider.dart]: nit
```suggestion
  Future<void> _forceAutosave() => 
    ref.read(videoEditorProvider.notifier).autosaveChanges();
```

File: mobile/lib/services/video_recorder/camera/camera_macos_service.dart [hunk 2]
```diff
@@ -279,11 +280,16 @@ class CameraMacOSService extends CameraService {
         category: .video,
       );
 
-      // Use system temp directory which we have permission to write to
+      // Use documents directory for user-accessible persistent storage
+      final documentsDir = await getApplicationDocumentsDirectory();
+      final recordingsDir = Directory('${documentsDir.path}/recordings');
+      if (!await recordingsDir.exists()) {
```
Comment (erickzanardo) [inline mobile/lib/services/video_recorder/camera/camera_macos_service.dart]:
```suggestion
      if (!recordingsDir.existsSync()) {
```

There are some IO operations which their async methods are too slow compared to their sync counterparts, and it is preferable that their sync method are used

There is a lint rule about that, maybe we should enable it on the project to help us find those cases:
https://dart.dev/tools/linter-rules/avoid_slow_async_io#details

Comment (hm21) [reply mobile/lib/services/video_recorder/camera/camera_macos_service.dart]: Fixed in 7131212

Thanks for sharing that! Honestly, until now, I always thought there would be no big difference but i see i was wrong😅

I also agree that some lint rules could be helpful, such as warnings for missing const and other things...

File: mobile/lib/providers/clip_manager_provider.dart (hunk 1 above)
Comment (hm21) [reply mobile/lib/providers/clip_manager_provider.dart]: Fixed in 7131212
