### PR TITLE
fix: Pull to refresh on the explore screen

### LINKED ISSUE #195: Explore screen - P1 - swipe down to refresh does not display new videos and loading wheel is displayed infinitely
**Description:** On the explore screen if user swipes down to refresh for new content loading wheel is stuck infinitely and no new videos are displayed.
**App version:** 1.0.2-127
**Platform:** iOS 18.7
**Steps:**
1. Open the app by just tapping the 2 checkboxes and accepting the terms&conds, tap on Explore. 
2. Swipe down, loading wheel is displayed
**Actual result:** no new videos are displayed, loading wheel is stuck 
**Expected**: After a few seconds app should load new videos and loading wheel should disappear.

**Evidence**
https://github.com/user-attachments/assets/89f70344-ad02-4112-b5f1-2d7f48962c4b

### PR DESCRIPTION
**Pull request by erickzanardo**
Uses a `ref.refresh` to do the pull to refresh on the explore trending tab since it is a more reliable way of doing so.

Previous we were doing a `ref.invalidate` and reading the future to the provider to do that, and that future would never complete, causing the pull to refresh to remain on screen forever

Fixes #195

### CODE REVIEW

File: mobile/lib/screens/explore_screen.dart [hunk 1]
```diff
@@ -1156,8 +1156,7 @@ class _ExploreScreenState extends ConsumerState<ExploreScreen>
           await ref.read(popularNowFeedProvider.notifier).refresh();
         } else {
           // For Trending tab, refresh video events
-          ref.invalidate(videoEventsProvider);
-          await ref.read(videoEventsProvider.future);
+          final _ = await ref.refresh(videoEventsProvider);
```
Comment (erickzanardo) [inline mobile/lib/screens/explore_screen.dart:1159]: Note: Had to assign it to `_` to not get a lint warning that the return value had to be used. But in fact we don't really need to use the returned value since the refresh method will trigger the `watch` methods once it is done.
