### PR TITLE
fix: bunker url error handling

### LINKED ISSUE #1058: fix: no error displayed when attempting to Connect Identity with invalid bunker URL
### Summary

If you enter an invalid bunker:// url no error gets displayed and app appears to hang.

### Environment

app version 1.0.4+200 built from main branch on Jan 26.

### Steps to Reproduce

1. logout of app
2. check boxes on welcome screen
3. tap "have an account. log in"
4. tap "import nostr key"
5. type "bunker://bad?relay=bad" in the input field
6. tap "Connect Identity"

### Actual Result

app hangs.  A circular progress indicator is displayed but it is not rotating

### Expected Result

an error message should eventually be displayed.  If the user wants to give up, they should be able to.

### Regression?

No

### Evidence
<details>
  <summary>Video using bunker://bad?relay=bad</summary>

https://github.com/user-attachments/assets/f0f546de-6b1c-44b3-b26b-af056b59627b

</details>
_No response_

### PR DESCRIPTION
**Pull request by JohnWeidner**
## Description

Improved error handling related to using bunker URLs.  Previously, the app would hang in some scenarios and in others an error messages wouldn't be displayed until you got back to the welcome screen.

**Related Issue:** Closes #1058 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+        // This behavior was verified by code inspection and integration testing.
+        //
+        // Key change in the code:
+        //   onTimeout: () {
+        //     throw TimeoutException(
+        //       'Bunker request timed out after ${timeout}s',
+        //       Duration(seconds: timeout),
+        //     );
+        //   },
+        expect(true, isTrue); // Documentation test
```
Comment (Josh-Sanford) [inline mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart]: Do we need this documentation test?

File: mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+      });
+    });
+  });
+
+  group('NostrRemoteSigner reconnection logic', () {
+    // These tests document the expected reconnection behavior.
+    // Full integration tests would require mocking WebSocket connections.
+
+    test('max retries constant should be 5', () {
+      // This is a documentation test - the actual constant is private
```
Comment (Josh-Sanford) [inline mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart]: Same here

File: mobile/packages/nostr_sdk/lib/nip46/nostr_remote_signer.dart [hunk 3]
```diff
@@ -150,17 +168,37 @@ class NostrRemoteSigner extends NostrSigner {
...
             log('[NIP46] onMessage: failed to decrypt response');
           }
         }
-      } catch (err) {
-        log('[NIP46] onMessage error: $err');
+      } catch (err, stackTrace) {
+        log('[NIP46] onMessage error: $err\n$stackTrace');
+        // Re-throw to ensure the error is not silently swallowed
+        // This allows the caller to handle the error appropriately
+        rethrow;
```
Comment (Josh-Sanford) [inline mobile/packages/nostr_sdk/lib/nip46/nostr_remote_signer.dart:191]: Looks like the rethrow gets caught by relay_base.dart:116 so it won't crash the app. But I think the error ends up getting logged twice (here and in relay_base) and then nothing else happens with it. Is the rethrow actually needed, or could we just log and continue?

File: mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart (hunk 2 above)
Comment (JohnWeidner) [reply mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart]: deleted

File: mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart (hunk 1 above)
Comment (JohnWeidner) [reply mobile/packages/nostr_sdk/test/unit/nostr_remote_signer_test.dart]: deleted

File: mobile/packages/nostr_sdk/lib/nip46/nostr_remote_signer.dart (hunk 3 above)
Comment (JohnWeidner) [reply mobile/packages/nostr_sdk/lib/nip46/nostr_remote_signer.dart:191]: log and continue sounds bad as then we are not blocking the exception from reaching the caller.  The code in relay_base.dart line 116 is just listening to help with debugging. We might need to figure out how to test this error condition better and notify the user if appropriate.
