### PR TITLE
fix: video metadata not being updated

### LINKED ISSUE #371: fix:  Video Editing | P1 | Metadata changes do not persist after tapping Update
### Summary

When editing a video’s metadata (title, description, hashtag), the user can modify the fields and tap Update, but the changes are not saved. After returning to the video or reopening the edit screen, the old data is still displayed.

### Environment

pp version: 1.0.4 (140)

OS: iOS v26.2
Device: iPhone Se
Network: Wi-Fi

### Steps to Reproduce

- Open any published video.
- Tap Edit to modify metadata.
- Change the title, description, and/or hashtag.
- Tap Update.
- Return to the video OR reopen the edit screen.

### Actual Result

None of the edits are saved.

### Expected Result

- Metadata changes should be persisted after tapping Update.
- Returning to the video or reopening the edit screen should show the updated title, description, and hashtags.

### Regression?

Yes

### Evidence

https://github.com/user-attachments/assets/0eb04e9b-468d-41dc-a9d3-f57fba554250

### PR DESCRIPTION
**Pull request by hudson-proenca**
## Description
When you edited a video's title or hashtags, nothing updated until you manually refreshed the app. What I Did:
Added a callback system so when you edit a video, all the feeds update:
- Your profile videos
- Home feed
- Explore tabs (New Videos + Popular)
- The currently playing video

I think the video refreshing is still not ideal (user sees a loading spinner) - but I think that is out of scope.

**Related Issue:** Closes #371

https://github.com/user-attachments/assets/fc38c03d-ade0-46fc-95d7-6b38020ba536

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/models/video_event.dart [hunk 1]
```diff
@@ -544,6 +544,12 @@ class VideoEvent {
 
   // Vine-specific fields from NIP-71 spec
   final String? vineId; // 'd' tag - original vine ID for replaceable events
+
+  /// Stable identifier for addressable events (NIP-71).
+  /// Returns vineId (d-tag) if available, otherwise event ID.
+  /// For addressable events, vineId remains constant even when
+  /// metadata updates create new event IDs.
+  String get stableId => vineId ?? id;
```
Comment (erickzanardo) [inline mobile/lib/models/video_event.dart:552]: @ryzizub would love to hear your thoughts about this?

Comment (hudson-proenca) [reply mobile/lib/models/video_event.dart:552]: Same! We had this in a few places so I tried to centralize it
image

Comment (ryzizub) [reply mobile/lib/models/video_event.dart:552]: Yes its correct, for relay actually updates based on that so it should remain the same. Good job! :)
