### PR TITLE
fix(feed): prevent 2 px caption overflow on video action buttons

### LINKED ISSUE #3451: fix: 2 px bottom overflow on right-rail video action buttons
## Summary
Right-side action buttons on the For You feed (Like, Comment, Repost, Share, About) render the red Flutter `RenderFlex overflowed by 2.0 pixels on the bottom` debug ribbon whenever the caption slot under the icon is populated (count > 0, or a `labelWhenZero` like "Repost" / "Share" / "About").

## Steps to reproduce

1. Check out `main` and `flutter run` a debug build on iOS or Android.
2. Open the **For You** feed.
3. Scroll to any video whose action buttons have at least one caption visible — e.g. like count, comment count, or one of the static labels (`Repost`, `Share`, `About`).
4. Observe the red `BOTTOM OVERFLOWED BY 2.0 PX` ribbons stacked down the right rail (Like / Comment / Repost / Share / About).

100% reproducible — every video card with a populated caption slot trips it.

## Expected
No overflow. Buttons render cleanly.

## Actual
Each `VideoActionButton` reports a 2 px Column overflow:

```
RenderFlex overflowed by 2.0 pixels on the bottom.
The relevant error-causing widget was:
    Column Column:.../mobile/lib/widgets/video_feed_item/actions/video_action_button.dart:88:20
```

## Root cause
`VideoActionButton` wraps its content in a fixed `SizedBox(48, 48)`. The inner Column sums to **24** (icon) + **8** (`Padding(top: 8)`) + **16** (caption — `VineTheme.labelSmallFont` declares `height: 16/11`) = **48 px** nominal. Inter (loaded via `GoogleFonts.inter`) has intrinsic ascent/descent metrics that run the actual rendered line box ~2 px past the strut, so the column lays out at ~50 px and overflows the 48 px container.

The existing `'GestureDetector fills the 48x48 tap target'` widget test only exercises the default path (`count = 0`, no caption / no `labelWhenZero`), where `_VideoActionCaption` collapses to `SizedBox.shrink` — so the regression slipped through.

## Environment
- Branch: `main`
- Repro: iOS simulator and device, debug build (any video with a populated caption)

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary

- `VideoActionButton` wrapped its content in a fixed `SizedBox(48, 48)`, but Inter's intrinsic line metrics push `VineTheme.labelSmallFont`'s caption line box ~2 px past the 16 px strut, so each button on the For You right rail (Like / Comment / Repost / Share / About) overflowed by 2 px on the bottom whenever a caption was visible.
- Relaxed the inner constraint to a 48 px **minimum** height while keeping the width clamped to exactly 48: `SizedBox(width: 48) > ConstrainedBox(minHeight: 48) > Column(min, center)`. The button stays exactly 48 × 48 with no caption and grows to ~50 px only when a caption renders. The 48 px a11y tap-target minimum is preserved everywhere.
- Added two regression tests (`count > 0` and `labelWhenZero`) asserting no `RenderFlex` exception and `width == 48`, `height >= 48`. The existing `'48x48 tap target'` test still passes for the no-caption default path.

Closes #3451

## Test plan

- [ ] From `mobile/`: `flutter test test/widgets/video_feed_item/actions/` — all 66 tests should pass.
- [ ] On a debug build (iOS or Android), open the **For You** feed and confirm the red `BOTTOM OVERFLOWED BY 2.0 PX` ribbons no longer appear on the right-rail interaction buttons.
- [ ] Tap each of Like / Comment / Repost / Share / About and verify the existing actions still fire (the 48 px tap target is preserved).
- [ ] (Optional) Crank iOS Dynamic Type to the largest setting — buttons should now grow gracefully instead of clipping.

### CODE REVIEW

File: mobile/lib/widgets/video_feed_item/actions/video_action_button.dart [hunk 1]
```diff
@@ -11,7 +11,11 @@ import 'package:openvine/utils/string_utils.dart';
 ///
 /// Matches Figma node `15314:53971`: a 48x48 fully tappable container with a
 /// 24 icon centered over an 8 px gap and a label/small caption beneath it.
-/// The entire 48x48 region captures the tap — not just the icon.
+/// The 48x48 spec is enforced as a *minimum* size — the whole region captures
+/// the tap, but the column is allowed to grow past 48 px on the main axis
+/// when caption metrics push the natural height higher (Inter's intrinsic
+/// line box edges past the strut by ~2 px) or when system text scaling is
+/// in effect, so the content never clips.
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/actions/video_action_button.dart]: I think we should follow the `code_style.md` guidelines for comments here and keep this one shorter.

**Review by hm21 — APPROVED** [review]
LGTM just left a comment regarding a long doc comment

File: mobile/lib/widgets/video_feed_item/actions/video_action_button.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/widgets/video_feed_item/actions/video_action_button.dart]: Trimmed to two lines in dd61838 — kept the Figma node ref and the *minimum*-size rationale, dropped the strut/text-scaling detail.
