### PR TITLE
fix(auth): propagate key deletion failures instead of swallowing

### LINKED ISSUE #1389: fix: errors while deleting keys are ignored
### Summary

A code audit indicates that errors while signing out might be silently ignored, leading to the user thinking their nsec was removed from the device when in reality they are still on the device.

### Environment

main branch as of February 7, 2026

### Steps to Reproduce

This should not happen and currently there is not a known way to make it happen.  But a user's keys should be deleted when the user picks certain options from the Settings menu or picks "Start with a new identity" from the welcome screen.

### Actual Result

not applicable

### Expected Result

keys should be deleted

### Regression?

Unknown

### Evidence

Here's details from a code audit.

<h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">1.<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">SecureKeyStorage.deleteKeys()</code><span> </span>— swallows<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">false</code><span> </span>from platform (<a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/packages/nostr_key_manager/lib/src/secure_key_storage.dart#L440-L442" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">secure_key_storage.dart:440-442</a>)</h3><div class="codeBlockWrapper_-a7MRw" style="position: relative; margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button class="copyButton_CEmTFw copyButton_-a7MRw" title="Copy code" aria-label="Copy code to clipboard" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(30, 30, 30); border-color: rgb(69, 69, 69); border-style: solid; border-width: 0.6px; border-image: none 100% / 1 / 0 stretch; cursor: pointer; opacity: 0; display: flex; border-radius: 4px; justify-content: center; align-items: center; padding: 4px; transition: opacity 0.15s, background 0.15s; position: absolute; top: 4px; right: 4px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="copyIcon_CEmTFw"><path fill-rule="evenodd" d="M15.988 3.012A2.25 2.25 0 0 1 18 5.25v6.5A2.25 2.25 0 0 1 15.75 14H13.5v-3.379a3 3 0 0 0-.879-2.121l-3.12-3.121a3 3 0 0 0-1.402-.791 2.252 2.252 0 0 1 1.913-1.576A2.25 2.25 0 0 1 12.25 1h1.5a2.25 2.25 0 0 1 2.238 2.012ZM11.5 3.25a.75.75 0 0 1 .75-.75h1.5a.75.75 0 0 1 .75.75v.25h-3v-.25Z" clip-rule="evenodd"></path><path d="M3.5 6A1.5 1.5 0 0 0 2 7.5v9A1.5 1.5 0 0 0 3.5 18h7a1.5 1.5 0 0 0 1.5-1.5v-5.879a1.5 1.5 0 0 0-.44-1.06L8.44 6.439A1.5 1.5 0 0 0 7.378 6H3.5Z"></path></svg></button><pre style="overflow-x: auto; white-space: pre; box-sizing: border-box; border-radius: 4px; max-width: 100%; margin: 0px; padding: 8px;"><code class="language-dart" style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 0px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">final success = await _platformStorage.deleteKey(keyId: _primaryKeyId, ...);

if (!success) {
  _log.severe('Platform key deletion may have failed');
}
// Continues anyway — clears cache, logs "All keys deleted"
</code></pre></div><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">When <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">PlatformSecureStorage.deleteKey()</code> returns <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">false</code> (native MethodChannel failure, biometric auth cancelled, etc.), it only logs a warning. It <strong>does not throw</strong>. The caller (<code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">NostrKeyManager.clearKeys()</code> → <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">AuthService.signOut()</code>) has no idea the key is still on disk. The in-memory cache is cleared, so the app <em>appears</em> logged out, but the nsec remains in the Secure Enclave / Keychain.</p><h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2.<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">PlatformSecureStorage.deleteKey()</code><span> </span>— catches all exceptions, returns<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">false</code><span> </span>(<a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/packages/nostr_key_manager/lib/src/platform_secure_storage.dart#L490-L493" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">platform_secure_storage.dart:490-493</a>)</h3><div class="codeBlockWrapper_-a7MRw" style="position: relative; margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button class="copyButton_CEmTFw copyButton_-a7MRw" title="Copy code" aria-label="Copy code to clipboard" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(30, 30, 30); border-color: rgb(69, 69, 69); border-style: solid; border-width: 0.6px; border-image: none 100% / 1 / 0 stretch; cursor: pointer; opacity: 0; display: flex; border-radius: 4px; justify-content: center; align-items: center; padding: 4px; transition: opacity 0.15s, background 0.15s; position: absolute; top: 4px; right: 4px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="copyIcon_CEmTFw"><path fill-rule="evenodd" d="M15.988 3.012A2.25 2.25 0 0 1 18 5.25v6.5A2.25 2.25 0 0 1 15.75 14H13.5v-3.379a3 3 0 0 0-.879-2.121l-3.12-3.121a3 3 0 0 0-1.402-.791 2.252 2.252 0 0 1 1.913-1.576A2.25 2.25 0 0 1 12.25 1h1.5a2.25 2.25 0 0 1 2.238 2.012ZM11.5 3.25a.75.75 0 0 1 .75-.75h1.5a.75.75 0 0 1 .75.75v.25h-3v-.25Z" clip-rule="evenodd"></path><path d="M3.5 6A1.5 1.5 0 0 0 2 7.5v9A1.5 1.5 0 0 0 3.5 18h7a1.5 1.5 0 0 0 1.5-1.5v-5.879a1.5 1.5 0 0 0-.44-1.06L8.44 6.439A1.5 1.5 0 0 0 7.378 6H3.5Z"></path></svg></button><pre style="overflow-x: auto; white-space: pre; box-sizing: border-box; border-radius: 4px; max-width: 100%; margin: 0px; padding: 8px;"><code class="language-dart" style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 0px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">} on Exception catch (e) {
  _log.severe('Failed to delete key: $e');
  return false;  // Swallowed — caller sees false but doesn't throw
}
</code></pre></div><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Any exception from the native platform or fallback storage is caught and converted to a <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">false</code> return. Combined with issue #1 above, this means even a hard crash in the native deletion code gets silently swallowed.</p><h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">3.<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">AuthService.signOut()</code><span> </span>— catches everything, sets state to unauthenticated regardless (<a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/services/auth_service.dart#L1587-L1594" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">auth_service.dart:1587-1594</a>)</h3><div class="codeBlockWrapper_-a7MRw" style="position: relative; margin: 8px 0px; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button class="copyButton_CEmTFw copyButton_-a7MRw" title="Copy code" aria-label="Copy code to clipboard" style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(30, 30, 30); border-color: rgb(69, 69, 69); border-style: solid; border-width: 0.6px; border-image: none 100% / 1 / 0 stretch; cursor: pointer; opacity: 0; display: flex; border-radius: 4px; justify-content: center; align-items: center; padding: 4px; transition: opacity 0.15s, background 0.15s; position: absolute; top: 4px; right: 4px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon" class="copyIcon_CEmTFw"><path fill-rule="evenodd" d="M15.988 3.012A2.25 2.25 0 0 1 18 5.25v6.5A2.25 2.25 0 0 1 15.75 14H13.5v-3.379a3 3 0 0 0-.879-2.121l-3.12-3.121a3 3 0 0 0-1.402-.791 2.252 2.252 0 0 1 1.913-1.576A2.25 2.25 0 0 1 12.25 1h1.5a2.25 2.25 0 0 1 2.238 2.012ZM11.5 3.25a.75.75 0 0 1 .75-.75h1.5a.75.75 0 0 1 .75.75v.25h-3v-.25Z" clip-rule="evenodd"></path><path d="M3.5 6A1.5 1.5 0 0 0 2 7.5v9A1.5 1.5 0 0 0 3.5 18h7a1.5 1.5 0 0 0 1.5-1.5v-5.879a1.5 1.5 0 0 0-.44-1.06L8.44 6.439A1.5 1.5 0 0 0 7.378 6H3.5Z"></path></svg></button><pre style="overflow-x: auto; white-space: pre; box-sizing: border-box; border-radius: 4px; max-width: 100%; margin: 0px; padding: 8px;"><code class="language-dart" style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 0px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">} catch (e) {
  Log.error('Error during sign out: $e', ...);
  _lastError = 'Sign out failed: $e';
}
</code></pre></div><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">_keyStorage.deleteKeys()</code> <em>does</em> throw a <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">SecureKeyStorageException</code>, <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signOut()</code> catches it, logs it, and stores it in <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">_lastError</code> — but <strong>none of the callers check <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">_lastError</code></strong>:</p><ul style="padding-inline-start: 1.5em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/widgets/delete_account_dialog.dart#L304" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">delete_account_dialog.dart:304</a><span> </span>— calls<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signOut(deleteKeys: true)</code>, then immediately shows "Your account has been deleted" success snackbar</li><li><a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/screens/settings_screen.dart#L727" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">settings_screen.dart:727</a><span> </span>— calls<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signOut(deleteKeys: true)</code>, only catches for UI error display but the outer try/catch in<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signOut</code><span> </span>prevents the exception from reaching it</li><li><a href="vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/screens/welcome_screen.dart#L301" target="_blank" rel="noopener noreferrer" style="color: rgb(55, 148, 255);">welcome_screen.dart:301</a><span> </span>— calls<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signOut(deleteKeys: true)</code>, then proceeds to<span> </span><code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">signInAutomatically()</code><span> </span>with a<span> </span><em>new</em><span> </span>key, while the old nsec is still in secure storage</li></ul><hr style="font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Impact summary</h3>
Scenario | User sees | Reality
-- | -- | --
Account deletion | "Your account has been deleted" | nsec may still be on device
Settings "Delete Keys" | Redirected to welcome screen | nsec may still be on device
Welcome "Start Fresh" | Signs in with new identity | old nsec orphaned in Secure Enclave

<p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(37, 37, 38); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The core issue is that <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">SecureKeyStorage.deleteKeys()</code> treats a <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">false</code> return from the platform as non-fatal. It should throw so the failure propagates up to the UI, and the user can be warned that their key was not actually destroyed.</p>1. SecureKeyStorage.deleteKeys() — swallows false from platform ([secure_key_storage.dart:440-442](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/packages/nostr_key_manager/lib/src/secure_key_storage.dart#L440-L442))

final success = await _platformStorage.deleteKey(keyId: _primaryKeyId, ...);

if (!success) {
  _log.severe('Platform key deletion may have failed');
}
// Continues anyway — clears cache, logs "All keys deleted"
When PlatformSecureStorage.deleteKey() returns false (native MethodChannel failure, biometric auth cancelled, etc.), it only logs a warning. It does not throw. The caller (NostrKeyManager.clearKeys() → AuthService.signOut()) has no idea the key is still on disk. The in-memory cache is cleared, so the app appears logged out, but the nsec remains in the Secure Enclave / Keychain.

2. PlatformSecureStorage.deleteKey() — catches all exceptions, returns false ([platform_secure_storage.dart:490-493](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/packages/nostr_key_manager/lib/src/platform_secure_storage.dart#L490-L493))

} on Exception catch (e) {
  _log.severe('Failed to delete key: $e');
  return false;  // Swallowed — caller sees false but doesn't throw
}
Any exception from the native platform or fallback storage is caught and converted to a false return. Combined with issue #1 above, this means even a hard crash in the native deletion code gets silently swallowed.

3. AuthService.signOut() — catches everything, sets state to unauthenticated regardless ([auth_service.dart:1587-1594](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/services/auth_service.dart#L1587-L1594))

} catch (e) {
  Log.error('Error during sign out: $e', ...);
  _lastError = 'Sign out failed: $e';
}
If _keyStorage.deleteKeys() does throw a SecureKeyStorageException, signOut() catches it, logs it, and stores it in _lastError — but none of the callers check _lastError:

[delete_account_dialog.dart:304](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/widgets/delete_account_dialog.dart#L304) — calls signOut(deleteKeys: true), then immediately shows "Your account has been deleted" success snackbar
[settings_screen.dart:727](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/screens/settings_screen.dart#L727) — calls signOut(deleteKeys: true), only catches for UI error display but the outer try/catch in signOut prevents the exception from reaching it
[welcome_screen.dart:301](vscode-webview://0448oj8gk4lcb8tmqabitic31rj5idg10hh97fmjoshfgcti5d7r/mobile/lib/screens/welcome_screen.dart#L301) — calls signOut(deleteKeys: true), then proceeds to signInAutomatically() with a new key, while the old nsec is still in secure storage
Impact summary
Scenario	User sees	Reality
Account deletion	"Your account has been deleted"	nsec may still be on device
Settings "Delete Keys"	Redirected to welcome screen	nsec may still be on device
Welcome "Start Fresh"	Signs in with new identity	old nsec orphaned in Secure Enclave
The core issue is that SecureKeyStorage.deleteKeys() treats a false return from the platform as non-fatal. It should throw so the failure propagates up to the UI, and the user can be warned that their key was not actually destroyed.

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary

Closes #1389

Three layers of error swallowing meant that when platform key deletion failed (MethodChannel error, biometric auth cancelled, etc.), the app cleared in-memory state and told the user "keys deleted" — but the nsec could remain in the Secure Enclave / Keychain.

### Root cause

1. `SecureKeyStorage.deleteKeys()` checked the platform return value but only logged a warning when it was `false` — continued to clear cache and return successfully
2. `SecureKeyStorage.deleteBackupKey()` didn't capture the return value at all
3. `AuthService.signOut()` had an outer catch that swallowed everything, setting `_lastError` that no caller checked

### Changes (bottom-up, 4 layers)

- **`secure_key_storage.dart`** — `deleteKeys()` and `deleteBackupKey()`: clear in-memory cache **first** (unconditionally), then attempt platform deletion, throw `SecureKeyStorageException` with code `platform_deletion_failed` if it returns `false`
- **`nostr_key_manager.dart`** — `clearKeys()`: clear `_keyPair` and caches **before** the platform call so the app cannot reuse the key regardless of deletion outcome; let `SecureKeyStorageException` propagate
- **`auth_service.dart`** — `signOut()`: isolate key deletion in its own try/catch; all remaining cleanup (session, signers, OAuth, auth state → unauthenticated) proceeds regardless; rethrow after cleanup so callers can warn the user
- **`delete_account_dialog.dart`** — catch `SecureKeyStorageException` and show a distinct warning ("Account deleted, but your keys may not have been fully removed from this device")
- **`nostr_settings_screen.dart`** — catch `SecureKeyStorageException` with specific retry message

### Design decisions

- **Cache-first clearing**: In-memory state is wiped before platform deletion so the app can never reuse the key, even if the platform call fails. This is the correct security ordering.
- **Cleanup always completes**: `signOut()` transitions to `unauthenticated` regardless of key deletion outcome. The error is rethrown *after* all cleanup, so the user is never stuck in a zombie state.
- **Distinct UI for partial failure**: The user is told they're signed out but keys may remain — not a generic "sign out failed" error.

## Test plan

- [x] `secure_key_storage_delete_test.dart` — 3 new tests: `deleteKeys` throws on platform failure, cache cleared despite failure, `deleteBackupKey` throws on failure
- [x] `auth_service_signout_cleanup_test.dart` — 2 new tests: `signOut` rethrows after completing cleanup, succeeds normally when deletion works
- [x] All 25 existing key manager integration tests pass (no regressions)
- [x] `flutter analyze` clean, `dart format` clean
- [ ] Manual device test: happy path Remove Keys from settings
- [ ] Manual device test: happy path Delete Account
- [ ] Manual device test: simulated platform failure shows warning snackbar (see testing guide in PR comments)

### CODE REVIEW

File: mobile/lib/screens/settings/nostr_settings_screen.dart [hunk 1]
```diff
@@ -154,6 +156,24 @@ class _RemoveKeysTile extends StatelessWidget {
...
+          if (!context.mounted) return;
+          context.pop();
+
+          if (!context.mounted) return;
+          ScaffoldMessenger.of(context).showSnackBar(
+            const SnackBar(
+              content: Text(
+                'Signed out, but your keys may not have been '
+                'fully removed from this device. '
+                'Try removing keys again.',
```
Comment (hm21) [inline mobile/lib/screens/settings/nostr_settings_screen.dart]: Here we say “Try removing keys again” but we sign the user out. Wouldn’t it make more sense to only sign the user out once the keys are actually removed? Otherwise, the user has to sign in again just to retry.

File: mobile/lib/widgets/delete_account_dialog.dart [hunk 2]
```diff
@@ -304,20 +306,41 @@ Future<void> executeAccountDeletion({
...
+                color: keyDeletionWarning != null
+                    ? VineTheme.whiteText
+                    : VineTheme.backgroundColor,
+              ),
             ),
-            backgroundColor: VineTheme.vineGreen,
+            backgroundColor: keyDeletionWarning != null
+                ? VineTheme.error
+                : VineTheme.vineGreen,
           ),
```
Comment (hm21) [inline mobile/lib/widgets/delete_account_dialog.dart]: Can we use DivineSnackBar

**Review by hm21 — APPROVED** [review]
