### PR TITLE
fix: hashtag search

### LINKED ISSUE #1274: Search | Search for hashtags won't find any
### Summary

Using the search function for hashtags is not working, always returning _No hashtag found_ even when using existing hashtags like _vine_, _bts_ or _funny_ in the search input.

### Environment

- iPhone 17 running iOS 26 with app version (350) Wifi
- Pixel 10 running Android 16 with app version (217)(.abb) Wifi

### Steps to Reproduce

1. Go to search and type for example _bts_
2. Go to Hashtag tab and notice there are no results
3. Go to Explore > Popular and notice how the hashtags do exist

### Actual Result

Search function for hashtags never finds any existing hashtags

### Expected Result

Search function should be able to find existing hashtags

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/d7fe4947-3b44-41a9-820c-a436109f4d5e

### PR DESCRIPTION
**Pull request by omartinma**
## Description

**Related Issue:** Closes #1274

Note: this is fully working now on Staging, but changes are not in PROD yet. For more context about those backend changes https://github.com/divinevideo/divine-mobile/pull/1509#issuecomment-3884256729

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/blocs/hashtag_search/hashtag_search_bloc.dart [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+      return;
+    }
+
+    emit(state.copyWith(status: HashtagSearchStatus.loading, query: query));
+
+    try {
+      // Refresh stats to include any recently loaded videos
+      _hashtagService.refreshHashtagStats();
+
+      // Get results from both sources
```
Comment (omartinma) [inline mobile/lib/blocs/hashtag_search/hashtag_search_bloc.dart]: TODO: This part should be updated once backend is ready

File: mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart [hunk 2]
```diff
@@ -421,6 +422,70 @@ class FunnelcakeApiClient {
...
+    if (!isAvailable) {
+      throw const FunnelcakeNotConfiguredException();
+    }
+
+    final queryParams = <String, String>{
+      'limit': limit.toString(),
+    };
+
+    if (query != null && query.isNotEmpty) {
+      queryParams['q'] = query;
```
Comment (erickzanardo) [inline mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart]:
```suggestion
    if (query != null && query.isNotEmpty) {
      'q': query,
```

File: mobile/packages/hashtag_repository/lib/src/hashtag_repository.dart [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+  ///
+  /// Throws:
+  /// - [FunnelcakeNotConfiguredException] if the API is not configured.
+  /// - [FunnelcakeApiException] if the request fails with a non-success status.
+  /// - [FunnelcakeTimeoutException] if the request times out.
+  /// - [FunnelcakeException] for other errors.
+  Future<List<String>> searchHashtags({
+    String? query,
+    int limit = 20,
+  }) async {
```
Comment (erickzanardo) [inline mobile/packages/hashtag_repository/lib/src/hashtag_repository.dart]:
```suggestion
  }) {
```
