### PR TITLE
fix(feed): recover stalled videos in main native feed

### LINKED ISSUE #2550: fix(feed): recover stalled videos in main native feed
Auto-created from PR #2549.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2549
**Branch:** `fix/main-feed-stall-recovery`

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2550

## Summary
- Add a stall circuit breaker in `VideoFeedController` that detects videos stuck in repeated buffering cycles (ready → buffer → ready with zero position/duration) and auto-skips after 1 retry
- Wire `GlobalKey<PooledVideoFeedState>` in `VideoFeedView` for programmatic feed skip via `onVideoStalled` callback
- Consolidate all error-marking paths into `_markLoadError` with a `notifyStalled` flag so stuck/stale/slow-load failures also trigger auto-skip

## Test plan
- [x] `flutter test packages/pooled_video_player/test/controllers/video_feed_controller_test.dart` — 159 pass (new: circuit breaker allows 1 recovery then marks error)
- [x] `flutter test test/screens/feed/video_feed_page_test.dart` — 13 pass (new: PooledVideoFeed has GlobalKey for programmatic control)
- [x] `flutter analyze lib test packages/pooled_video_player` — no issues
- [ ] Manual: play feed, observe stalled videos auto-skip instead of hanging

### CODE REVIEW

File: mobile/packages/pooled_video_player/lib/src/controllers/video_feed_controller.dart [hunk 1]
```diff
@@ -458,8 +467,14 @@ class VideoFeedController extends ChangeNotifier {
     return VideoErrorType.generic;
   }
 
-  void _markLoadError(int index, [String? errorMessage]) {
+  void _markLoadError(
+    int index, [
+    String? errorMessage,
+    bool notifyStalled = false,
+  ]) {
```
Comment (hm21) [inline mobile/packages/pooled_video_player/lib/src/controllers/video_feed_controller.dart]: nit for better readability:


```suggestion
  void _markLoadError({
   required int index, 
    String? errorMessage,
    bool notifyStalled = false,
  }) {
```
