### PR TITLE
fix(notifications): port consolidated unread badge logic to NotificationFeedBloc

### LINKED ISSUE #3487: fix(notifications): port consolidated unread badge logic to NotificationFeedBloc
## Summary
PR #3472 fixes the inbox badge mismatch on the Riverpod notifications path by deriving the badge count from the consolidated visible list instead of the server raw unreadCount.

## Follow-up needed
The gated/off migration target in notification_feed_bloc.dart still reads and mutates unreadCount directly, which can silently reintroduce the same badge mismatch when that stack is enabled.

## Scope
- Audit notification_feed_bloc.dart unread-count handling
- Port the same consolidated-visible-list contract used in PR #3472
- Add/adjust tests so the BLoC path matches the Riverpod path for duplicate follow notifications

## Context
Split from PR #3472 after approval so the current mitigation can merge independently while the migration parity work stays tracked.

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Description

PR #3472 corrected the inbox unread badge on the **Riverpod** notifications path by deriving the count from the consolidated visible list instead of `state.unreadCount` (which the server inflates whenever a follower republishes Kind 3 — every contact-list edit emits one notification row per existing follow, and `unread_count` counts each duplicate).

The same gap existed in `NotificationFeedBloc` — the gated/off migration target. This PR ports the contract so flipping the migration gate cannot reintroduce the mismatch.

**Related Issue:** Closes #3487
**Upstream tracking:** [divinevideo/divine-funnelcake#234](https://github.com/divinevideo/divine-funnelcake/issues/234) (server-side Kind 3 republish dedup — still OPEN; the new `unreadBadgeCount` getter carries the same `TODO(funnelcake#234)` revert pointer as the Riverpod path)

## Type of Change

- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)

## Changes

- `NotificationFeedState.unreadBadgeCount` — new derived getter that counts unread items in the post-consolidation list. `unreadCount` stays as the server-truth diagnostic / revert target.
- `_onMarkAllRead` now flips `isRead: true` on every visible notification so the derived badge clears immediately, matching `RelayNotifications.markAllAsRead`.
- `_onItemTapped` flips `isRead` on tapped `GroupedNotification` rows too (previously a no-op on grouped items).
- New `GroupedNotification.copyWith`, mirroring `SingleNotification.copyWith`, so the BLoC can flip read state on either subtype.

### Automated

- [x] Four new `unreadBadgeCount` cases mirror PR #3472's contract: 5 follow rows from 2 distinct pubkeys + server `unreadCount: 5` → 2; empty list + server `unreadCount: 42` → 0; mixed read/unread → only unread; grouped + single mix with one read group excluded → 2.
- [x] `_onMarkAllRead` now asserts the list flip (singles + grouped) and the no-op case (already-read).
- [x] New `GroupedNotification.copyWith` tests in `models`.
- [x] `dart format` / `flutter analyze lib test integration_test` clean.
- [x] `flutter test test/notifications` — 53 / 53 pass.
- [x] `flutter test packages/notification_repository` — 44 / 44 pass.
- [x] `flutter test packages/models` (notification_item_test.dart) — 29 / 29 pass.

### Manual (real device)

The inbox badge UI currently still reads the Riverpod provider (the path PR #3472 already fixed); the BLoC contract is verified by unit tests until the migration cutover. What you can directly observe on device today is the **list behavior**:

1. **Mark-all-read clears unread dots.** Generate fresh unread notifications, open the inbox → Notifications tab. Every "unread" dot disappears immediately. Pop and re-open — items stay read, no flicker back.
2. **Tapping a grouped notification clears its dot.** Find a "X and N others liked your video" row, tap it. Dot disappears, navigation occurs, dot stays cleared after back-nav.
3. **Tapping a single notification still clears its dot** (regression check). Standard behavior unchanged.
4. **Real-time arrival adds an unread row.** With the screen foregrounded, have someone like / follow / comment on you. New row appears at top with an unread dot; tapping clears it.
5. **Kind 3 republish dedup** (regression check). Have a teammate follow → unfollow → follow you in quick succession, then pull-to-refresh. Single row, not three.

To eyeball the badge digit itself before the migration cutover, temporarily swap `relayNotificationUnreadCountProvider` in `mobile/lib/screens/inbox/inbox_view.dart:63` for a `BlocSelector<NotificationFeedBloc, NotificationFeedState, int>(selector: (s) => s.unreadBadgeCount, …)`. **Do not commit this** — it's a local probe; revert before pushing.

### Failure signals to watch for

| Symptom on device | Likely cause |
|---|---|
| Unread dots persist after opening notifications | `_onMarkAllRead` not flipping `isRead` (regression in this PR) |
| Tapping grouped notif doesn't clear its dot | `GroupedNotification.copyWith` not wired into `_onItemTapped` |
| Tapping single notif doesn't clear its dot | Regression in pre-existing `SingleNotification` path |
| Multiple rows from the same user after a Kind 3 burst | `_consolidateFollows` regression in `notification_repository` (out of scope for this PR — rare; flag separately) |
| Badge digit on bottom nav doesn't match list | Today: Riverpod path issue (not this PR). After migration: `NotificationFeedBloc.state.unreadBadgeCount` consumer is wired wrong. |

### CODE REVIEW

File: mobile/test/notifications/bloc/notification_feed_bloc_test.dart [hunk 1]
```diff
@@ -324,11 +324,34 @@ void main() {
           ),
         ],
       );
+
+      blocTest<NotificationFeedBloc, NotificationFeedState>(
+        'marks a tapped grouped notification as read and decrements unread',
```
Comment (NotThatKindOfDrLiz) [inline mobile/test/notifications/bloc/notification_feed_bloc_test.dart:329]: This closes the real regression gap in the PR. The grouped path now has the same local read-state coverage as the single-notification path, so a future fallback to `GroupedNotification() => n` will fail loudly.

File: mobile/lib/notifications/bloc/notification_feed_state.dart [hunk 2]
```diff
@@ -43,6 +47,20 @@ final class NotificationFeedState extends Equatable {
...
+  /// same N followers can produce 2N+ rows after a few contact-list edits,
+  /// even though [NotificationRepository] has already merged them on screen
+  /// via `_consolidateFollows`. Counting unread items in the
+  /// post-consolidation list keeps the badge in sync with what the user
+  /// actually sees.
+  ///
+  // TODO(funnelcake#234): Revert to [unreadCount] once server-side Kind 3
+  // republish dedup ships and the visible list and server count agree
+  // again. Tracking: divinevideo/divine-funnelcake#234.
+  int get unreadBadgeCount => notifications.where((n) => !n.isRead).length;
```
Comment (NotThatKindOfDrLiz) [inline mobile/lib/notifications/bloc/notification_feed_state.dart:62]: The docstring and revert pointer make the temporary split between `unreadBadgeCount` and server `unreadCount` explicit. That should keep the BLoC and Riverpod implementations easy to reconcile once funnelcake#234 lands.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
LGTM. The unread badge port is aligned with the Riverpod fix, the grouped-tap regression is now covered, and the mark-all-read tests pin the local badge behavior clearly enough to keep the migration gate flip from reintroducing the old unread inflation bug.

File: mobile/test/notifications/bloc/notification_feed_bloc_test.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/test/notifications/bloc/notification_feed_bloc_test.dart:329]: Confirmed — the new `blocTest` asserts the tapped grouped row's `isRead` flips to true and `unreadBadgeCount` decrements, so a regression back to the grouped no-op path would fail loudly.

File: mobile/lib/notifications/bloc/notification_feed_state.dart (hunk 2 above)
Comment (realmeylisdev) [reply mobile/lib/notifications/bloc/notification_feed_state.dart:62]: Yes — the `TODO(funnelcake#234)` on `unreadBadgeCount` mirrors the same revert pointer on the Riverpod side (`relayNotificationUnreadCountProvider` from #3472), so both paths collapse back to `unreadCount` together once server-side Kind 3 republish dedup ships.
