### PR TITLE
fix(video): treat relay acceptance as publish success

### LINKED ISSUE #2708: fix(video): false upload failure when relay accepts event but read-back confirmation times out
## Summary

Video uploads are falsely reported as failed even though the relay has already accepted and is delivering the event. The root cause is that `VideoEventPublisher.publishDirectUpload` treats a timed-out read-back confirmation as a publish failure, when in reality the relay already acknowledged receipt.

## Current Behavior

1. User publishes a video event.
2. `_publishEventToNostr` succeeds — the relay accepts the event (`sendResult == true`).
3. `_confirmEventVisibleOnRelays` times out (relay indexing lag, slow query, etc.).
4. The publisher treats this as a **failure**: status is set back to `readyToPublish`, the local feed is not updated, and the user sees an error.

## Expected Behavior

Once the relay accepts the event, the publish should be treated as **successful**. The visibility read-back confirmation is useful diagnostics but should not gate the success/failure outcome.

## Impact

- Users see false "upload failed" errors on successful publishes.
- Users may retry uploads that already succeeded, creating duplicates.
- Erodes trust in the upload flow reliability.

## Reproduction

Occurs in production when relays have indexing lag — the event is accepted via WebSocket OK but is not immediately queryable via `queryEvents`.

## Affected Code

- `mobile/lib/services/video_event_publisher.dart` — `publishDirectUpload` retry loop

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2708

## Summary

- Treat relay event acceptance (`sendResult == true`) as publish success, regardless of whether the read-back visibility confirmation succeeds.
- Demote `_confirmEventVisibleOnRelays` failure from a hard error to a warning log — relay indexing lag should not fail the upload.
- Add a dedicated test for the actual failure path (relay rejects the event on all attempts).

## Changes

| File | Change |
|------|--------|
| `video_event_publisher.dart` | Once relay accepts, set `publishResult = true`; log warning if read-back times out instead of failing |
| `video_event_publisher_publish_confirmation_test.dart` | Update existing test to expect success on accept-but-no-readback; add new test for relay rejection |

## Root Cause

The retry loop in `publishDirectUpload` was gating success on `_confirmEventVisibleOnRelays`, which queries the relay to verify the event is indexed. Relay indexing lag caused this read-back to time out, making the publisher treat an already-accepted event as a failure.

## Test Plan

- [x] Existing confirmation test updated — relay accepts but read-back fails → now expects `true`
- [x] New test — relay rejects on all attempts → expects `false`
- [ ] Manual: publish a video and verify no false failure toast

### CODE REVIEW

File: mobile/lib/services/video_event_publisher.dart [hunk 1]
```diff
@@ -934,20 +934,32 @@ class VideoEventPublisher {
...
+
+          final confirmed = await _confirmEventVisibleOnRelays(event);
+          if (!confirmed) {
+            Log.warning(
+              '⚠️ Event accepted by relay but not yet queryable '
+              '(attempt $attempt): ${event.id}',
+              name: 'VideoEventPublisher',
+              category: LogCategory.video,
+            );
+          }
```
Comment (hm21) [inline mobile/lib/services/video_event_publisher.dart]: I wonder if it still makes sense to keep that method when we’re only logging it now. 
Alternatively, we could add a backoff retry if we still want to verify that it’s published instead of just logging it.
