### PR TITLE
fix: added a Semantics label to user search results

### LINKED ISSUE #716: feat: Add semantic label to Profile icon in the Search results, Users tab
In order to validate profile search results, we must check the existence and interact with the profile listed:

The automation framework is unable to tap on a profile listed on the search results.Adding a semantic label to it will solve the issue. 

Feel free to add a meaningful name you consider. 

Image

### PR DESCRIPTION
**Pull request by JohnWeidner**
## Description

To assist in QA testing, each user in the search result list of users is wrapped with a Semantics value

**Related Issue:** Closes #716 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/widgets/user_profile_tile.dart [hunk 1]
```diff
@@ -32,86 +32,94 @@ class UserProfileTile extends ConsumerWidget {
...
-                        ),
-                      ),
-                      if (profile?.about != null && profile!.about!.isNotEmpty)
+                  child: UserAvatar(imageUrl: profile?.picture, size: 48),
+                ),
+                const SizedBox(width: 12),
+
+                // Name and details
+                Expanded(
+                  child: GestureDetector(
```
Comment (B0berman) [inline mobile/lib/widgets/user_profile_tile.dart]: Instead of two gesture detectors why not only one above the Row?

Comment (JohnWeidner) [reply mobile/lib/widgets/user_profile_tile.dart]: I agree and made the change.  (Originally, I was just adding the Semantics that was needed for testing and did not want to change the original code more than was necessary.)

**Review by rabble — APPROVED** [review]
**Smoke tested and approved.**

Verified on iPhone 16 Pro simulator:
- User tiles display correctly with avatar, name, and bio
- Tapping anywhere on the tile navigates to the user profile (consolidated GestureDetector works as expected)
- Semantics wrapper properly applied for QA automation testing

Minor observation: The Semantics label uses `betterDisplayName('Unknown')` while the visible text uses `bestDisplayName ?? 'Loading...'` - these could theoretically show different values during loading states, but it's not a blocker.

Good refactor consolidating the two GestureDetectors into one per @B0berman's feedback.
