### PR TITLE
fix: newly followed user videos in home feed

### LINKED ISSUE #798: fix: Home feed videos | P0 | Not all videos from a newly followed user are listed
### Summary

After following user Lele you can see in the profile 6 videos. If you keep scrolling it bounces meaning that you already viewed all Lele’s videos. If you switch the app section and then browse back new videos from Lele are loaded and you can keep scrolling till view them all.

### Environment

1.0.4 -200 #34 
iOS sim
Wifi

### Steps to Reproduce

1. With a fresh user navigate to explore and tap on a Lele video
2. Tap on follow and navigate to home: Lele videos are displayed
3. Swipe to the bottom till the bottom is reached: You were able to watch 6 videos

### Actual Result

No more videos from Lele are loaded/displayed.

### Expected Result

Lele has 14 videos and user should be able to watch 'em all.
After reaching the bottom if you switch the app screen, lets say you navigate to the explore screen and navigate back to home, more videos are loaded

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/109a7692-0afa-4ec0-afb2-46647d066242

### PR DESCRIPTION
**Pull request by andyhorn**
## Description

Seeds the home feed with newly followed user videos.

This fixes a bug where newly followed user videos weren't being added to the home feed until after refreshing.

**Related Issue:** Closes #798 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/services/video_event_service.dart [hunk 1]
```diff
@@ -2707,14 +2707,212 @@ class VideoEventService extends ChangeNotifier {
...
+        category: LogCategory.video,
+      );
+
+      // Add videos to home feed list
+      for (final video in videosToSeed) {
+        homeFeedList.add(video);
+      }
+
+      // Sort by creation time (newest first)
+      homeFeedList.sort((a, b) {
```
Comment (ryzizub) [inline mobile/lib/services/video_event_service.dart]: nit: same sorting is in `seedHomeFeedFromDiscoveryCache` seems to me like a good private extension here on top of the list

**Review by ryzizub — APPROVED** [review]
