### PR TITLE
fix: handle missing profile info for new users

### LINKED ISSUE #421: [TC-AUTH-035] Reserved name detection messaging
## Test Case: TC-AUTH-035

**Section:** 1. Authentication & Login
**Feature:** 1.7 Name Service & Reserved Name Management
**Priority:** P0
**Status:** nan
**Size:** M
**Estimate:** 2 days
**Release:** MVP Rel 2

---
*Imported from QA Test Case Tracker*

### LINKED ISSUE #423: [TC-AUTH-032] Username selection during registration
## Test Case: TC-AUTH-032

**Section:** 1. Authentication & Login
**Feature:** 1.7 Name Service & Reserved Name Management
**Priority:** P0
**Status:** nan
**Size:** M
**Estimate:** 2 days
**Release:** MVP Rel 2

---
*Imported from QA Test Case Tracker*

### PR DESCRIPTION
**Pull request by Josh-Sanford**
## Summary
- Show profile header for new users who don't have profile data yet (own profile)
- Prevent flash of "Not a profile route" error during navigation transitions
- Handle null/empty displayName gracefully in followers/following screens (shows "Followers" instead of "'s Followers")

Screenshot 2025-12-23 at 5 37 13 AM

Fixes #423 
Fixes #421 

## Test plan
- [x] New tests added for null displayName fallback
- [x] New tests added for empty string displayName fallback
- [x] Manual test: Create new account, verify profile header shows

### CODE REVIEW

File: mobile/lib/screens/followers_screen.dart [hunk 1]
```diff
@@ -116,9 +116,13 @@ class _FollowersScreenState extends ConsumerState<FollowersScreen>
 
   @override
   Widget build(BuildContext context) {
+    final appBarTitle = widget.displayName?.isNotEmpty == true
```
Comment (calevgian100) [inline mobile/lib/screens/followers_screen.dart:119]: No need to do `== true`

This should work:

```
final appBarTitle = widget.displayName?.isNotEmpty 
        ? '${widget.displayName}\'s Followers'
        : 'Followers';
```

File: mobile/lib/screens/following_screen.dart [hunk 2]
```diff
@@ -147,9 +147,13 @@ class _FollowingScreenState extends ConsumerState<FollowingScreen>
 
   @override
   Widget build(BuildContext context) {
+    final appBarTitle = widget.displayName?.isNotEmpty == true
```
Comment (calevgian100) [inline mobile/lib/screens/following_screen.dart:150]: Same here!

File: mobile/lib/screens/profile_screen_router.dart [hunk 3]
```diff
@@ -526,14 +527,17 @@ class _ProfileScreenRouterState extends ConsumerState<ProfileScreenRouter>
...
-    final profilePictureUrl = profile.picture;
-    final displayName = profile.bestDisplayName;
+
+    final profilePictureUrl = profile?.picture;
+    final displayName = profile?.bestDisplayName;
     final hasCustomName =
-        profile.name?.isNotEmpty == true ||
-        profile.displayName?.isNotEmpty == true;
+        profile?.name?.isNotEmpty == true ||
+        profile?.displayName?.isNotEmpty == true;
```
Comment (calevgian100) [inline mobile/lib/screens/profile_screen_router.dart:538]: Same here, we can remove the `== true` on both cases

Comment (Josh-Sanford) [reply mobile/lib/screens/profile_screen_router.dart:538]: Thanks for the comments! Hmm this was actually here before my changes, but it gives an error if I remove the `== true`: 
_A nullable expression can't be used as a condition.
Try checking that the value isn't 'null' before using it as a condition._ 
As far as I understand this is a check to make sure it isn't null AND isn't empty, and is equivalent to `profile?.name != true && profile?.name?.isNotEmpty`

File: mobile/lib/screens/followers_screen.dart (hunk 1 above)
Comment (Josh-Sanford) [reply mobile/lib/screens/followers_screen.dart:119]: Screenshot 2025-12-23 at 12 49 36 PM
🤔 
I think what I have is technically equivalent to `widget.displayName != null && widget.displayName.isNotEmpty`. Removing the `== true` returns `bool?` which can't be used in a ternary condition. Should I change it so it's easier to read?
