### PR TITLE
fix(profile): prevent that the layout shift when stats loading

### LINKED ISSUE #3674: fix(profile): prevent that the layout shift when stats loading
Auto-created from PR #3673.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3673
**Branch:** `fix/profile-layout-shift`

### PR DESCRIPTION
**Pull request by hm21**
Closes #3674

## Description

Until now, when a user opened their own or another profile for the first time and the data wasn’t cached, the profile stats were completely hidden until the data finished loading, which caused the entire layout to shift. This PR changes that behavior by introducing a skeleton loader.

| Before | After |
|--------|-------|
| <video src="https://github.com/user-attachments/assets/61d6011d-1a0d-4544-aec1-765712645a78" controls width="300"></video> | <video src="https://github.com/user-attachments/assets/be670e28-1755-41ac-b5da-828a84f26da7" controls width="300"></video> |

**Related Issue:** Closes # or Relates to #

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/widgets/profile/profile_header_widget.dart [hunk 1]
```diff
@@ -654,59 +656,115 @@ class _BannerImage extends StatelessWidget {
...
         ),
     ];
 
-    return Row(
-      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
-      children: [
-        for (int i = 0; i < columns.length; i++) ...[
-          if (i > 0) const _StatDivider(),
-          columns[i],
+    return Skeletonizer(
```
Comment (realmeylisdev) [inline mobile/lib/widgets/profile/profile_header_widget.dart:756]: All other `Skeletonizer` call sites in `mobile/lib/` pass `effect: vineSkeletonEffect` from `divine_ui` — `comment_skeleton_loader.dart:19`, `tags_section.dart:144`, `lists_section.dart:271`, `videos_section.dart:265`, `people_section.dart:146`. Worth passing it here too so the shimmer uses `VineTheme.skeletonBase` / `skeletonHighlight` / `skeletonDuration` instead of the package default.

File: mobile/lib/widgets/profile/profile_header_widget.dart [hunk 2]
```diff
@@ -654,59 +656,115 @@ class _BannerImage extends StatelessWidget {
...
+  /// Two-digit placeholder painted behind the Skeletonizer shimmer while the
+  /// real stats load. The number itself is never visible — it only sets the
+  /// width of the skeleton bar.
+  static const _skeletonPlaceholderCount = 99;
+
+  Timer? _timer;
+  bool _timeoutExpired = false;
+
+  @override
+  void initState() {
```
Comment (realmeylisdev) [inline mobile/lib/widgets/profile/profile_header_widget.dart:690]: The timer is started once here. Two prop-change cases aren't covered:\n\n1. If `widget.profileStats` flips non-null → null after the first frame — e.g. when `profileRepositoryProvider` rebuilds on auth flip, same identity-flip pattern as `state_management.md` § "Bridging Riverpod-provided dependencies" — no timer is started for the second loading window, so `Skeletonizer(enabled: isLoading && !_timeoutExpired)` shimmers indefinitely.\n2. If `widget.userIdHex` changes while State is reused, `_timeoutExpired = true` carries over from the previous profile and the new one renders em-dash placeholders with no skeleton phase.\n\nA `didUpdateWidget` that resets the timer when `userIdHex` changes or `profileStats` transitions non-null → null would close both.

File: mobile/test/widgets/profile/profile_header_widget_test.dart [hunk 3]
```diff
@@ -363,24 +363,82 @@ void main() {
...
+            ),
+          );
+          // One frame only — the 7-second skeleton timer has not fired yet.
+          await tester.pump();
+
+          // All four column labels are in the tree, rendered as skeletons.
+          expect(find.text('Followers'), findsOneWidget);
+          expect(find.text('Following'), findsOneWidget);
+          expect(find.text('Likes'), findsOneWidget);
+          expect(find.text('Loops'), findsOneWidget);
```
Comment (realmeylisdev) [inline mobile/test/widgets/profile/profile_header_widget_test.dart:423]: This test passes if the four labels are present, but it doesn't actually verify the skeleton is active — would still pass if `Skeletonizer.enabled` were always `false`. Worth tightening with:\n\n```dart\nfinal s = tester.widget<Skeletonizer>(find.byType(Skeletonizer));\nexpect(s.enabled, isTrue);\n```\n\nA symmetric `expect(s.enabled, isFalse)` after the 8-second pump in the timeout test above would lock both ends of the contract.

File: mobile/lib/widgets/profile/profile_header_widget.dart (hunk 2 above)
Comment (hm21) [reply mobile/lib/widgets/profile/profile_header_widget.dart:690]: Thanks for the detailed analysis — both cases are theoretically sound, but neither is reachable in the current codebase:

Case 1 (non-null → null flip): The profileStats prop flows one-way: null while loading, then non-null once data arrives — it never resets to null mid-lifecycle. On an auth flip, the parent uses the ValueKey-on-identity pattern (per state_management.md § "Bridging Riverpod-provided dependencies"), which remounts the entire widget subtree. That gives _ProfileStatsRow a fresh State with initState running against profileStats == null, so the timer starts correctly. A mid-lifecycle non-null → null transition has no code path that produces it.

Case 2 (userIdHex changes): Profile navigation is always a context.push(...) to a new route, which constructs a new widget tree and a new State. No parent recycles the same _ProfileStatsRow instance with a different pubkey.

Skipping didUpdateWidget for now since there's no real reproduction path for either case. Happy to add it if you can point to a code path that triggers one of these transitions.

**Comment by hm21** [comment]
@realmeylisdev thanks for the review. All fixed and one comment i explain the reason why not add a extended logic and keep it simple for now.

**Review by realmeylisdev — APPROVED** [review]
LGTM — solid fix. All 37 tests in `profile_header_widget_test.dart` pass locally; reviewer threads addressed.

Nits (take or leave):

- **Placeholder width.** `_skeletonPlaceholderCount = 99` formats to `"99"` (~25 px), but real values can render `"1.2K"` / `"12.4M"`. Because the row uses `spaceEvenly` + `MainAxisSize.min`, dividers will reposition slightly when stats arrive — in-row jiggle, not a screen-level shift. A fixed-width sizing of the column while loading, or a wider placeholder, would close it.
- **7-second timeout — add a "why" comment.** The dartdoc explains *what*; a one-liner near `_skeletonTimeout` recording *why 7s* (e.g. "covers slow relay round-trips on cold start; beyond this we'd rather show em-dashes than shimmer forever") makes the choice durable.
- **`didUpdateWidget` thread.** Your response holds for today's call sites — fine to leave un-added. Consider a one-line comment near `initState` recording the assumption ("relies on parent to remount on `userIdHex` change") so a future caller that breaks it surfaces loudly.
- **Test gap (symmetric).** New tests assert `Skeletonizer.enabled == true` before timeout and `== false` after. Worth one more assertion on the happy path (`profileStats` non-null at mount) that `Skeletonizer.enabled == false` from the first frame, to lock both ends of the contract.
