### PR TITLE
fix: show truncated npub instead of Loading for users without profiles

### LINKED ISSUE #804: fix: Videos | P0 | username "Loading..."
### Summary

Username not loading 

Image

### Environment

App v 200
iPhone 16 pro

### Steps to Reproduce

Try to watch a video and see if username loads 

### Actual Result

As above 

### Expected Result

User name to load 

### Regression?

Yes

### Evidence

Attached above

### PR DESCRIPTION
**Pull request by Josh-Sanford**
## Summary

- Users without a Kind 0 profile event were seeing "Loading..." indefinitely
- Now shows truncated npub (e.g., `npub1abc...xyz`) as fallback

## Changes

- **nostr_key_utils.dart**: Added `truncateNpub()` utility method
- **video_explore_tile.dart**: Use truncated npub for missing/error profile states
- **user_profile_tile.dart**: Use truncated npub instead of "Loading..." fallback
- **video_feed_item.dart**: Fixed author display and repost banner (was using raw `substring(0,8)`)

https://github.com/user-attachments/assets/063491d4-2cc6-462d-8566-fb963cb24d32

Closes #804

### CODE REVIEW

File: mobile/lib/utils/nostr_key_utils.dart [hunk 1]
```diff
@@ -50,4 +50,21 @@ class NostrKeyUtils {
       return false;
     }
   }
+
+  /// Create a truncated npub for display (e.g., "npub1abc...xyz")
+  ///
+  /// Converts a hex pubkey to npub format and truncates for UI display.
+  /// Shows first 10 characters + "..." + last 6 characters.
+  /// Use this when displaying usernames for users without a Kind 0 profile.
+  static String truncateNpub(String hexPubkey) {
```
Comment (JohnWeidner) [inline mobile/lib/utils/nostr_key_utils.dart:59]: Can we delete the makeTruncatedNpub from user_profile.dart and use this method instead?

Comment (Josh-Sanford) [reply mobile/lib/utils/nostr_key_utils.dart:59]: Absolutely
