### PR TITLE
fix(explore): restore refresh recovery for empty feeds

### LINKED ISSUE #3702: fix(explore): restore refresh recovery for empty feeds
Auto-created from PR #3701.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3701
**Branch:** `fix/feed-refresh-retry`

### PR DESCRIPTION
**Pull request by rabble**
Closes #3702

## Summary
- add a shared feed refresh wrapper for scrollable feeds and standalone empty/error states
- make Classics empty/unavailable/error states pull-refreshable and auto-recheck once when empty
- keep existing Classics videos when refresh fails or the API returns an empty page
- wire stranded error/unavailable states for New, Popular, and For You through the shared refresh view

## Verification
- flutter test test/widgets/feed_refresh_control_test.dart test/widgets/composable_video_grid_test.dart test/providers/feed_refresh_helpers_test.dart test/providers/classic_vines_refresh_test.dart test/providers/feed_background_preservation_test.dart test/providers/explore_feed_refresh_retention_test.dart
- flutter analyze lib/widgets/feed_refresh_control.dart lib/widgets/composable_video_grid.dart lib/widgets/classic_vines_tab.dart lib/widgets/new_videos_tab.dart lib/widgets/popular_videos_tab.dart lib/widgets/for_you_tab.dart lib/providers/classic_vines_provider.dart test/widgets/feed_refresh_control_test.dart test/providers/classic_vines_refresh_test.dart
- pre-commit hook: format, analyze, generated-file verification
- pre-push hook: generated-file verification and changed-file tests

### CODE REVIEW

File: mobile/lib/widgets/feed_refresh_control.dart [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+
+  void _scheduleAutoRefreshIfNeeded() {
+    if (!widget.autoRefresh || _autoRefreshStarted) {
+      return;
+    }
+
+    _autoRefreshStarted = true;
+    WidgetsBinding.instance.addPostFrameCallback((_) {
+      if (!mounted) return;
+      final refreshControlState = context
```
Comment (NotThatKindOfDrLiz) [inline mobile/lib/widgets/feed_refresh_control.dart:181]: Auto-refresh now routes through the shared refresh control instead of calling `onRefresh()` directly. That keeps the first retry visually consistent with manual pull-to-refresh and reuses the same indicator/locking path.

File: mobile/lib/widgets/classic_vines_tab.dart [hunk 2]
```diff
@@ -62,9 +64,17 @@ class _ClassicVinesTabState extends ConsumerState<ClassicVinesTab> {
       category: LogCategory.video,
     );
 
-    // If REST API not available (or still checking), show unavailable state
-    if (!isAvailable) {
-      return const _ClassicVinesUnavailableState();
+    if (isAvailableAsync.isLoading) {
```
Comment (NotThatKindOfDrLiz) [inline mobile/lib/widgets/classic_vines_tab.dart:67]: This guard in the tab is the UI half of the availability fix: while the capability probe is still resolving, we stay on the loading state instead of showing the unavailable state and then flipping back a moment later.

File: mobile/lib/providers/classic_vines_provider.dart [hunk 3]
```diff
@@ -293,8 +287,7 @@ int classicVinesFeedCount(Ref ref) {
 /// Classic vines require Funnelcake REST API to be available.
 @riverpod
 Future<bool> classicVinesAvailable(Ref ref) async {
-  final funnelcakeAsync = ref.watch(funnelcakeAvailableProvider);
-  return funnelcakeAsync.asData?.value ?? false;
+  return ref.watch(funnelcakeAvailableProvider.future);
```
Comment (NotThatKindOfDrLiz) [inline mobile/lib/providers/classic_vines_provider.dart:290]: This now preserves the real async loading state from `funnelcakeAvailableProvider` instead of collapsing unresolved availability to `false`. That avoids briefly rendering the Classics tab as unavailable while the availability probe is still in flight.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
This looks good to merge.

The follow-up polish tightened the last two UX nits without changing the overall refresh strategy:
- Classics availability now preserves a real loading state instead of briefly collapsing to unavailable while the Funnelcake probe is still resolving.
- Automatic empty-state retries now route through the shared refresh control so they use the same indicator and locking path as manual pull-to-refresh.

I don’t see any remaining blockers.
