### PR TITLE
fix(reposts): cache repost count to prevent stale relay counts after unrepost

### LINKED ISSUE #1292: fix: Repost count does not decreases when removing a repost
### Summary

The repost counter increases by +1 when a user reposts a video, but it fails to decrease by -1 when the action is undone.

### Environment

Build: 1.0.4(357) on iOS and 1.0.4(224) on Android
Device: Samsung A54 and Iphone Se v26.3

### Steps to Reproduce

Open the app
Open a video
Tap the repost button
Check the number increase by +1
Tap the repost button again
Check the amount of repost that the video has.
Close and reopen the app and search for the same video

### Actual Result

Tapping the repost button increases the count correctly. However, if the user removes the repost, the number remains the same.

### Expected Result

The repost counter should be dynamic; it must decrease by 1 when a user removes their repost to reflect the actual number of active reposts.

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/9f14642e-c9b8-4a39-81a0-299bd7d64906

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary

- Adds an in-memory count cache to `RepostsRepository` so that after a repost/unrepost toggle, the adjusted count survives BLoC disposal (e.g. scrolling away and back in the feed)
- `getRepostCount()` now checks the local cache before querying relays via NIP-45 COUNT, which may not reflect Kind 5 deletions promptly
- Cache is cleared on logout via `clearCache()`

Closes #1292

## Test plan

- [x] `RepostsRepository` tests: cached count returned, negative clamped, cache overrides relay, cleared by `clearCache()` (62/62 pass)
- [x] `VideoInteractionsBloc` tests: verify `cacheRepostCount` called with correct adjusted count on repost and unrepost (33/33 pass)
- [x] Analyzer: 0 errors
- [ ] Manual: repost a video, unrepost, scroll away and back — count should reflect the unrepost

### CODE REVIEW

File: mobile/lib/blocs/video_interactions/video_interactions_bloc.dart [hunk 1]
```diff
@@ -246,11 +246,17 @@ class VideoInteractionsBloc
       // Update local state with new repost status and adjusted count
       final currentCount = state.repostCount ?? 0;
       final newCount = isNowReposted ? currentCount + 1 : currentCount - 1;
+      final safeCount = newCount < 0 ? 0 : newCount;
+
+      // Cache the adjusted count in the repository so future BLoC instances
+      // (created when scrolling away and back) use the correct count instead
+      // of a stale NIP-45 COUNT from relays.
+      _repostsRepository.cacheRepostCount(_addressableId, safeCount);
```
Comment (omartinma) [inline mobile/lib/blocs/video_interactions/video_interactions_bloc.dart]: I would recommend having this method is private and accessed directly when calling  toggleRepost in the repository

Comment (realmeylisdev) [reply mobile/lib/blocs/video_interactions/video_interactions_bloc.dart]: Really appreciate your feedback, taking care now
