### PR TITLE
fix(badges): ensure videos show the correct badge like "fully-verified"

### LINKED ISSUE #1688: fix(video): fully-verified videos incorrectly show "V-Original" badge
### Description

Videos always display the **“V-Original”** badge, even when they are fully verified.

The issue appears to be caused by the way raw tags are enhanced with statistics data.  
Once stats are added, the tags are no longer considered empty, which prevents the Proofmode tag loading process from running.

As a result, verified tags are never applied and videos incorrectly remain marked as “V-Original”.

---

### Current Behavior

- Fully verified videos still show the **“V-Original”** badge.
- Proofmode tags are not loaded.
- Verification state is displayed incorrectly.

---

### Expected Behavior

- Verified videos should display the correct verification badge.
- Proofmode tags should load regardless of stats enrichment.
- Badge state should accurately reflect the verification status.

---

### Suspected Cause

- Raw tags are enhanced with stats before Proofmode tag loading occurs.
- Because tags are no longer completely empty, the Proofmode loading step is skipped.
- Incorrect assumption that non-empty tags are already finalized.

### PR DESCRIPTION
**Pull request by hm21**
## Description

Videos always show the “V-Original” badge, even when they are fully verified. The issue was that the raw tags were enhanced with stats, which caused them to stop loading all missing tags. Since the tags were no longer completely empty, that process was skipped.

| Before | After |
| ------- | ------ |
| image | image |

**Related Issue:** Closes #1688

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/utils/video_nostr_enrichment.dart [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+      .map((v) => v.id)
+      .toList();
+
+  if (idsToEnrich.isEmpty) return videos;
+
+  try {
+    // Batch query Nostr relays for the full events
+    final filter = Filter(
+      ids: idsToEnrich,
+      kinds: [34236],
```
Comment (erickzanardo) [inline mobile/lib/utils/video_nostr_enrichment.dart]: any named constant we could use or create here so we don't have a magic number here?

Comment (hm21) [reply mobile/lib/utils/video_nostr_enrichment.dart]: Oh good point, i saw there is already a `NIP71VideoKinds.getAllVideoKinds()` which return `[34236]` so i direclty use that now...
