### PR TITLE
fix(picker): prevent autocorrect re-query + boost followed users

### LINKED ISSUE #3221: fix: user is not showing up in the inspired by seach bar
### Summary

I keep getting this issue. I tried to add [@Liz Sweigart](https://planetary-app.slack.com/team/U05QZP58QUX) as the inspired by, but when I type Liz in the search bar it her name does not pop up. It used to be the 1st account that would pop up for me. Now nothing. Instead 
Her alter ego does (Clawdette) is the 1st one to pop up. 

Also if you try to scroll down they search get promoted again rather than simply scrolling down to see other accounts the search came up with.

### Environment

version 659 
iPhone 12 Pro 26.3
data 

### Steps to Reproduce

capture a video 
click next to the section where you fill out the video  details 
in the inspired by type: Liz or another user you follow 
scroll down if they are not atthe top visable part of the list 

### Actual Result

I was looking to Liz but got her alter ego account Clawdette 
when i scrolled down the app refreshes the search results intested of showing me more users who match my search term 

### Expected Result

either Liz's account show up at the top or near the top of my list or if she is lower down the list i simply scroll down and select her profile. 

### Regression?

No

### Evidence

https://github.com/user-attachments/assets/30ce5147-683e-46ef-88b5-5ecf17911b5a

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #3221

## Summary

The Inspired By user picker had two compounding bugs revealed by the reporter's video:

1. **iOS predictive text silently rewrote the query** (e.g. `"liz"` → `"Liz"`), re-firing `onChanged` and wiping the results list for ~5s while the progressive search restarted. This is what the reporter described as scrolling "refreshing" the search — the trigger was autocorrect, not scroll.
2. **Followed users were not surfaced above globally-popular profiles** with the same substring match. `UserSearchBloc` requests `sortBy: 'followers'` and the repository preserves that server order verbatim, so a popular alter-ego outranks a friend the user follows.

## Root cause trace

Ordering flow from server to screen (all confirmed by reading source):

| Layer | File:Line | Role |
|---|---|---|
| Funnelcake | `funnelcake_api_client.dart:459-461` | Sorts globally by follower count on `sort_by=followers` |
| ProfileRepository | `profile_repository.dart:904-905` | `useServerSort` path preserves server order verbatim; custom `_profileSearchFilter` hook is unreachable here |
| UserSearchBloc | `user_search_bloc.dart:80-84` | Previously emitted server order + cleared results on every new query |
| UserPickerSheet | `user_picker_sheet.dart` | Renders `state.results` as-is |

The TextField lacked `autocorrect: false` / `enableSuggestions: false`, so iOS silently committed predictive suggestions, which fires `onChanged` with a rewritten string → BLoC treats it as a fresh query → clears results → 5s blank while the 3-phase progressive search reruns.

## Changes

- **`TextField`** (`user_picker_sheet.dart`): `autocorrect: false` + `enableSuggestions: false`. Search fields should never autocorrect — industry standard (GitHub, Slack, iOS Spotlight).
- **`UserSearchBloc._onQueryChanged`**: keep the previous query's results visible while a new query loads (stale-results pattern). `offset`/`hasMore` still reset so pagination elsewhere isn't corrupted.
- **`UserSearchBloc`**: optional `FollowRepository` injection + `_boostFollowed` helper. When provided, followed users move to the top of each progressive yield (local → REST → NIP-50) preserving server-relative order within each group. Not applied to `_onLoadMore` — appending pages must not reshuffle already-visible positions.
- **`UserPickerSheet._NetworkResults`**: port the PR #2566 `loading when state.results.isNotEmpty => list` pattern already live in `user_search_view.dart` and `find_people_sheet.dart`, so progressive yields render tiles in place instead of flashing a spinner.

## Scope discipline

Other `UserSearchBloc` consumers (`search_results_page.dart` unified search, `find_people_sheet.dart` DM share) are **unchanged** — they keep today's server ranking. Whether to extend the boost to them is a product decision for a follow-up; their surfaces have different intents (discovery, pre-loaded contacts).

## Steps to reproduce (before this PR)

1. Record a video, tap Next to the metadata screen.
2. Tap the "Inspired By" row.
3. Type a lowercase substring that matches a followed user (e.g. `liz`).
4. Observe that a high-global-followers account with the same substring ranks first.
5. Wait ~1s without typing. iOS predictive text silently capitalizes to `Liz`.
6. The results list blanks. A full-screen spinner covers the sheet for ~5s while the progressive search re-runs.
7. Results return — same ranking, same user(s) missing.

## Expected behavior (after this PR)

1. Typed `liz` stays as `liz`. iOS does not rewrite.
2. Users you follow appear above unfollowed users with the same substring match.
3. Re-queries (pagination, debounce restarts) do not blank the list — previous results remain visible until new ones arrive.
4. Progressive yields update the list in place without a spinner flash.

## Test plan

- [x] `flutter analyze lib test integration_test` → no issues
- [x] `flutter test test/blocs/user_search/` → 37 tests, all pass (4 new + 2 updated for stale-results behavior)
- [x] `flutter test test/widgets/user_picker_sheet_test.dart` → 18 tests, all pass (3 new)
- [x] `flutter test test/widgets/find_people_sheet_test.dart test/widgets/user_search_view_test.dart test/screens/search_results/` → all pass (unchanged consumers, regression guard)
- [ ] Manual device test: run `flutter run`, reproduce the flow above, verify all 4 expected behaviors
- [ ] Manual device test: unified search (`/search-results/`) and DM share sheet — confirm ranking unchanged

## Known limitation

If the followed user's Nostr profile `display_name` / `name` / `about` does not contain the query substring, no client-side fix surfaces them — Funnelcake's search indexes those fields and the local-cache fallback matches on the same ones. For example, if "Liz Sweigart" appears in Nostr as `Elizabeth Sweigart`, typing `liz` still won't match her. A server-side `boost_pubkeys=` parameter on Funnelcake would be the definitive fix and would also let every consumer benefit without per-surface plumbing — worth a follow-up with the backend team.

## Follow-ups worth opening

1. Server-side `boost_pubkeys` param on Funnelcake `search/profiles` so the boost moves off-device.
2. Pagination for the picker (`ScrollPaginationMixin` + `UserSearchLoadMore`) — not reproducing this bug, intentionally out of scope here.
3. Product decision: should unified search (`search_results_page`) and DM share (`find_people_sheet`) adopt the same client-side boost?

### CODE REVIEW

File: mobile/lib/widgets/user_picker_sheet.dart [hunk 1]
```diff
@@ -78,6 +79,10 @@ class UserPickerSheet extends ConsumerStatefulWidget {
   /// Pubkeys to exclude from search results (already selected users).
   final Set<String> excludePubkeys;
 
+  /// Optional timeout forwarded to the internally created [UserSearchBloc].
+  /// Pass `null` in tests that use `pumpAndSettle` to avoid pending timers.
+  final Duration? searchTimeout;
```
Comment (omartinma) [inline mobile/lib/widgets/user_picker_sheet.dart]: I dont think setup a time out on the view that will go to the Bloc is the most optimal solution. Would it be possible to setup something like that directly into the bloc?

File: mobile/lib/blocs/user_search/user_search_bloc.dart [hunk 2]
```diff
@@ -63,19 +71,27 @@ class UserSearchBloc extends Bloc<UserSearchEvent, UserSearchState> {
     // the search to get stuck in loading/empty-success states with no recovery
     // path (the user could never re-trigger the same query).
 
+    // Keep the previous query's results visible while the new search loads,
```
Comment (omartinma) [inline mobile/lib/blocs/user_search/user_search_bloc.dart]: I see we added something on the UI part, which I see as right call, so then i believe this comment is not needed

Comment (realmeylisdev) [reply mobile/lib/blocs/user_search/user_search_bloc.dart]: Agreed — dropped the comment in c128ae6ff.

File: mobile/lib/widgets/user_picker_sheet.dart (hunk 1 above)
Comment (realmeylisdev) [reply mobile/lib/widgets/user_picker_sheet.dart]: Good call — dropped `UserPickerSheet.searchTimeout` entirely in 330b56f7e. Turns out the 3 tests that were passing `null` did not actually need the escape hatch; stream teardown + `BLoC.close()` cancel the timeout timer on their own.
