### PR TITLE
fix: iOS Vertical flip issue after video recording

### LINKED ISSUE #1522: fix: iOS Vertical flip issue after video recording
## Bug Description

On iOS, recorded videos are vertically flipped after recording.

This issue occurs inconsistently but happens most frequently when recording with the front camera. The preview during recording appears correct, but the resulting exported/saved video is vertically mirrored (flipped upside down).

The issue seems related to orientation and/or front camera mirroring handling during the recording or export process.

## Expected Behavior
Recorded videos should maintain the correct orientation and transformation after recording.

Videos recorded with the front camera should:
- Not be vertically flipped
- Preserve the correct rotation

The exported video should visually match what the user sees during recording.

### PR DESCRIPTION
**Pull request by hm21**
## Description

On iOS, recorded videos are vertically flipped after recording.

This issue occurs inconsistently but happens most frequently when recording with the front camera. The preview during recording appears correct, but the resulting exported/saved video is vertically mirrored (flipped upside down).

**Related Issue:** Closes #1522

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/packages/divine_camera/lib/src/widgets/camera_preview_widget.dart [hunk 1]
```diff
@@ -66,8 +85,18 @@ class _CameraPreviewWidgetState extends State<CameraPreviewWidget> {
...
 
     // Calculate normalized coordinates (0.0 - 1.0) based on actual preview size
-    final normalizedX = (localPosition.dx / previewSize.width).clamp(0.0, 1.0);
+    var normalizedX = (localPosition.dx / previewSize.width).clamp(0.0, 1.0);
     final normalizedY = (localPosition.dy / previewSize.height).clamp(0.0, 1.0);
+
+    // If preview is mirrored in Flutter, flip the X coordinate for the camera
+    // The visual focus indicator stays where the user tapped,
+    // but the camera needs the un-mirrored coordinate
+    // coverage:ignore-start
```
Comment (erickzanardo) [inline mobile/packages/divine_camera/lib/src/widgets/camera_preview_widget.dart:94]: Nit: tbh, I would rather lower the coverage of the package as a whole instead of having these comments here

(I am also already assuming there is a good reason to ignore the coverage :P )
