### PR TITLE
fix(video): use transcoded variants and prioritize current video playback

### LINKED ISSUE #2184: iOS video playback jitter: constant buffering oscillation during playback
## Problem

Videos on iOS exhibit constant jittery playback — playing for 300-500ms then buffering for 500-1000ms in a repeating cycle. This is a regression that appeared in the last few releases.

## Evidence from Logs

The currently-playing video (index=0) buffers **12 times in 24 seconds**:

```
play 66ms  → buffer 748ms
play 34ms  → buffer 548ms
play 333ms → buffer 952ms
play 534ms → buffer 690ms
play 400ms → buffer 854ms
play 934ms → buffer 4083ms  ← worst stall
play 900ms → buffer 550ms
play 400ms → buffer 1095ms
play 533ms → buffer 798ms
play 500ms → buffer 5066ms
```

All 3 video controllers load within **5ms of each other** at navigation time, immediately competing for bandwidth.

### Primary: Bandwidth starvation from concurrent downloads

The currently-playing video competes equally with preloaded videos for network bandwidth. There is no prioritization of the active video's download.

- **Prefetch config**: `preloadBefore=2` + `preloadAfter=3` + current = **6 concurrent video downloads**
- **HTTP connection limit**: `maxConnectionsPerHost = 4` in `video_cache_manager.dart`
- **No deferral logic**: Preloads fire immediately regardless of whether the current video has buffered enough to play smoothly

With 6-second MP4 videos over progressive download, the client-side bandwidth is split across too many simultaneous requests, and the active video can't buffer faster than it plays.

**Note**: HLS is not viable for this use case — our videos are too short for HLS segment windows and caching doesn't work well with HLS for short-form content.

**Note**: The media server (media.divine.video) does not limit concurrent connections, so this is purely a client-side bandwidth contention issue.

### Likely Regression: PR #2055 — "smoother full screen video scrolling"

Commit `77b6b261c` (Mar 8) changed video controllers to be **retained when scrolling away** ("video continues from where it was instead of restarting"). This is a 705-line change to `video_feed_item.dart`.

**Before #2055**: Scroll away → controller disposed → download stops → bandwidth freed for current video

**After #2055**: Scroll away → controller retained (still downloading) → bandwidth consumed → current video starved

This change, combined with the aggressive prefetch strategy, means significantly more controllers are alive and actively downloading simultaneously than before.

### Contributing: PR #2060 — Playback watchdog

Commit `ff9cce753` (Mar 9) added a watchdog that auto-resumes playback when the native player pauses unexpectedly. If a video buffers and briefly pauses, the watchdog could fight with the buffer state, causing rapid play→buffer→watchdog-resume→buffer cycles that amplify the jitter.

### Contributing: Widget rebuild churn during buffering

- `ValueListenableBuilder` on the controller rebuilds on **every state change** (position, buffering, size) — potentially 60fps rebuild rate
- `setState()` fires every 2 seconds during loading indicator scheduling
- Each `isBuffering` toggle (true→false→true) triggers a full widget tree rebuild of the video Stack

### 1. Prioritize active video download (High Impact)
Defer preload downloads until the current video has stopped buffering. Don't start preloading index=1,2,3 until index=0 is playing smoothly.

### 2. Reduce preload concurrency (High Impact)
Reduce from 6 concurrent to 2-3:
- `preloadBefore = 1` (was 2)
- `preloadAfter = 1` (was 3)
- Or stagger preloads sequentially instead of in parallel

### 3. Pause retained controllers' downloads (Medium Impact)
If retaining controllers for "continue where you left off", pause their network activity when off-screen. The position can be remembered without keeping the download active.

### 4. Review watchdog interaction with buffering (Medium Impact)
Ensure the playback watchdog doesn't auto-resume during active buffering cycles. The guard `if (value.isBuffering) return;` may not be sufficient if the buffering state toggles rapidly.

### 5. Reduce widget rebuilds during playback (Low Impact)
Decouple buffering state changes from full widget rebuilds. The loading indicator and player widget don't need to rebuild on every position update.

## Key Files

- `lib/mixins/video_prefetch_mixin.dart` — prefetch strategy (preloadBefore/After)
- `lib/services/video_cache_manager.dart` — HTTP connection limits, batch size
- `lib/widgets/video_feed_item/video_feed_item.dart` — player widget, watchdog, rebuild logic
- `lib/providers/individual_video_providers.dart` — controller lifecycle, keepAlive
- `lib/providers/active_video_provider.dart` — auto-cleanup on route changes
- `lib/constants/app_constants.dart` — prefetch constants

## How to Verify

1. Build from before PR #2055 (`git checkout 77b6b261c~1`) and test — if jitter disappears, controller retention is confirmed as the cause
2. Monitor `[POOLED] buffering_event` log frequency — healthy playback should have 0-1 buffering events, not 12+
3. Test on cellular connection to amplify the bandwidth contention effect

### PR DESCRIPTION
**Pull request by dcadenas**
## Description

Videos randomly freeze during scroll, especially on slower phones and networks. The root cause: the app was downloading the original uploaded video (7-21 Mbps archival blob) instead of the optimized transcoded versions that divine-blossom already provides.

**What changed:**

1. **Play the right file** — All Divine videos now use the transcoded 720p (2.5 Mbps) or 480p (1.0 Mbps) variants for playback and caching, cutting bandwidth 3-8x. The raw blob is never played.

2. **Current video loads first** — The feed preloads adjacent videos (2 ahead, 1 behind). Previously all 4 downloads raced simultaneously, starving the visible video. Now the current video downloads first; preloads start only after it's ready.

3. **Slow external video hint** — Videos hosted outside Divine don't have optimized variants. If one takes more than 8 seconds to load, a banner appears with a Skip button. Placeholder UX — copy and design to be refined.

4. **E2E seed generates realistic test data** — The seed script now produces a 15 Mbps source video with real 720p/480p transcoded variants uploaded to MinIO, enabling before/after perf measurement locally.

**Related Issue:** Closes #2184

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code refactor
- [ ] Build configuration change
- [ ] Documentation
- [ ] Chore

### CODE REVIEW

File: mobile/lib/widgets/video_feed_item/actions/share_action_button.dart [hunk 1]
```diff
@@ -129,10 +133,28 @@ class _UnifiedShareSheetState extends ConsumerState<_UnifiedShareSheet> {
...
+      );
+    }
+
+    final bloc = _ensureBloc(profileRepository)!;
     final isOwnContent = _isUserOwnContent();
 
     return BlocProvider.value(
-      value: _bloc,
+      value: bloc,
       child: BlocListener<ShareSheetBloc, ShareSheetState>(
```
Comment (hm21) [inline mobile/lib/widgets/video_feed_item/actions/share_action_button.dart]: I wonder if there's a reason why we don't create the block directly in the build, like `BlocProvider(create: (_) => ...`?

File: mobile/lib/screens/feed/video_feed_page.dart [hunk 2]
```diff
@@ -675,33 +632,43 @@ class _PooledVideoFeedItemContent extends StatelessWidget {
...
+                  index: index,
+                  player: player,
+                  firstFrameFuture:
+                      videoController?.waitUntilFirstFrameRendered,
+                  listSources: listSources,
+                ),
+          ),
+          if (!video.isFromDivineServer)
+            _SlowExternalVideoOverlay(index: index),
+        ],
```
Comment (hm21) [inline mobile/lib/screens/feed/video_feed_page.dart]: Should we put the `_SlowExternalVideoOverlay` into the `overlayBuilder`?

File: mobile/lib/screens/feed/video_feed_page.dart [hunk 3]
```diff
@@ -735,6 +702,80 @@ class _FittedVideoPlayer extends StatelessWidget {
...
+                  TextButton(
+                    onPressed: () {
+                      final nextIndex = feedController.currentIndex + 1;
+                      context
+                          .findAncestorStateOfType<PooledVideoFeedState>()
+                          ?.animateToPage(nextIndex);
+                    },
+                    style: TextButton.styleFrom(
+                      foregroundColor: VineTheme.vineGreen,
+                      padding: const EdgeInsets.symmetric(horizontal: 12),
```
Comment (hm21) [inline mobile/lib/screens/feed/video_feed_page.dart]: Nit I guess there isn't a design for that yet, but I wonder if we should still use the Divine Icon and a style from the VineTheme?

File: mobile/lib/widgets/video_feed_item/actions/share_action_button.dart (hunk 1 above)
Comment (dcadenas) [reply mobile/lib/widgets/video_feed_item/actions/share_action_button.dart]: Refactored, the share button now checks for null before opening and passes the repo as a required param, so we use normal `BlocProvider(create:)`. See 7f2dabe75.

File: mobile/lib/screens/feed/video_feed_page.dart (hunk 2 above)
Comment (dcadenas) [reply mobile/lib/screens/feed/video_feed_page.dart]: Moved it there, 213431188.

File: mobile/lib/screens/feed/video_feed_page.dart (hunk 3 above)
Comment (dcadenas) [reply mobile/lib/screens/feed/video_feed_page.dart]: Updated to `DivineIconName.globe` + `VineTheme.bodyMediumFont()` in the same commit. Placeholder but at least consistent now.
