### PR TITLE
fix(auth): refresh token before Keycast account deletion

### LINKED ISSUE #659: fix: Account / Deletion | P0 | Deleted account can still log in and post and profile remains visible
### Summary

Deleting an account does not fully remove the user profile or content. After deletion, the user can still log in using the same key, access their posts, and navigate the app. Additionally, other users can still find the deleted account and view its profile and posts.

### Environment

App version: 1.0.4 (150 and 166)
OS: iOS v26.2
Device: iPhone Se

### Steps to Reproduce

- Log in to an existing account.
- Go to Settings.
- Tap Delete account and complete the flow.
- Observe that the app indicates the account has been deleted and allows creating a new one.
- Use the same key to log in again.
- Navigate the app and view profile/posts.
- Also from another account, search for the deleted user.

### Actual Result

The deleted account can still log in using the same key.
The user’s profile and posts are still accessible.
Other users can search for and view the deleted profile and its content.

### Expected Result

Deleting an account should permanently remove the user profile and all associated content.
The deleted account should not be able to log in again using the same key.

### Regression?

No

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by realmeylisdev**
## Summary

Closes #659

`deleteKeycastAccount()` silently skipped the Keycast `DELETE /api/user/account` call when the access token expired during the NIP-62 deletion step. This allowed divineOAuth (email/password) users to log back in after "deleting" their account.

### Root cause

`KeycastOAuth.getSession()` returns `null` for expired tokens. `deleteKeycastAccount()` treated `null` as "no Keycast account exists" and returned `(true, null)` — reporting success without ever calling the DELETE endpoint. During deletion (fetch events → publish kind 5 batches → publish kind 62), the short-lived access token could expire before the Keycast call.

### Changes

- **Add `getSessionOrRefresh()`** to `KeycastOAuth` — tries `getSession()` first, falls back to `refreshSession()` when expired
- **Fix `deleteKeycastAccount()`** — use `getSessionOrRefresh()` so expired tokens are refreshed; return failure (not success) when OAuth client exists but session is unavailable
- **Block sign-out for divineOAuth users on Keycast failure** — in `executeAccountDeletion()`, check `authService.isRegistered`; if Keycast deletion fails for a registered user, show error and do NOT sign out (non-OAuth users proceed as before since they have no server account)
- **Update tests** — 3 new `getSessionOrRefresh` unit tests, updated auth service deletion test expectations

### Files changed

| File | Change |
|------|--------|
| `mobile/packages/keycast_flutter/lib/src/oauth/oauth_client.dart` | Add `getSessionOrRefresh()` |
| `mobile/lib/services/auth_service.dart` | Use `getSessionOrRefresh()`, fix null handling |
| `mobile/lib/widgets/delete_account_dialog.dart` | Block on Keycast failure for divineOAuth |
| `mobile/packages/keycast_flutter/test/oauth_client_test.dart` | Add `getSessionOrRefresh` tests |
| `mobile/test/services/auth_service_delete_keycast_account_test.dart` | Update expectations |

## Test plan

- [x] `flutter test test/services/auth_service_delete_keycast_account_test.dart` — 6/6 pass
- [x] `flutter test` in `packages/keycast_flutter` — 70/70 pass (3 new)
- [x] `flutter analyze` — no issues
- [ ] **Manual QA**: divineOAuth user deletes account → cannot re-login with email/password
- [ ] **Manual QA**: divineOAuth with Keycast down → error shown, NOT signed out
- [ ] **Manual QA**: importedKeys user deletes → NIP-62 published, signed out normally
- [ ] **Manual QA**: from another account, deleted user's profile/content is gone

### CODE REVIEW

File: mobile/lib/widgets/delete_account_dialog.dart [hunk 1]
```diff
@@ -291,12 +291,37 @@ Future<void> executeAccountDeletion({
...
+              content: Text(
+                'Could not delete your account from the server. '
+                'Please check your connection and try again.',
+                style: TextStyle(color: VineTheme.whiteText),
+              ),
+              backgroundColor: VineTheme.error,
+            ),
+          );
+        }
+        return;
```
Comment (hm21) [inline mobile/lib/widgets/delete_account_dialog.dart:315]: Can we use DivineSnackbar

**Review by hm21 — COMMENTED** [review]
LGTM just one comment regarding "DivineSnackbar"

**Review by hm21 — APPROVED** [review]
