### PR TITLE
fix(file-path): resolve file path issues for iOS compatibility

### LINKED ISSUE #1116: fix: Saved clips appear greyed out and unusable after updates
### Summary

Older video clips in the library become corrupted or inaccessible, appearing as grey placeholders. This clips were before I made the update of the app.

### Environment

Build: 1.0.4(308) on iOS and 1.0.4(173) on Android
Device: Samsung A54 and Iphone Se v26.3

### Steps to Reproduce

User should have clips saved in the app
Open the app
Open the camera
Go to the edit field
Tap the 3 dots
Tap the select clips in library option
Look for the old clips

### Actual Result

Following an app update or new build installation, previously saved clips are displayed as greyed-out images and cannot be used or edited.

### Expected Result

Saved clips should remain valid, accessible, and playable across different app versions and builds.

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/a0836b90-daa9-47b5-a03d-39c321fd5517

### PR DESCRIPTION
**Pull request by hm21**
## Description

Video clips were becoming unusable (greyed out) after iOS app updates. This happened because iOS changes the app container path (e.g., /var/mobile/Containers/Data/Application/ABC123/...) to a new UUID on every app update, but we were storing absolute file paths in SharedPreferences.

**Related Issue:** Closes #1116

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/services/video_editor/video_editor_split_service.dart [hunk 1]
```diff
@@ -93,9 +93,9 @@ class VideoEditorSplitService {
       processingCompleter: Completer<bool>(),
     );
 
-    final cachedDirectory = await getApplicationDocumentsDirectory();
-    final startClipPath = '${cachedDirectory.path}/${startClipId}_start.mp4';
-    final endClipPath = '${cachedDirectory.path}/${endClipId}_end.mp4';
+    final documentsPath = await getDocumentsPath();
+    final startClipPath = '$documentsPath/${startClipId}_start.mp4';
```
Comment (erickzanardo) [inline mobile/lib/services/video_editor/video_editor_split_service.dart]: we probably should use `path` package here

File: mobile/lib/services/video_recorder/camera/camera_macos_service.dart [hunk 2]
```diff
@@ -362,9 +364,7 @@ class CameraMacOSService extends CameraService {
       // Configure audio session for recording BEFORE starting
       await _configureAudioSessionForRecording();
 
-      // Use documents directory for user-accessible persistent storage
-      final documentsDir = await getApplicationDocumentsDirectory();
-      final recordingsDir = Directory('${documentsDir.path}/recordings');
+      final recordingsDir = Directory('${outputDirectory}/recordings');
```
Comment (erickzanardo) [inline mobile/lib/services/video_recorder/camera/camera_macos_service.dart]: Same here

File: mobile/lib/utils/android_path_migration.dart [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+  required List<String?> filePaths,
+}) async {
+  // Only migrate on Android when using app_flutter directory
+  if (kIsWeb || !Platform.isAndroid || !documentsPath.contains('app_flutter')) {
+    return false;
+  }
+
+  var migrated = false;
+  for (final path in filePaths) {
+    if (path != null && path.contains('/files/')) {
```
Comment (erickzanardo) [inline mobile/lib/utils/android_path_migration.dart:23]: These `/` are path separators right? Probably a good idea to also use the `path` package here as well

File: mobile/lib/services/video_editor/video_editor_split_service.dart (hunk 1 above)
Comment (hm21) [reply mobile/lib/services/video_editor/video_editor_split_service.dart]: Fixed db3ba82

File: mobile/lib/services/video_recorder/camera/camera_macos_service.dart (hunk 2 above)
Comment (hm21) [reply mobile/lib/services/video_recorder/camera/camera_macos_service.dart]: Fixed db3ba82

File: mobile/lib/utils/android_path_migration.dart (hunk 3 above)
Comment (hm21) [reply mobile/lib/utils/android_path_migration.dart:23]: The `/` here are not path constructions but string pattern checks (contains('/files/'), contains('app_flutter')). that should detect the old android-specific directory names in existing paths. Since this code only runs on android (Platform.isAndroid) and android always uses / as path separator i guess the path package is not required here, right?
