### PR TITLE
fix(feed): skip and hide session-missing videos

### LINKED ISSUE #3108: fix(feed): skip and hide session-missing videos
Auto-created from PR #3107.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3107
**Branch:** `codex/fix-video-404-skip`

### PR DESCRIPTION
**Pull request by rabble**
Closes #3108

## Summary
- treat active fullscreen `PlaybackStatus.notFound` videos as session-unavailable content
- remove missing videos from in-memory feed and grid data via `VideoEventService.removeVideoCompletely`
- auto-skip the fullscreen feed to the next item and add regression coverage for primary, duplicate, and non-notFound cases

## Test Plan
- [x] flutter test test/screens/feed/pooled_fullscreen_video_feed_screen_test.dart
- [x] dart analyze lib/screens/feed/pooled_fullscreen_video_feed_screen.dart test/screens/feed/pooled_fullscreen_video_feed_screen_test.dart
- [x] pre-push targeted suite for changed files via git hook

### CODE REVIEW

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart [hunk 1]
```diff
@@ -81,6 +82,23 @@ double _scrollDrivenOpacity(double distance) {
   return 0.0;
 }
 
+Future<bool> confirmWebVideoNotFound(
```
Comment (omartinma) [inline mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: I would recommend moving this out of UI layer. It could fit fine on VidesoRepository for example

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart [hunk 2]
```diff
@@ -356,6 +380,21 @@ class _FullscreenFeedContentState extends ConsumerState<FullscreenFeedContent>
     }
   }
 
+  Future<bool> _handleWebVideoLoadError(VideoEvent video, int index) async {
```
Comment (omartinma) [inline mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: I believe this could stay on the bloc FullscreenFeedBloc, and then from UI we would have something like:

```
  onActiveVideoLoadError: (video, index) {
    context.read<FullscreenFeedBloc>().add(
      FullscreenFeedWebVideoLoadFailed(video.id, video.videoUrl ?? ''),
    );
  }
```

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart [hunk 3]
```diff
@@ -772,6 +820,24 @@ class _PooledFullscreenItemContentState
     unawaited(feedState.animateToPage(widget.index + 1));
   }
 
+  Future<void> _handleNotFoundVideo(BuildContext context) async {
```
Comment (omartinma) [inline mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: This could be moved to FullscreenFeedBloc too

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart [hunk 4]
```diff
@@ -794,6 +860,19 @@ class _PooledFullscreenItemContentState
...
+    final playbackStatus = context.select(
+      (VideoPlaybackStatusCubit cubit) => cubit.state.statusFor(video.id),
+    );
+
+    if (widget.isActive &&
+        playbackStatus == PlaybackStatus.notFound &&
+        !_handledNotFound) {
+      WidgetsBinding.instance.addPostFrameCallback((_) {
+        if (!mounted) return;
+        unawaited(_handleNotFoundVideo(context));
```
Comment (omartinma) [inline mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: This would be much cleaner triggered by a bloc listener once the comments above are completed

**Comment by rabble** [comment]
**Self-review — requesting changes on my own PR** (GitHub wouldn't let me mark it formally).

The user-visible outcome (auto-skip 404 videos) is a real improvement and the fullscreen skip tests are thorough. But the implementation crosses several architecture lines, and there's a silent-failure risk where a transient error can permanently hide a video session-wide.

## Blockers

**1. Business logic inside `VideoFeedItem.build()` — directly forbidden by `.claude/rules/architecture.md`.** At `mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart:816-823`, inside `VideoFeedItem.build`, the widget reads playback status, schedules a post-frame callback, then calls a mutation on a service (`removeVideoCompletely`) and drives navigation (`animateToPage`). Side effects launched from `build()` + filtering/removal orchestration in a widget is exactly the pattern the rule calls "WRONG." Move this behind a BLoC event (e.g. a `FullscreenFeedBloc` event `FullscreenFeedVideoUnavailable(videoId)`) consumed by a `BlocListener`.

**2. Silent-failure risk — `notFound` is not confirmed to mean "gone forever" on native.** `pooled_fullscreen_video_feed_screen.dart:772-788`: the native path removes the video from **all** feeds and grids based purely on the cubit's `PlaybackStatus.notFound`. Only the web path calls `confirmWebVideoNotFound` (HEAD check). A transient playback error that `VideoFeedController._classifyError` happens to classify as `notFound` (intermittent CDN hiccup, DNS glitch, AVPlayer quirk) will permanently hide the video across every feed surface for the session. Either mirror the HEAD-confirm on native, require N consecutive failures, or tighten the classifier before mutating global state.

**3. `context.findAncestorStateOfType<PooledVideoFeedState>()` across an async gap** — `pooled_fullscreen_video_feed_screen.dart:779`. A feed **item** is grabbing the parent feed's `State` object and driving navigation on it. Couples `VideoFeedItem` to a specific ancestor implementation and bypasses the BLoC/event model. Lookup after an `await` is also brittle under dispose — the null check saves it but this is exactly what BLoC events are for.

## Should-fix

**4. Two independent "is missing" detectors that will drift.**
- Native: `PlaybackStatus.notFound` from `VideoPlaybackStatusCubit` read inside `VideoFeedItem.build` (line 812-823).
- Web: HEAD check in `_handleWebVideoLoadError` (line 380-394).

Different triggers, different dedupe sets (`_handledNotFound` bool on item, `_handledWebNotFoundVideoIds` set on screen). Same behavior should be driven from one source of truth.

**5. Grid "hide" relies on `VideoEventService.notifyListeners`.** Any grid that reads the service without subscribing to the notifier won't refresh. PR description claims "hide from grids" but there's no grid-side test proving it.

**6. No "video becomes available again" test.** `_locallyDeletedVideoIds` (`video_event_service.dart:203, 893`) is never cleared during the session. If a transient 404 resolves, pagination keeps rejecting that id — permanently hidden until app restart. At minimum, needs an explicit test that this is the intended behavior.

**7. Web test asserts `onActiveVideoLoadError` fires but never asserts `removeVideoCompletely` was called** — `web_video_feed_test.dart`. The integration from HEAD-404 → service mutation is untested.

**8. `findAncestorStateOfType` call in an async gap** — even with the null guard, this is fragile under dispose. Promote to a BLoC event.

## Nits

- `_handledNotFound` is mutable widget instance state. Works, but reinforces that the whole flow belongs in a BLoC.
- `unawaited` on the scheduled removal at line 821 swallows `animateToPage` exceptions. At least log them.
- `confirmWebVideoNotFound` lumps 403/410/500 in with 200 (returns `false`). Safer than the native path but worth a comment documenting the decision.

## What was done well

- Happy-path fullscreen-skip tests are thorough (primary, duplicate-fire suppression, non-`notFound` exclusion).
- Full 64-char Nostr IDs used in tests (satisfies the project-wide rule).
- No `errorMessage` / `Exception?` leaking into state (satisfies `.claude/rules/state_management.md`).
- Web HEAD-confirm is the right instinct — distinguishes real-404 from player hiccups. Pull that pattern into the native path too.
- `_handledNotFound` flag prevents duplicate fire per item.
- Hitchhiking web autoplay fix at `web_video_player.dart:111-118` is a legitimate improvement.

## Open questions

1. Why does HEAD-confirm only apply to web? On native, `VideoFeedController._classifyError` classifies generic Divine-hosted failures as `notFound`, so one flaky player init removes the video everywhere. What protects against that?
2. Should the PR also register the id with a "hidden this session" set at the repository layer so grids loading *after* removal (e.g. user opens their profile after a skip) also filter it?
3. The PR scope includes unrelated `web_video_player.dart` cover-box resizing. Per `.claude/rules/code_style.md` "PR Scope" — intentional?
4. Does the grid actually update? PR body claims it but there's no test and no reactive subscription path visible in the diff.

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart (hunk 1 above)
Comment (rabble) [reply mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: Moved out of UI in 3f6ff87f. Extracted into `MediaAvailabilityChecker` (mobile/lib/services/media_availability_checker.dart) — a small injectable service that issues the HEAD and returns `isConfirmedMissing`. The checker is injected into `FullscreenFeedBloc`, so the BLoC owns the 404-confirmation decision and the widget no longer makes HTTP calls.

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart (hunk 2 above)
Comment (rabble) [reply mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: Moved to the BLoC in f39bfe439. There is now a `FullscreenFeedVideoUnavailable(videoId)` event; the widget handler is reduced to dispatching it and the BLoC does the HEAD check, the dedupe via `removedVideoIds`, the `onRemoveVideo` callback, and emits a `pendingSkipTarget`. The handler also uses `transformer: sequential()` so concurrent error events can't race the dedupe.

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart (hunk 3 above)
Comment (rabble) [reply mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: Moved to the BLoC in f39bfe439 / a36c4d918. The per-item `_handleNotFoundVideo` is gone — `FullscreenFeedVideoUnavailable` does the removal on the BLoC side and emits `pendingSkipTarget`, which the screen consumes to animate via `_animateToPage` and then dispatches `FullscreenFeedSkipAcknowledged` so the BLoC clears the signal.

File: mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart (hunk 4 above)
Comment (rabble) [reply mobile/lib/screens/feed/pooled_fullscreen_video_feed_screen.dart]: Replaced with BlocListeners in a36c4d918. The `context.select` + `addPostFrameCallback` pattern in `_PooledFullscreenItemContent.build` is gone. Two screen-level listeners handle it instead:

1. `BlocListener<VideoPlaybackStatusCubit>` dispatches `FullscreenFeedVideoUnavailable` when the active video's status becomes `notFound` (with `removedVideoIds` dedupe).
2. `BlocListener<FullscreenFeedBloc>` reacts to `pendingSkipTarget`, animates the feed, and dispatches `FullscreenFeedSkipAcknowledged`.

No more per-item post-frame callbacks walking the ancestor tree.

**Review by NotThatKindOfDrLiz — APPROVED** [review]
Approved. I re-reviewed the updated head and the remaining blocker is addressed: confirmed-missing videos now reconcile the native pooled controller instead of only pruning BLoC/source state, so stale removed videos should not remain playable or shift indices.

I also checked the 404 flow end to end: the BLoC owns HEAD confirmation, dedupe, removal, and pending skip signaling; web/native UI code just bridges player errors into that flow. The conservative replaceVideos rebuild on non-append-only changes is an acceptable tradeoff for correctness here.

Latest checks are green, including Mobile CI, Pooled Video Player CI, generated files, analyze, format, tests, web preview, semantic PR, mergeability, and CLA.
