### PR TITLE
fix(profile): ensure video total count is correct and scroll works

### LINKED ISSUE #2783: fix(profile): ensure video total count is correct and scroll works
Auto-created from PR #2782.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2782
**Branch:** `fix/profile-full-screen`

### PR DESCRIPTION
**Pull request by hm21**
## Description

In the user profile, the total video count was always capped at 50. Only after scrolling to load more videos did the count update to the correct number.

Additionally, this PR fixes a scrolling issue where the grid did not expand to full screen while scrolling.

This was reported on Discord [here](https://discord.com/channels/1470168817589158040/1470255950408454164/1490422987994828942)

**Related Issue:** Closes #2783

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart [hunk 1]
```diff
@@ -109,15 +109,16 @@ class FunnelcakeApiClient {
...
+  /// `totalCount` parsed from the `X-Total-Count` response header.
   ///
   /// Throws:
   /// - [FunnelcakeNotConfiguredException] if the API is not configured.
   /// - [FunnelcakeNotFoundException] if the author is not found.
   /// - [FunnelcakeApiException] if the request fails with a non-success status.
   /// - [FunnelcakeTimeoutException] if the request times out.
   /// - [FunnelcakeException] for other errors.
-  Future<List<VideoStats>> getVideosByAuthor({
+  Future<({List<VideoStats> videos, int? totalCount})> getVideosByAuthor({
```
Comment (omartinma) [inline mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart]: Wondering if it is worth to create a VideosByAuthor response model

Comment (hm21) [reply mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart]: Thanks @omartinma, that’s a really good suggestion and I’ve quickly implemented it :)

Btw I’m wondering if we should also consider refactoring other methods in that file, like `Future<Map<String, dynamic>?> getUserProfile`, since it still uses a dynamic instead of what I assume should be a `sealed class`. If you agree a refactor would make sense, I would love to create a task so we can tackle it later when we have some time.

Comment (omartinma) [reply mobile/packages/funnelcake_api_client/lib/src/funnelcake_api_client.dart]: I think makes total sense @hm21 , go for it!
