### PR TITLE
fix: Browsing to the Home screen takes endlessly 

### LINKED ISSUE #687: fix:  Home screen | P0 | Browsing to the Home screen takes endlessly
### Summary

Home screen loads endlessly if user is not following anyone. If the user starts to follow a user the home screen loads. Once you unfollow that user the issue occurs again.

### Environment

App version:  1.0.4 build 168
Device: iPhone XS iOS 18.6

### Steps to Reproduce

1. Open the app
2. Browse to Home

### Actual Result

Home page loads endlessly regardless a new user or an existing user. 

### Expected Result

Home screen loader should stop after a few secs and either display it empty or with the content of an existing user.

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/85a21a3a-2bb4-461b-9f3c-feddb286cf43

### PR DESCRIPTION
**Pull request by hudson-proenca**
## Description

**Related Issue:** Closes #687

https://github.com/user-attachments/assets/a60d202b-0e2b-4bf0-a9d1-4d87255257c3

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/providers/home_feed_provider.dart [hunk 1]
```diff
@@ -164,7 +164,7 @@ class HomeFeed extends _$HomeFeed {
         hasMoreContent: false,
         isLoadingMore: false,
         error: null,
-        lastUpdated: null,
+        lastUpdated: DateTime.now(),
```
Comment (matiasleyba) [inline mobile/lib/providers/home_feed_provider.dart]: I'm not sure how this fixes the issue 🤔 I see this logic is intended to emit an empty state but we are loading the data....
Also it seems we are showing the empty state for a second before showing the data, I think this behavior is new.

Comment (hudson-proenca) [reply mobile/lib/providers/home_feed_provider.dart]: In the home_screen_router we have this logic
image

When we are not following anyone, the `videos.isEmpty` is always gonna be true, but in the home_feed_provider we were sending a null lastUpdated if the user doesn't follow anyone, so it was getting in this loop
```dart
if (followingPubkeys.isEmpty) {
      // Return empty state if not following anyone
      keepAliveLink.close();
      return VideoFeedState(
        videos: [],
        hasMoreContent: false,
        isLoadingMore: false,
        error: null,
        lastUpdated: null,
      );
```

Let me try to see if there is a smarter way to fix this

Comment (hudson-proenca) [reply mobile/lib/providers/home_feed_provider.dart]: @matiasleyba pushed a change that only updates the state after we are sure we fetched the social data (following information). I think the lastUpdated change is the right path to go, but now we will only do that after we got the info we wanted. Now the empty state flashing before loading the video isn't showing anymore.

What do you think?

**Review by omartinma — APPROVED** [review]
