### PR TITLE
fix: profile back button

### LINKED ISSUE #709: fix: profiles not using back button
### Summary

Viewing a user's profile shows the hamburger menu when it should use a back button.

### Environment

Version: 1.0.4+146
Device: iPhone 16
OS: iOS 18.5

### Steps to Reproduce

1. Tap to open a video
2. Tap the author's name tag
3. Verify the author's profile is displayed
4. Note the hamburger menu

### Actual Result

A hamburger menu is displayed on other users' profiles.

### Expected Result

A back button is displayed on other users' profiles and I can navigate "back" one step by tapping it.

### Regression?

Unknown

### Evidence

https://github.com/user-attachments/assets/b22e843b-acb4-4e46-9227-88432cfc6e30

### PR DESCRIPTION
**Pull request by andyhorn**
## Description

Add support for showing the back button when viewing another user's profile and "popping" back to the 
previous view when tapping it.

  * Add a nav extension for pushing a profile route
  * Update routing to user profiles to use push methods
  * Update the AppShell to display the back button for other user profiles

**Related Issue:** Closes #709

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: mobile/lib/router/nav_extensions.dart [hunk 1]
```diff
@@ -110,6 +110,36 @@ extension NavX on BuildContext {
     );
   }
 
+  /// Push profile in grid mode (no video playing) - use for other users' profiles
+  void pushProfileGrid(String identifier) {
+    // Handle 'me' special case - need to get current user's hex
+    String? currentUserHex;
```
Comment (matiasleyba) [inline mobile/lib/router/nav_extensions.dart:117]: Just a thought but I'd add a TODO to review this later. It seems strange to me to have all this logic here; I think the router or the screen itself is a more appropriate place.

Comment (matiasleyba) [reply mobile/lib/router/nav_extensions.dart:117]: feel free to resolve

Comment (andyhorn) [reply mobile/lib/router/nav_extensions.dart:117]: @matiasleyba I agree, but I didn't want to go changing everything haha

I think we have a ticket already for improving navigation; I'll try and find it and add a TODO with the ticket number to these extensions 👍
