### PR TITLE
fix(timestamps): convert notification date headers to local time

### LINKED ISSUE #2694: fix(timestamps): convert Nostr timestamps and notifications timestamps
Auto-created from PR #2693.

**PR:** https://github.com/divinevideo/divine-mobile/pull/2693
**Branch:** `fix/nostr-utc-timestamps-and-notification-source-created-at`

### PR DESCRIPTION
**Pull request by realmeylisdev**
Closes #2694

## Summary

- Fixes notification screen date headers (`_shouldShowDateHeader`, `_getDateHeader`) that access `.year`/`.month`/`.day`/`.weekday` on UTC `DateTime` objects without converting to local time first
- Companion fix to PR #2693 which changed `NotificationModel.timestamp` to UTC but missed these two display-boundary methods
- Without this fix, users east of UTC can see late-evening notifications under the wrong day header

## What changed

**`notifications_screen.dart`** — added `.toLocal()` before extracting date components:
- `_shouldShowDateHeader()`: converts both `current.timestamp` and `previous.timestamp` to local before comparing calendar days
- `_getDateHeader()`: converts the incoming UTC `date` to local before extracting `.year/.month/.day/.weekday` and formatting with `DateFormat`

## Test plan

- [ ] Set device timezone to **UTC+12** → open Notifications → verify date headers ("Today", "Yesterday", day names) match local calendar
- [ ] Set device timezone to **UTC-12** → repeat above
- [ ] Find a notification created near midnight UTC → verify it appears under the correct local-date header
- [ ] Verify relative timestamps ("3m ago", "2h ago") are unaffected by timezone changes

### CODE REVIEW

File: mobile/lib/screens/notifications_screen.dart [hunk 1]
```diff
@@ -413,9 +416,9 @@ class _NotificationTabContentState
         'Saturday',
         'Sunday',
       ];
-      return weekdays[date.weekday - 1];
+      return weekdays[local.weekday - 1];
     } else {
-      return DateFormat.yMd().format(date);
+      return DateFormat.yMd().format(local);
     }
```
Comment (hm21) [inline mobile/lib/screens/notifications_screen.dart]: I think it would be better when we use our internal `time_formatter` package and completely remove that method.
