### PR TITLE
fix(app): downgrade recoverable media load errors

### LINKED ISSUE #3090: fix(app): downgrade recoverable media load errors
Auto-created from PR #3089.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3089
**Branch:** `codex/fix-media-fetch-crashlytics`

### PR DESCRIPTION
**Pull request by rabble**
Closes #3090

## Summary
- classify repeated media and image loading Flutter errors as recoverable instead of letting Crashlytics mark them fatal
- handle CDN 404s, Divine media DNS failures, interrupted media downloads, and invalid image data through the shared classifier in the global Flutter error handler
- add regression coverage for the Crashlytics signatures so future changes keep these failures non-fatal

## Test Plan
- [x] flutter test test/utils/recoverable_flutter_error_test.dart
- [x] dart analyze lib/main.dart lib/utils/recoverable_flutter_error.dart test/utils/recoverable_flutter_error_test.dart
- [x] pre-push targeted suite for changed files via git hook

### CODE REVIEW

**Review by NotThatKindOfDrLiz — APPROVED** [review]
LGTM.

This is a focused Crashlytics-noise reduction fix. The classifier is isolated, the known media/image load signatures are covered by tests, and the errors are still reported to Crashlytics as non-fatal rather than being swallowed. Calling FlutterError.presentError also preserves local/debug visibility.

One note: not every classifier path is host-scoped. DNS failures and interrupted media downloads are limited to known media hosts, but image 404s and invalid image data are classified by Flutter image-loading context. That seems acceptable for recoverable resource-load failures, but it is worth keeping in mind if this list expands.

Fine to merge.

File: mobile/lib/utils/recoverable_flutter_error.dart
Comment (omartinma) [inline mobile/lib/utils/recoverable_flutter_error.dart:1]: Approach is good, but we introduced some String verification and those are all Flutter/Dart SDK internal strings. Line 21 references an internal file path (_network_image_io). Any of these could change silently on an SDK upgrade. Suggest adding a comment near line 14 noting these depend on SDK internals and should be re-verified on major Flutter upgrades.

File: mobile/lib/utils/recoverable_flutter_error.dart [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+};
+
+/// Returns a non-fatal reporting reason when a Flutter error represents a
+/// recoverable media or image loading failure.
+String? classifyRecoverableFlutterError(FlutterErrorDetails details) {
+  final error = details.exception.toString();
+  final library = details.library ?? '';
+  final context = details.context?.toDescription() ?? '';
+
+  final isImage404 =
```
Comment (omartinma) [inline mobile/lib/utils/recoverable_flutter_error.dart:29]: Is intention that this does not call _containsRecoverableMediaHost?

File: mobile/lib/utils/recoverable_flutter_error.dart [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+  'v.cdn.vine.co',
+  'cdn.vine.co',
+};
+
+/// Returns a non-fatal reporting reason when a Flutter error represents a
+/// recoverable media or image loading failure.
+String? classifyRecoverableFlutterError(FlutterErrorDetails details) {
+  final error = details.exception.toString();
+  final library = details.library ?? '';
+  final context = details.context?.toDescription() ?? '';
```
Comment (omartinma) [inline mobile/lib/utils/recoverable_flutter_error.dart:23]: We could create here a property for the result of _containsRecoverableMediaHost and simply reuse it on any of the checks below so that we process that just one time

File: mobile/lib/utils/recoverable_flutter_error.dart
Comment (rabble) [reply mobile/lib/utils/recoverable_flutter_error.dart:1]: Added a dartdoc block on `classifyRecoverableFlutterError` calling out that `_network_image_io`, `image codec`, `image resource`, etc. are SDK-internal strings that need re-verification on major Flutter upgrades. Commit 6415ea79c.

File: mobile/lib/utils/recoverable_flutter_error.dart (hunk 1 above)
Comment (rabble) [reply mobile/lib/utils/recoverable_flutter_error.dart:29]: Intentional — image 404s from any source (Gravatar, third-party thumbnails, nostr profile avatars, etc.) are recoverable because the widget falls back to a placeholder. The Flutter image-loading context (`_network_image_io`/`image codec`/`image resource`) narrows the match to image loads regardless of host. Added an inline comment making this explicit in 6415ea79c.

File: mobile/lib/utils/recoverable_flutter_error.dart (hunk 2 above)
Comment (rabble) [reply mobile/lib/utils/recoverable_flutter_error.dart:23]: Done — hoisted `_containsRecoverableMediaHost(error)` into a `hasRecoverableMediaHost` local at the top of the function and reused it for both `isMediaHostLookup` and `isInterruptedMediaDownload`. Commit 6415ea79c.
