### PR TITLE
fix(video-editor): localize copy and harden macos recording

### LINKED ISSUE #3250: fix(video-editor): localize copy and harden macos recording
Auto-created from PR #3249.

**PR:** https://github.com/divinevideo/divine-mobile/pull/3249
**Branch:** `codex/pr-3142-translation`

### PR DESCRIPTION
**Pull request by rabble**
Closes #3250

## Summary
- localize remaining video editor instruction copy and regenerate l10n output
- add ARB coverage for the PR 3142 follow-up keys while allowing existing profile translation debt
- harden macOS camera recording cleanup when preview frames or first writer frames never arrive

## Test Plan
- [x] dart test test/l10n/arb_consistency_test.dart
- [x] flutter test test/widgets/video_clip_editor/gallery/video_editor_gallery_instruction_text_test.dart test/screens/video_editor/video_audio_editor_timing_screen_test.dart
- [x] flutter test test/divine_camera_test.dart from mobile/packages/divine_camera
- [x] repo pre-push selected tests, 181 passed
- [x] flutter analyze --no-pub via pre-commit hook
- [x] flutter build macos --debug

### CODE REVIEW

File: mobile/lib/l10n/generated/app_localizations.dart [hunk 1]
```diff
@@ -9470,6 +9512,12 @@ abstract class AppLocalizations {
   /// **'Hold to reorder'**
   String get videoEditorLayerReorderHint;
 
+  /// No description provided for @videoEditorLayers.
+  ///
+  /// In en, this message translates to:
+  /// **'Layers'**
+  String get videoEditorLayers;
```
Comment (hm21) [inline mobile/lib/l10n/generated/app_localizations.dart]: This translation isn’t used anywhere and only exists in the l10n files, so we can remove it.

File: mobile/test/screens/video_editor/video_audio_editor_timing_screen_test.dart [hunk 2]
```diff
@@ -185,6 +186,20 @@ void main() {
...
+      await tester.pump();
+
+      expect(
+        find.text('Wähle den Audiobereich für dein Video aus'),
+        findsOneWidget,
+      );
+      expect(
+        find.text('Select the audio segment for your video'),
+        findsNothing,
+      );
```
Comment (hm21) [inline mobile/test/screens/video_editor/video_audio_editor_timing_screen_test.dart:212]: nit: Instead of using hardcoded strings in tests, we could access the l10n files directly so that if a translation changes, the tests won’t fail because of it.
Note that most of our test files still use hardcoded strings like this, so I’ll quickly create another PR to update the Claude rules.


```suggestion
      expect(
        find.text(
          lookupAppLocalizations(const Locale('de')).videoEditorAudioSegmentInstruction,
        ),
        findsOneWidget,
      );
      expect(
        find.text(
          lookupAppLocalizations(const Locale('en')).videoEditorAudioSegmentInstruction,
        ),
        findsNothing,
      );
```

**Review by hm21 — APPROVED** [review]
LGTM great fix. I left two minor comments, but nothing blocking.

File: mobile/lib/l10n/generated/app_localizations.dart (hunk 1 above)
Comment (rabble) [reply mobile/lib/l10n/generated/app_localizations.dart]: Fixed in dd0cdd2ab: removed the unused `videoEditorLayers` message from ARBs and regenerated l10n outputs.

File: mobile/test/screens/video_editor/video_audio_editor_timing_screen_test.dart (hunk 2 above)
Comment (rabble) [reply mobile/test/screens/video_editor/video_audio_editor_timing_screen_test.dart:212]: Fixed in dd0cdd2ab: the timing-screen assertions now read `videoEditorAudioSegmentInstruction` through `lookupAppLocalizations` for both German and English.
