### PR TITLE
fix(search): preserve results when switching tabs (#2093)

### LINKED ISSUE #2093: fix: Search results lost when switching between tabs
## Summary
When searching for content on the search screen, switching between tabs causes the previously searched results to be lost.

## Environment
- App version: Latest
- Device: All
- Network: N/A

## Steps to Reproduce
1. Go to the Search screen
2. Enter a search query
3. View results on the current tab
4. Switch to a different tab
5. Switch back to the original tab

## Actual Result
The search results from the original tab are gone. The user has to search again.

## Expected Result
Search results should persist across tab switches. Previously loaded results should still be visible when returning to a tab.

## Regression?
Unknown

### PR DESCRIPTION
**Pull request by nikitawvi**
## Description

When switching between search tabs (Videos / Users / Hashtags), results were lost and the user had to search again.

**Changes:**

1. **BLoC (video_search, user_search, hashtag_search):** When `fetchResults` is `false` for the same `query`, existing loaded results are preserved and only `resultCount` is updated via `copyWith`, instead of resetting `videos`/`results` and `status`.

2. **SearchScreen:** In `_onTabChanged`, `_dispatchSearchForActiveTabIfNeeded` is called instead of `_dispatchSearch`. This method checks whether state already exists for the current query; if so, it does not trigger a full search again.

3. **Tests:** Added/updated tests for preserving results when `fetchResults` is `false` and when switching tabs.

**Related Issue:** Closes #2093

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by nikitawvi** [comment]
Hi! @omartinma 

I made a pull request, can you please review it?

File: mobile/lib/screens/pure/search_screen_pure.dart [hunk 1]
```diff
@@ -148,6 +149,41 @@ class _SearchScreenPureState extends ConsumerState<SearchScreenPure>
     );
   }
 
+  void _dispatchSearchForActiveTabIfNeeded(String query) {
```
Comment (omartinma) [inline mobile/lib/screens/pure/search_screen_pure.dart]: All this logic would fit better on the bloc side, to avoid loading unnecessary logic into the UI

Comment (nikitawvi) [reply mobile/lib/screens/pure/search_screen_pure.dart]: Done
